// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Popover } from './Popover';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Popover: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-38872-21191", title: "Components/Elastic UI/Popover [38872:21191]",
  component: Popover, tags: ['autodocs'],
  args: {"Header#38265:0": true, "Footer#38265:5": true, "Arrow": "3:00 →"},
  argTypes: {"Header#38265:0": {"control": "boolean", "description": "Свойство Figma: Header", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Footer#38265:5": {"control": "boolean", "description": "Свойство Figma: Footer", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Arrow": {"control": "inline-radio", "description": "Свойство Figma: Arrow", "table": {"category": "Figma", "defaultValue": {"summary": "3:00 →"}}, "options": ["12:00 ↑", "3:00 →", "6:00 ↓", "9:00 ←"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "38872:21191", exportName: "Popover", docs: { description: { component: "Popover — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=38872-21191) · 4 вариантов." } } },
} satisfies Meta<typeof Popover>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="38872:21191" component={Popover} storyId="ds-38872-21191"/> };
/** Arrow: 3:00 → */
export const Variant001: Story = { name: "Arrow: 3:00 →", args: {"Arrow": "3:00 →"}, tags: ["!autodocs"] };
/** Arrow: 6:00 ↓ */
export const Variant002: Story = { name: "Arrow: 6:00 ↓", args: {"Arrow": "6:00 ↓"}, tags: ["!autodocs"] };
/** Arrow: 12:00 ↑ */
export const Variant003: Story = { name: "Arrow: 12:00 ↑", args: {"Arrow": "12:00 ↑"}, tags: ["!autodocs"] };
/** Arrow: 9:00 ← */
export const Variant004: Story = { name: "Arrow: 9:00 ←", args: {"Arrow": "9:00 ←"}, tags: ["!autodocs"] };
