// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ExpressionColumn } from './ExpressionColumn';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ExpressionColumn: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14850-110142", title: "Components/Elastic UI/Expression - Column [14850:110142]",
  component: ExpressionColumn, tags: ['autodocs'],
  args: {"Clickable": "True", "Active": "False", "Color": "Success", "Invalid": "False"},
  argTypes: {"Clickable": {"control": "inline-radio", "description": "Свойство Figma: Clickable", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Active": {"control": "inline-radio", "description": "Свойство Figma: Active", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Color": {"control": "select", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Success"}}, "options": ["Success", "Primary", "Accent", "Warning", "Danger", "Subdued"]}, "Invalid": {"control": "inline-radio", "description": "Свойство Figma: Invalid", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14850:110142", exportName: "ExpressionColumn", docs: { description: { component: "&lt;EuiExpression display=&quot;columns&quot;&gt;\n\nColumn expressions are great for lining up multiple expression blocks. The description components usually line up on the right, you can fake this by adding white space to shorter descriptions.\n\nExpressions require both a value and description but they can optionally be clickable/editable.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14850-110142) · 21 вариантов." } } },
} satisfies Meta<typeof ExpressionColumn>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14850:110142" component={ExpressionColumn} storyId="ds-14850-110142"/> };
/** Clickable: True · Active: False · Color: Success · Invalid: False */
export const Variant001: Story = { name: "Clickable: True · Active: False · Color: Success · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Success", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Success · Invalid: False */
export const Variant002: Story = { name: "Clickable: True · Active: True · Color: Success · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Success", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Primary · Invalid: False */
export const Variant003: Story = { name: "Clickable: True · Active: True · Color: Primary · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Primary", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Danger · Invalid: False */
export const Variant004: Story = { name: "Clickable: True · Active: True · Color: Danger · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Danger", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Subdued · Invalid: False */
export const Variant005: Story = { name: "Clickable: True · Active: True · Color: Subdued · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Subdued", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Danger · Invalid: True */
export const Variant006: Story = { name: "Clickable: True · Active: True · Color: Danger · Invalid: True", args: {"Clickable": "True", "Active": "True", "Color": "Danger", "Invalid": "True"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Accent · Invalid: False */
export const Variant007: Story = { name: "Clickable: True · Active: True · Color: Accent · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Accent", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: True · Color: Warning · Invalid: False */
export const Variant008: Story = { name: "Clickable: True · Active: True · Color: Warning · Invalid: False", args: {"Clickable": "True", "Active": "True", "Color": "Warning", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Success · Invalid: False */
export const Variant009: Story = { name: "Clickable: False · Active: False · Color: Success · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Success", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Primary · Invalid: False */
export const Variant010: Story = { name: "Clickable: False · Active: False · Color: Primary · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Primary", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Danger · Invalid: False */
export const Variant011: Story = { name: "Clickable: False · Active: False · Color: Danger · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Danger", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Subdued · Invalid: False */
export const Variant012: Story = { name: "Clickable: False · Active: False · Color: Subdued · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Subdued", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Danger · Invalid: True */
export const Variant013: Story = { name: "Clickable: False · Active: False · Color: Danger · Invalid: True", args: {"Clickable": "False", "Active": "False", "Color": "Danger", "Invalid": "True"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Accent · Invalid: False */
export const Variant014: Story = { name: "Clickable: False · Active: False · Color: Accent · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Accent", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: False · Active: False · Color: Warning · Invalid: False */
export const Variant015: Story = { name: "Clickable: False · Active: False · Color: Warning · Invalid: False", args: {"Clickable": "False", "Active": "False", "Color": "Warning", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Primary · Invalid: False */
export const Variant016: Story = { name: "Clickable: True · Active: False · Color: Primary · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Primary", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Danger · Invalid: False */
export const Variant017: Story = { name: "Clickable: True · Active: False · Color: Danger · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Danger", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Accent · Invalid: False */
export const Variant018: Story = { name: "Clickable: True · Active: False · Color: Accent · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Accent", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Subdued · Invalid: False */
export const Variant019: Story = { name: "Clickable: True · Active: False · Color: Subdued · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Subdued", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Warning · Invalid: False */
export const Variant020: Story = { name: "Clickable: True · Active: False · Color: Warning · Invalid: False", args: {"Clickable": "True", "Active": "False", "Color": "Warning", "Invalid": "False"}, tags: ["!autodocs"] };
/** Clickable: True · Active: False · Color: Danger · Invalid: True */
export const Variant021: Story = { name: "Clickable: True · Active: False · Color: Danger · Invalid: True", args: {"Clickable": "True", "Active": "False", "Color": "Danger", "Invalid": "True"}, tags: ["!autodocs"] };
