// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { HeatmapLegend } from './HeatmapLegend';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** HeatmapLegend: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-83-730", title: "Components/UX-Lab/HeatmapLegend [83:730]",
  component: HeatmapLegend, tags: ['autodocs'],
  args: {"SampleBase#83:4": "84 клика · 18 участников", "DefinitionNote#83:5": "Для текущей страницы, состояния и выборки.", "Mode": "AllClicks"},
  argTypes: {"SampleBase#83:4": {"control": "text", "description": "Свойство Figma: SampleBase", "table": {"category": "Figma", "defaultValue": {"summary": "84 клика · 18 участников"}}}, "DefinitionNote#83:5": {"control": "text", "description": "Свойство Figma: DefinitionNote", "table": {"category": "Figma", "defaultValue": {"summary": "Для текущей страницы, состояния и выборки."}}}, "Mode": {"control": "inline-radio", "description": "Свойство Figma: Mode", "table": {"category": "Figma", "defaultValue": {"summary": "AllClicks"}}, "options": ["AllClicks", "FirstClick"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "83:730", exportName: "HeatmapLegend", docs: { description: { component: "HeatmapLegend — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=83-730) · 2 вариантов." } } },
} satisfies Meta<typeof HeatmapLegend>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="83:730" component={HeatmapLegend} storyId="ds-83-730"/> };
/** Mode: AllClicks */
export const Variant001: Story = { name: "Mode: AllClicks", args: {"Mode": "AllClicks"}, tags: ["!autodocs"] };
/** Mode: FirstClick */
export const Variant002: Story = { name: "Mode: FirstClick", args: {"Mode": "FirstClick"}, tags: ["!autodocs"] };
