// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { HorizontalRule } from './HorizontalRule';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** HorizontalRule: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15154-113938", title: "Components/Elastic UI/☠️ Horizontal Rule [15154:113938]",
  component: HorizontalRule, tags: ['autodocs'],
  args: {"Margin": "Large* - 24px", "Size": "Full"},
  argTypes: {"Margin": {"control": "select", "description": "Свойство Figma: Margin", "table": {"category": "Figma", "defaultValue": {"summary": "Large* - 24px"}}, "options": ["None - 0px", "X-small - 8px", "Small - 12px", "Medium - 16px", "Large* - 24px", "X-large - 32px", "XX-large - 40px"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Full"}}, "options": ["Full", "Half", "Quarter"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15154:113938", exportName: "HorizontalRule", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15154-113938) · 21 вариантов." } } },
} satisfies Meta<typeof HorizontalRule>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15154:113938" component={HorizontalRule} storyId="ds-15154-113938"/> };
/** Margin: X-small - 8px · Size: Full */
export const Variant001: Story = { name: "Margin: X-small - 8px · Size: Full", args: {"Margin": "X-small - 8px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: X-small - 8px · Size: Half */
export const Variant002: Story = { name: "Margin: X-small - 8px · Size: Half", args: {"Margin": "X-small - 8px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: X-small - 8px · Size: Quarter */
export const Variant003: Story = { name: "Margin: X-small - 8px · Size: Quarter", args: {"Margin": "X-small - 8px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: None - 0px · Size: Full */
export const Variant004: Story = { name: "Margin: None - 0px · Size: Full", args: {"Margin": "None - 0px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: None - 0px · Size: Half */
export const Variant005: Story = { name: "Margin: None - 0px · Size: Half", args: {"Margin": "None - 0px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: None - 0px · Size: Quarter */
export const Variant006: Story = { name: "Margin: None - 0px · Size: Quarter", args: {"Margin": "None - 0px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: Small - 12px · Size: Full */
export const Variant007: Story = { name: "Margin: Small - 12px · Size: Full", args: {"Margin": "Small - 12px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: Small - 12px · Size: Half */
export const Variant008: Story = { name: "Margin: Small - 12px · Size: Half", args: {"Margin": "Small - 12px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: Small - 12px · Size: Quarter */
export const Variant009: Story = { name: "Margin: Small - 12px · Size: Quarter", args: {"Margin": "Small - 12px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: Medium - 16px · Size: Full */
export const Variant010: Story = { name: "Margin: Medium - 16px · Size: Full", args: {"Margin": "Medium - 16px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: Medium - 16px · Size: Half */
export const Variant011: Story = { name: "Margin: Medium - 16px · Size: Half", args: {"Margin": "Medium - 16px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: Medium - 16px · Size: Quarter */
export const Variant012: Story = { name: "Margin: Medium - 16px · Size: Quarter", args: {"Margin": "Medium - 16px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: Large* - 24px · Size: Full */
export const Variant013: Story = { name: "Margin: Large* - 24px · Size: Full", args: {"Margin": "Large* - 24px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: Large* - 24px · Size: Half */
export const Variant014: Story = { name: "Margin: Large* - 24px · Size: Half", args: {"Margin": "Large* - 24px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: Large* - 24px · Size: Quarter */
export const Variant015: Story = { name: "Margin: Large* - 24px · Size: Quarter", args: {"Margin": "Large* - 24px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: X-large - 32px · Size: Full */
export const Variant016: Story = { name: "Margin: X-large - 32px · Size: Full", args: {"Margin": "X-large - 32px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: X-large - 32px · Size: Half */
export const Variant017: Story = { name: "Margin: X-large - 32px · Size: Half", args: {"Margin": "X-large - 32px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: X-large - 32px · Size: Quarter */
export const Variant018: Story = { name: "Margin: X-large - 32px · Size: Quarter", args: {"Margin": "X-large - 32px", "Size": "Quarter"}, tags: ["!autodocs"] };
/** Margin: XX-large - 40px · Size: Full */
export const Variant019: Story = { name: "Margin: XX-large - 40px · Size: Full", args: {"Margin": "XX-large - 40px", "Size": "Full"}, tags: ["!autodocs"] };
/** Margin: XX-large - 40px · Size: Half */
export const Variant020: Story = { name: "Margin: XX-large - 40px · Size: Half", args: {"Margin": "XX-large - 40px", "Size": "Half"}, tags: ["!autodocs"] };
/** Margin: XX-large - 40px · Size: Quarter */
export const Variant021: Story = { name: "Margin: XX-large - 40px · Size: Quarter", args: {"Margin": "XX-large - 40px", "Size": "Quarter"}, tags: ["!autodocs"] };
