// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SuperDatePickerDropdown } from './SuperDatePickerDropdown';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SuperDatePickerDropdown: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14792-135915", title: "Components/Elastic UI/Super Date Picker - Dropdown [14792:135915]",
  component: SuperDatePickerDropdown, tags: ['autodocs'],
  args: {"Tab select": "Quick select"},
  argTypes: {"Tab select": {"control": "inline-radio", "description": "Свойство Figma: Tab select", "table": {"category": "Figma", "defaultValue": {"summary": "Quick select"}}, "options": ["Calendar", "Quick select"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14792:135915", exportName: "SuperDatePickerDropdown", docs: { description: { component: "&lt;EuiSuperDatePicker&gt;\n\nRe-design idea to combine quick select and calendar selection into a single popover.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14792-135915) · 2 вариантов." } } },
} satisfies Meta<typeof SuperDatePickerDropdown>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14792:135915" component={SuperDatePickerDropdown} storyId="ds-14792-135915"/> };
/** Tab select: Quick select */
export const Variant001: Story = { name: "Tab select: Quick select", args: {"Tab select": "Quick select"}, tags: ["!autodocs"] };
/** Tab select: Calendar */
export const Variant002: Story = { name: "Tab select: Calendar", args: {"Tab select": "Calendar"}, tags: ["!autodocs"] };
