// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AttemptAction } from './AttemptAction';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** AttemptAction: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-152-996", title: "Components/UX-Lab/AttemptAction [152:996]",
  component: AttemptAction, tags: ['autodocs'],
  args: {"Mode": "Single"},
  argTypes: {"Mode": {"control": "inline-radio", "description": "Свойство Figma: Mode", "table": {"category": "Figma", "defaultValue": {"summary": "Single"}}, "options": ["Single", "Multiple", "Unavailable"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "attempts": {"control": "object", "description": "Данные / обработчик компонента", "table": {"category": "React"}}, "onSelectAttempt": {"control": false, "description": "Данные / обработчик компонента", "table": {"category": "React"}, "action": "onSelectAttempt"}, "onOpenRecording": {"control": false, "description": "Данные / обработчик компонента", "table": {"category": "React"}, "action": "onOpenRecording"}},
  parameters: { layout: "padded", catalogId: "152:996", exportName: "AttemptAction", docs: { description: { component: "AttemptAction — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=152-996) · 3 вариантов." } } },
} satisfies Meta<typeof AttemptAction>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="152:996" component={AttemptAction} storyId="ds-152-996"/> };
/** Mode: Single */
export const Variant001: Story = { name: "Mode: Single", args: {"Mode": "Single"}, tags: ["!autodocs"] };
/** Mode: Multiple */
export const Variant002: Story = { name: "Mode: Multiple", args: {"Mode": "Multiple"}, tags: ["!autodocs"] };
/** Mode: Unavailable */
export const Variant003: Story = { name: "Mode: Unavailable", args: {"Mode": "Unavailable"}, tags: ["!autodocs"] };
