// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SliderLevels } from './SliderLevels';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SliderLevels: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15222-126396", title: "Components/Elastic UI/.📦 Slider  ·  Levels [15222:126396]",
  component: SliderLevels, tags: ['autodocs'],
  args: {"Labels": "True", "Compressed": "False"},
  argTypes: {"Labels": {"control": "inline-radio", "description": "Свойство Figma: Labels", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15222:126396", exportName: "SliderLevels", docs: { description: { component: ".📦 Slider / Levels — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15222-126396) · 4 вариантов." } } },
} satisfies Meta<typeof SliderLevels>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15222:126396" component={SliderLevels} storyId="ds-15222-126396"/> };
/** Labels: True · Compressed: False */
export const Variant001: Story = { name: "Labels: True · Compressed: False", args: {"Labels": "True", "Compressed": "False"}, tags: ["!autodocs"] };
/** Labels: True · Compressed: True */
export const Variant002: Story = { name: "Labels: True · Compressed: True", args: {"Labels": "True", "Compressed": "True"}, tags: ["!autodocs"] };
/** Labels: False · Compressed: False */
export const Variant003: Story = { name: "Labels: False · Compressed: False", args: {"Labels": "False", "Compressed": "False"}, tags: ["!autodocs"] };
/** Labels: False · Compressed: True */
export const Variant004: Story = { name: "Labels: False · Compressed: True", args: {"Labels": "False", "Compressed": "True"}, tags: ["!autodocs"] };
