// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { NumberIndicatorRightSide } from './NumberIndicatorRightSide';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** NumberIndicatorRightSide: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-22764-276696", title: "Components/Elastic UI/.📦Number indicator (right side) [22764:276696]",
  component: NumberIndicatorRightSide, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "22764:276696", exportName: "NumberIndicatorRightSide", docs: { description: { component: ".📦Number indicator (right side) — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=22764-276696) · 1 вариантов." } } },
} satisfies Meta<typeof NumberIndicatorRightSide>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="22764:276696" component={NumberIndicatorRightSide} storyId="ds-22764-276696"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
