// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SliderTrack } from './SliderTrack';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SliderTrack: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-17068-2", title: "Components/Elastic UI/Slider  ·  Track [17068:2]",
  component: SliderTrack, tags: ['autodocs'],
  args: {"Compressed": "False"},
  argTypes: {"Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "17068:2", exportName: "SliderTrack", docs: { description: { component: "Slider / Track — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=17068-2) · 2 вариантов." } } },
} satisfies Meta<typeof SliderTrack>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="17068:2" component={SliderTrack} storyId="ds-17068-2"/> };
/** Compressed: False */
export const Variant001: Story = { name: "Compressed: False", args: {"Compressed": "False"}, tags: ["!autodocs"] };
/** Compressed: True */
export const Variant002: Story = { name: "Compressed: True", args: {"Compressed": "True"}, tags: ["!autodocs"] };
