// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Radio } from './Radio';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Radio: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13581-25220", title: "Components/Elastic UI/☠️ Radio [13581:25220]",
  component: Radio, tags: ['autodocs'],
  args: {"Label": "True", "Checked": "False", "State": "Default"},
  argTypes: {"Label": {"control": "inline-radio", "description": "Свойство Figma: Label", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Checked": {"control": "inline-radio", "description": "Свойство Figma: Checked", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Disabled", "Focus"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13581:25220", exportName: "Radio", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13581-25220) · 10 вариантов." } } },
} satisfies Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13581:25220" component={Radio} storyId="ds-13581-25220"/> };
/** Label: True · Checked: False · State: Default */
export const Variant001: Story = { name: "Label: True · Checked: False · State: Default", args: {"Label": "True", "Checked": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Label: False · Checked: False · State: Default */
export const Variant002: Story = { name: "Label: False · Checked: False · State: Default", args: {"Label": "False", "Checked": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Label: True · Checked: True · State: Default */
export const Variant003: Story = { name: "Label: True · Checked: True · State: Default", args: {"Label": "True", "Checked": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Label: False · Checked: True · State: Default */
export const Variant004: Story = { name: "Label: False · Checked: True · State: Default", args: {"Label": "False", "Checked": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Label: True · Checked: False · State: Focus */
export const Variant005: Story = { name: "Label: True · Checked: False · State: Focus", args: {"Label": "True", "Checked": "False", "State": "Focus"}, tags: ["!autodocs"] };
/** Label: False · Checked: False · State: Focus */
export const Variant006: Story = { name: "Label: False · Checked: False · State: Focus", args: {"Label": "False", "Checked": "False", "State": "Focus"}, tags: ["!autodocs"] };
/** Label: True · Checked: True · State: Disabled */
export const Variant007: Story = { name: "Label: True · Checked: True · State: Disabled", args: {"Label": "True", "Checked": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Label: False · Checked: True · State: Disabled */
export const Variant008: Story = { name: "Label: False · Checked: True · State: Disabled", args: {"Label": "False", "Checked": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Label: True · Checked: False · State: Disabled */
export const Variant009: Story = { name: "Label: True · Checked: False · State: Disabled", args: {"Label": "True", "Checked": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Label: False · Checked: False · State: Disabled */
export const Variant010: Story = { name: "Label: False · Checked: False · State: Disabled", args: {"Label": "False", "Checked": "False", "State": "Disabled"}, tags: ["!autodocs"] };
