// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { EmptyPrompt } from './EmptyPrompt';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** EmptyPrompt: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36674-394711", title: "Components/Elastic UI/Empty Prompt [36674:394711]",
  component: EmptyPrompt, tags: ['autodocs'],
  args: {"Show Footer#36674:0": false, "Color": "Transparent", "Layout": "Horizontal"},
  argTypes: {"Show Footer#36674:0": {"control": "boolean", "description": "Свойство Figma: Show Footer", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Color": {"control": "select", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Transparent"}}, "options": ["Transparent", "Plain", "Plain + Border", "Plain + Shadow", "Subdued", "Primary", "Success", "Warning", "Danger", "Accent"]}, "Layout": {"control": "inline-radio", "description": "Свойство Figma: Layout", "table": {"category": "Figma", "defaultValue": {"summary": "Horizontal"}}, "options": ["Vertical", "Horizontal"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36674:394711", exportName: "EmptyPrompt", docs: { description: { component: "Component has a min-width of 805px.  Additional actions can be added alongside or below the primary action\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36674-394711) · 20 вариантов." } } },
} satisfies Meta<typeof EmptyPrompt>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36674:394711" component={EmptyPrompt} storyId="ds-36674-394711"/> };
/** Color: Transparent · Layout: Horizontal */
export const Variant001: Story = { name: "Color: Transparent · Layout: Horizontal", args: {"Color": "Transparent", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Transparent · Layout: Vertical */
export const Variant002: Story = { name: "Color: Transparent · Layout: Vertical", args: {"Color": "Transparent", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Plain · Layout: Horizontal */
export const Variant003: Story = { name: "Color: Plain · Layout: Horizontal", args: {"Color": "Plain", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Plain · Layout: Vertical */
export const Variant004: Story = { name: "Color: Plain · Layout: Vertical", args: {"Color": "Plain", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Plain + Border · Layout: Horizontal */
export const Variant005: Story = { name: "Color: Plain + Border · Layout: Horizontal", args: {"Color": "Plain + Border", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Plain + Border · Layout: Vertical */
export const Variant006: Story = { name: "Color: Plain + Border · Layout: Vertical", args: {"Color": "Plain + Border", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Plain + Shadow · Layout: Horizontal */
export const Variant007: Story = { name: "Color: Plain + Shadow · Layout: Horizontal", args: {"Color": "Plain + Shadow", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Plain + Shadow · Layout: Vertical */
export const Variant008: Story = { name: "Color: Plain + Shadow · Layout: Vertical", args: {"Color": "Plain + Shadow", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Subdued · Layout: Horizontal */
export const Variant009: Story = { name: "Color: Subdued · Layout: Horizontal", args: {"Color": "Subdued", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Subdued · Layout: Vertical */
export const Variant010: Story = { name: "Color: Subdued · Layout: Vertical", args: {"Color": "Subdued", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Primary · Layout: Horizontal */
export const Variant011: Story = { name: "Color: Primary · Layout: Horizontal", args: {"Color": "Primary", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Primary · Layout: Vertical */
export const Variant012: Story = { name: "Color: Primary · Layout: Vertical", args: {"Color": "Primary", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Success · Layout: Horizontal */
export const Variant013: Story = { name: "Color: Success · Layout: Horizontal", args: {"Color": "Success", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Success · Layout: Vertical */
export const Variant014: Story = { name: "Color: Success · Layout: Vertical", args: {"Color": "Success", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Warning · Layout: Horizontal */
export const Variant015: Story = { name: "Color: Warning · Layout: Horizontal", args: {"Color": "Warning", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Warning · Layout: Vertical */
export const Variant016: Story = { name: "Color: Warning · Layout: Vertical", args: {"Color": "Warning", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Danger · Layout: Horizontal */
export const Variant017: Story = { name: "Color: Danger · Layout: Horizontal", args: {"Color": "Danger", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Danger · Layout: Vertical */
export const Variant018: Story = { name: "Color: Danger · Layout: Vertical", args: {"Color": "Danger", "Layout": "Vertical"}, tags: ["!autodocs"] };
/** Color: Accent · Layout: Horizontal */
export const Variant019: Story = { name: "Color: Accent · Layout: Horizontal", args: {"Color": "Accent", "Layout": "Horizontal"}, tags: ["!autodocs"] };
/** Color: Accent · Layout: Vertical */
export const Variant020: Story = { name: "Color: Accent · Layout: Vertical", args: {"Color": "Accent", "Layout": "Vertical"}, tags: ["!autodocs"] };
