// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { HeaderBreadcrumbs } from './HeaderBreadcrumbs';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** HeaderBreadcrumbs: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-9871-3787", title: "Components/Elastic UI/📦 Header Breadcrumbs [9871:3787]",
  component: HeaderBreadcrumbs, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "9871:3787", exportName: "HeaderBreadcrumbs", docs: { description: { component: "&lt;EuiHeaderBreadcrumbs&gt;\n\nThese breadcrumbs should only be used within the Header component.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=9871-3787) · 1 вариантов." } } },
} satisfies Meta<typeof HeaderBreadcrumbs>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="9871:3787" component={HeaderBreadcrumbs} storyId="ds-9871-3787"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
