// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ListGroup } from './ListGroup';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ListGroup: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15132-132472", title: "Components/Elastic UI/List Group [15132:132472]",
  component: ListGroup, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15132:132472", exportName: "ListGroup", docs: { description: { component: "&lt;EuiListGroup&gt;\n\nBorder and edge padding can be removed. \n\nGutter sizes available are: 0, 8, 16\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15132-132472) · 1 вариантов." } } },
} satisfies Meta<typeof ListGroup>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15132:132472" component={ListGroup} storyId="ds-15132-132472"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
