// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Chart } from './Chart';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Chart: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13648-4291", title: "Components/Elastic UI/☠️ Chart [13648:4291]",
  component: Chart, tags: ['autodocs'],
  args: {"Color": "True", "Size": "Medium (default)"},
  argTypes: {"Color": {"control": "inline-radio", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium (default)"}}, "options": ["Medium (default)", "Large", "X Large"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13648:4291", exportName: "Chart", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13648-4291) · 6 вариантов." } } },
} satisfies Meta<typeof Chart>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13648:4291" component={Chart} storyId="ds-13648-4291"/> };
/** Color: True · Size: Medium (default) */
export const Variant001: Story = { name: "Color: True · Size: Medium (default)", args: {"Color": "True", "Size": "Medium (default)"}, tags: ["!autodocs"] };
/** Color: True · Size: Large */
export const Variant002: Story = { name: "Color: True · Size: Large", args: {"Color": "True", "Size": "Large"}, tags: ["!autodocs"] };
/** Color: True · Size: X Large */
export const Variant003: Story = { name: "Color: True · Size: X Large", args: {"Color": "True", "Size": "X Large"}, tags: ["!autodocs"] };
/** Color: False · Size: Medium (default) */
export const Variant004: Story = { name: "Color: False · Size: Medium (default)", args: {"Color": "False", "Size": "Medium (default)"}, tags: ["!autodocs"] };
/** Color: False · Size: Large */
export const Variant005: Story = { name: "Color: False · Size: Large", args: {"Color": "False", "Size": "Large"}, tags: ["!autodocs"] };
/** Color: False · Size: X Large */
export const Variant006: Story = { name: "Color: False · Size: X Large", args: {"Color": "False", "Size": "X Large"}, tags: ["!autodocs"] };
