// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FilterButton } from './FilterButton';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FilterButton: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-39838-197", title: "Components/Elastic UI/.📦 Filter Button [39838:197]",
  component: FilterButton, tags: ['autodocs'],
  args: {"With next#39823:0": true, "Active": "true", "Count": "true", "Icon": "Left", "Disabled": "False", "Size": "Medium*"},
  argTypes: {"With next#39823:0": {"control": "boolean", "description": "Свойство Figma: With next", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Active": {"control": "inline-radio", "description": "Свойство Figma: Active", "table": {"category": "Figma", "defaultValue": {"summary": "true"}}, "options": ["False", "true"]}, "Count": {"control": "inline-radio", "description": "Свойство Figma: Count", "table": {"category": "Figma", "defaultValue": {"summary": "true"}}, "options": ["true", "false"]}, "Icon": {"control": "inline-radio", "description": "Свойство Figma: Icon", "table": {"category": "Figma", "defaultValue": {"summary": "Left"}}, "options": ["None", "Left", "Right"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium*"}}, "options": ["Medium*", "Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "39838:197", exportName: "FilterButton", docs: { description: { component: ".📦 Filter Button — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=39838-197) · 18 вариантов." } } },
} satisfies Meta<typeof FilterButton>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="39838:197" component={FilterButton} storyId="ds-39838-197"/> };
/** Active: true · Count: true · Icon: Left · Disabled: False · Size: Medium* */
export const Variant001: Story = { name: "Active: true · Count: true · Icon: Left · Disabled: False · Size: Medium*", args: {"Active": "true", "Count": "true", "Icon": "Left", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: true · Count: true · Icon: Right · Disabled: False · Size: Medium* */
export const Variant002: Story = { name: "Active: true · Count: true · Icon: Right · Disabled: False · Size: Medium*", args: {"Active": "true", "Count": "true", "Icon": "Right", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: true · Count: false · Icon: None · Disabled: False · Size: Medium* */
export const Variant003: Story = { name: "Active: true · Count: false · Icon: None · Disabled: False · Size: Medium*", args: {"Active": "true", "Count": "false", "Icon": "None", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: true · Count: true · Icon: Left · Disabled: False · Size: Small */
export const Variant004: Story = { name: "Active: true · Count: true · Icon: Left · Disabled: False · Size: Small", args: {"Active": "true", "Count": "true", "Icon": "Left", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: true · Count: true · Icon: Right · Disabled: False · Size: Small */
export const Variant005: Story = { name: "Active: true · Count: true · Icon: Right · Disabled: False · Size: Small", args: {"Active": "true", "Count": "true", "Icon": "Right", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: true · Count: false · Icon: None · Disabled: False · Size: Small */
export const Variant006: Story = { name: "Active: true · Count: false · Icon: None · Disabled: False · Size: Small", args: {"Active": "true", "Count": "false", "Icon": "None", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Left · Disabled: False · Size: Medium* */
export const Variant007: Story = { name: "Active: False · Count: true · Icon: Left · Disabled: False · Size: Medium*", args: {"Active": "False", "Count": "true", "Icon": "Left", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Right · Disabled: False · Size: Medium* */
export const Variant008: Story = { name: "Active: False · Count: true · Icon: Right · Disabled: False · Size: Medium*", args: {"Active": "False", "Count": "true", "Icon": "Right", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: false · Icon: None · Disabled: False · Size: Medium* */
export const Variant009: Story = { name: "Active: False · Count: false · Icon: None · Disabled: False · Size: Medium*", args: {"Active": "False", "Count": "false", "Icon": "None", "Disabled": "False", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Left · Disabled: False · Size: Small */
export const Variant010: Story = { name: "Active: False · Count: true · Icon: Left · Disabled: False · Size: Small", args: {"Active": "False", "Count": "true", "Icon": "Left", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Right · Disabled: False · Size: Small */
export const Variant011: Story = { name: "Active: False · Count: true · Icon: Right · Disabled: False · Size: Small", args: {"Active": "False", "Count": "true", "Icon": "Right", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: false · Icon: None · Disabled: False · Size: Small */
export const Variant012: Story = { name: "Active: False · Count: false · Icon: None · Disabled: False · Size: Small", args: {"Active": "False", "Count": "false", "Icon": "None", "Disabled": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Left · Disabled: True · Size: Medium* */
export const Variant013: Story = { name: "Active: False · Count: true · Icon: Left · Disabled: True · Size: Medium*", args: {"Active": "False", "Count": "true", "Icon": "Left", "Disabled": "True", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Right · Disabled: True · Size: Medium* */
export const Variant014: Story = { name: "Active: False · Count: true · Icon: Right · Disabled: True · Size: Medium*", args: {"Active": "False", "Count": "true", "Icon": "Right", "Disabled": "True", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: false · Icon: None · Disabled: True · Size: Medium* */
export const Variant015: Story = { name: "Active: False · Count: false · Icon: None · Disabled: True · Size: Medium*", args: {"Active": "False", "Count": "false", "Icon": "None", "Disabled": "True", "Size": "Medium*"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Left · Disabled: True · Size: Small */
export const Variant016: Story = { name: "Active: False · Count: true · Icon: Left · Disabled: True · Size: Small", args: {"Active": "False", "Count": "true", "Icon": "Left", "Disabled": "True", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: true · Icon: Right · Disabled: True · Size: Small */
export const Variant017: Story = { name: "Active: False · Count: true · Icon: Right · Disabled: True · Size: Small", args: {"Active": "False", "Count": "true", "Icon": "Right", "Disabled": "True", "Size": "Small"}, tags: ["!autodocs"] };
/** Active: False · Count: false · Icon: None · Disabled: True · Size: Small */
export const Variant018: Story = { name: "Active: False · Count: false · Icon: None · Disabled: True · Size: Small", args: {"Active": "False", "Count": "false", "Icon": "None", "Disabled": "True", "Size": "Small"}, tags: ["!autodocs"] };
