// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CodeLine } from './CodeLine';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** CodeLine: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-41028-3667", title: "Components/Elastic UI/.📦 Code line [41028:3667]",
  component: CodeLine, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "41028:3667", exportName: "CodeLine", docs: { description: { component: ".📦 Code line — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=41028-3667) · 1 вариантов." } } },
} satisfies Meta<typeof CodeLine>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="41028:3667" component={CodeLine} storyId="ds-41028-3667"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
