// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { TableCellHeader } from './TableCellHeader';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** TableCellHeader: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15035-3348", title: "Components/Elastic UI/📦 Table Cell -> Header [15035:3348]",
  component: TableCellHeader, tags: ['autodocs'],
  args: {"Sort": "None", "Compressed": "No", "Tooltip": "No"},
  argTypes: {"Sort": {"control": "inline-radio", "description": "Свойство Figma: Sort", "table": {"category": "Figma", "defaultValue": {"summary": "None"}}, "options": ["Ascending", "Descending", "None"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "No"}}, "options": ["No", "Yes"]}, "Tooltip": {"control": "inline-radio", "description": "Свойство Figma: Tooltip", "table": {"category": "Figma", "defaultValue": {"summary": "No"}}, "options": ["No", "Yes"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15035:3348", exportName: "TableCellHeader", docs: { description: { component: "📦 Table Cell -> Header — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15035-3348) · 12 вариантов." } } },
} satisfies Meta<typeof TableCellHeader>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15035:3348" component={TableCellHeader} storyId="ds-15035-3348"/> };
/** Sort: Ascending · Compressed: No · Tooltip: No */
export const Variant001: Story = { name: "Sort: Ascending · Compressed: No · Tooltip: No", args: {"Sort": "Ascending", "Compressed": "No", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: Ascending · Compressed: No · Tooltip: Yes */
export const Variant002: Story = { name: "Sort: Ascending · Compressed: No · Tooltip: Yes", args: {"Sort": "Ascending", "Compressed": "No", "Tooltip": "Yes"}, tags: ["!autodocs"] };
/** Sort: Ascending · Compressed: Yes · Tooltip: No */
export const Variant003: Story = { name: "Sort: Ascending · Compressed: Yes · Tooltip: No", args: {"Sort": "Ascending", "Compressed": "Yes", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: Ascending · Compressed: Yes · Tooltip: Yes */
export const Variant004: Story = { name: "Sort: Ascending · Compressed: Yes · Tooltip: Yes", args: {"Sort": "Ascending", "Compressed": "Yes", "Tooltip": "Yes"}, tags: ["!autodocs"] };
/** Sort: None · Compressed: No · Tooltip: No */
export const Variant005: Story = { name: "Sort: None · Compressed: No · Tooltip: No", args: {"Sort": "None", "Compressed": "No", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: None · Compressed: No · Tooltip: Yes */
export const Variant006: Story = { name: "Sort: None · Compressed: No · Tooltip: Yes", args: {"Sort": "None", "Compressed": "No", "Tooltip": "Yes"}, tags: ["!autodocs"] };
/** Sort: None · Compressed: Yes · Tooltip: No */
export const Variant007: Story = { name: "Sort: None · Compressed: Yes · Tooltip: No", args: {"Sort": "None", "Compressed": "Yes", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: None · Compressed: Yes · Tooltip: Yes */
export const Variant008: Story = { name: "Sort: None · Compressed: Yes · Tooltip: Yes", args: {"Sort": "None", "Compressed": "Yes", "Tooltip": "Yes"}, tags: ["!autodocs"] };
/** Sort: Descending · Compressed: No · Tooltip: No */
export const Variant009: Story = { name: "Sort: Descending · Compressed: No · Tooltip: No", args: {"Sort": "Descending", "Compressed": "No", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: Descending · Compressed: No · Tooltip: Yes */
export const Variant010: Story = { name: "Sort: Descending · Compressed: No · Tooltip: Yes", args: {"Sort": "Descending", "Compressed": "No", "Tooltip": "Yes"}, tags: ["!autodocs"] };
/** Sort: Descending · Compressed: Yes · Tooltip: No */
export const Variant011: Story = { name: "Sort: Descending · Compressed: Yes · Tooltip: No", args: {"Sort": "Descending", "Compressed": "Yes", "Tooltip": "No"}, tags: ["!autodocs"] };
/** Sort: Descending · Compressed: Yes · Tooltip: Yes */
export const Variant012: Story = { name: "Sort: Descending · Compressed: Yes · Tooltip: Yes", args: {"Sort": "Descending", "Compressed": "Yes", "Tooltip": "Yes"}, tags: ["!autodocs"] };
