// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SplitPanel } from './SplitPanel';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SplitPanel: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-32670-392917", title: "Components/Elastic UI/Split Panel [32670:392917]",
  component: SplitPanel, tags: ['autodocs'],
  args: {"Direction": "Vertical", "Border": "False", "Shadow": "True", "Border radius": "True"},
  argTypes: {"Direction": {"control": "inline-radio", "description": "Свойство Figma: Direction", "table": {"category": "Figma", "defaultValue": {"summary": "Vertical"}}, "options": ["Vertical", "Horizontal", "Direction3"]}, "Border": {"control": "inline-radio", "description": "Свойство Figma: Border", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Shadow": {"control": "inline-radio", "description": "Свойство Figma: Shadow", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Border radius": {"control": "inline-radio", "description": "Свойство Figma: Border radius", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "32670:392917", exportName: "SplitPanel", docs: { description: { component: "Split Panel — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=32670-392917) · 8 вариантов." } } },
} satisfies Meta<typeof SplitPanel>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="32670:392917" component={SplitPanel} storyId="ds-32670-392917"/> };
/** Direction: Vertical · Border: False · Shadow: True · Border radius: True */
export const Variant001: Story = { name: "Direction: Vertical · Border: False · Shadow: True · Border radius: True", args: {"Direction": "Vertical", "Border": "False", "Shadow": "True", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Direction3 · Border: True · Shadow: False · Border radius: True */
export const Variant002: Story = { name: "Direction: Direction3 · Border: True · Shadow: False · Border radius: True", args: {"Direction": "Direction3", "Border": "True", "Shadow": "False", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Direction3 · Border: False · Shadow: False · Border radius: True */
export const Variant003: Story = { name: "Direction: Direction3 · Border: False · Shadow: False · Border radius: True", args: {"Direction": "Direction3", "Border": "False", "Shadow": "False", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Direction3 · Border: False · Shadow: False · Border radius: False */
export const Variant004: Story = { name: "Direction: Direction3 · Border: False · Shadow: False · Border radius: False", args: {"Direction": "Direction3", "Border": "False", "Shadow": "False", "Border radius": "False"}, tags: ["!autodocs"] };
/** Direction: Horizontal · Border: False · Shadow: True · Border radius: True */
export const Variant005: Story = { name: "Direction: Horizontal · Border: False · Shadow: True · Border radius: True", args: {"Direction": "Horizontal", "Border": "False", "Shadow": "True", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Horizontal · Border: True · Shadow: False · Border radius: True */
export const Variant006: Story = { name: "Direction: Horizontal · Border: True · Shadow: False · Border radius: True", args: {"Direction": "Horizontal", "Border": "True", "Shadow": "False", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Horizontal · Border: False · Shadow: False · Border radius: True */
export const Variant007: Story = { name: "Direction: Horizontal · Border: False · Shadow: False · Border radius: True", args: {"Direction": "Horizontal", "Border": "False", "Shadow": "False", "Border radius": "True"}, tags: ["!autodocs"] };
/** Direction: Horizontal · Border: False · Shadow: False · Border radius: False */
export const Variant008: Story = { name: "Direction: Horizontal · Border: False · Shadow: False · Border radius: False", args: {"Direction": "Horizontal", "Border": "False", "Shadow": "False", "Border radius": "False"}, tags: ["!autodocs"] };
