// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ParticipantsTable } from './ParticipantsTable';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ParticipantsTable: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-153-1605", title: "Components/UX-Lab/ParticipantsTable [153:1605]",
  component: ParticipantsTable, tags: ['autodocs'],
  args: {"State": "Ready"},
  argTypes: {"State": {"control": "select", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Ready"}}, "options": ["Ready", "Loading", "Empty", "FilteredEmpty", "Error"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "rows": {"control": "object", "description": "Данные / обработчик компонента", "table": {"category": "React"}}, "onOpenRecording": {"control": false, "description": "Данные / обработчик компонента", "table": {"category": "React"}, "action": "onOpenRecording"}},
  parameters: { layout: "padded", catalogId: "153:1605", exportName: "ParticipantsTable", docs: { description: { component: "ParticipantsTable — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=153-1605) · 5 вариантов." } } },
} satisfies Meta<typeof ParticipantsTable>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="153:1605" component={ParticipantsTable} storyId="ds-153-1605"/> };
/** State: Ready */
export const Variant001: Story = { name: "State: Ready", args: {"State": "Ready"}, tags: ["!autodocs"] };
/** State: Loading */
export const Variant002: Story = { name: "State: Loading", args: {"State": "Loading"}, tags: ["!autodocs"] };
/** State: Empty */
export const Variant003: Story = { name: "State: Empty", args: {"State": "Empty"}, tags: ["!autodocs"] };
/** State: FilteredEmpty */
export const Variant004: Story = { name: "State: FilteredEmpty", args: {"State": "FilteredEmpty"}, tags: ["!autodocs"] };
/** State: Error */
export const Variant005: Story = { name: "State: Error", args: {"State": "Error"}, tags: ["!autodocs"] };
