import { chromium,expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const api=process.env.LIVE_TEST_API;
if(!api)throw Error('Only run with an isolated test API');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[];
await context.route('http://127.0.0.1:5174/**',async route=>{
  const response=await route.fetch({url:route.request().url().replace('http://127.0.0.1:5174',api)});
  await route.fulfill({response});
});
const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
const open=async screen=>{await page.goto(`http://127.0.0.1:5173/#/${screen}`);await expect(page.locator('[data-live-project]')).toBeVisible();await expect(page.getByText('Загружаем исследование…',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Обновить',exact:true})).toHaveCount(0);if(screen==='report'||screen==='studies')await expect(page.getByRole('button',{name:screen==='report'?'Создать отчёт':'Создать исследование',exact:true})).toBeVisible();};
try {
  await fs.mkdir('.tmp/live-project',{recursive:true});
  await open('projects');await expect(page.getByRole('table')).toHaveCount(1);
  await expect(page.getByRole('row')).toHaveCount(2);
  await expect(page.getByText('Интернет-магазин',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Lead Generation',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Исследования проекта',exact:true})).toBeVisible();
  await open('overview');await expect(page.getByRole('table',{name:'Экраны проекта'})).toBeVisible();
  await open('participants');await expect(page.getByRole('table',{name:'Сессии Lead Generation'})).toBeVisible();
  await page.getByRole('button',{name:'session-',exact:true}).click();
  await expect(page.getByRole('heading',{name:'История сессии',exact:true})).toBeVisible();
  await page.getByText('Снимки и события · 4',{exact:true}).click();
  await expect(page.getByRole('button',{name:'Следующее',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Сохранить наблюдение',exact:true}).click();
  await page.getByLabel('Название',{exact:true}).fill('Проверка наблюдения');
  await page.getByLabel('Что наблюдали',{exact:true}).fill('Повторные клики по области');
  await page.getByRole('button',{name:'Сохранить',exact:true}).click();
  await open('findings');await expect(page.getByRole('heading',{name:'Проверка наблюдения'})).toBeVisible();
  await page.getByRole('tab',{name:'Сигналы',exact:true}).click();
  await expect(page.getByRole('table',{name:'Сигналы',exact:true})).toBeVisible();
  const view=page.getByRole('group',{name:'Представление сигналов'});
  await expect(view.getByRole('button',{name:'Отдельные события',exact:true})).toHaveAttribute('aria-pressed','true');
  await view.getByRole('button',{name:'По страницам',exact:true}).click();
  await expect(page.getByRole('table',{name:'Сигналы по страницам',exact:true})).toBeVisible();
  await expect(view.getByRole('button',{name:'По страницам',exact:true})).toHaveAttribute('aria-pressed','true');
  await view.getByRole('button',{name:'Отдельные события',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByRole('table',{name:'Сигналы',exact:true})).toBeVisible();
  await page.screenshot({path:'.tmp/live-project/signals-switch.png',fullPage:true});
  await open('setup');
  await expect(page.getByRole('heading',{name:'Параметры исследования',exact:true})).toBeVisible();
  const saveParameters=page.getByRole('button',{name:'Сохранить параметры',exact:true});
  await expect(saveParameters).toBeDisabled();
  await page.getByLabel('Собирать клики',{exact:true}).uncheck();
  await saveParameters.click();
  await expect(page.getByText('Параметры сохранены',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Собирать клики',{exact:true})).not.toBeChecked();
  await page.getByLabel('Собирать клики',{exact:true}).check();
  await saveParameters.click();
  await expect(saveParameters).toBeDisabled();
  await expect(page.getByRole('button',{name:'Проверить подключение',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Приостановить сбор',exact:true})).toHaveCount(0);
  await page.getByLabel('Название исследования',{exact:true}).fill('Проверка разделения экранов');
  await page.getByRole('button',{name:'Сохранить название',exact:true}).click();
  await expect(page.getByText('Название сохранено',{exact:true})).toBeVisible();
  assert.equal((await(await fetch(api+'/api/project/config')).json()).studyTitle,'Проверка разделения экранов');
  await page.getByLabel('Название исследования',{exact:true}).fill('   ');
  await expect(page.getByRole('button',{name:'Сохранить название',exact:true})).toBeDisabled();
  await page.screenshot({path:'.tmp/live-project/setup.png',fullPage:true});
  await page.getByRole('link',{name:'К проверке и запуску',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Проверка и запуск',exact:true})).toBeVisible();
  await expect(page.getByLabel('Название исследования',{exact:true})).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'Инструкция для участника',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Проверить подключение',exact:true}).click();
  await expect(page.getByText('Сервер сбора доступен',{exact:true})).toBeVisible();
  await page.route('**/api/project/config',route=>route.fulfill({status:503,json:{error:'Isolated connection failure'}}));
  await page.getByRole('button',{name:'Проверить подключение',exact:true}).click();
  await expect(page.getByText('Сервер сбора доступен',{exact:true})).toHaveCount(0);
  await expect(page.getByText('Нет связи с локальным сервером. Данные сохранены; повторите попытку.',{exact:true})).toBeVisible();
  await page.unroute('**/api/project/config');
  await page.getByRole('switch',{name:'Сбор данных',exact:true}).click();
  await expect(page.getByRole('switch',{name:'Сбор данных',exact:true})).not.toBeChecked();
  assert.equal((await(await fetch(api+'/api/project/config')).json()).enabled,false);
  await page.getByRole('switch',{name:'Сбор данных',exact:true}).click();
  await expect(page.getByRole('switch',{name:'Сбор данных',exact:true})).toBeChecked();
  await page.screenshot({path:'.tmp/live-project/launch.png',fullPage:true});
  await open('report');await page.getByRole('button',{name:'Создать отчёт',exact:true}).click();await page.getByRole('button',{name:'Сформировать PDF',exact:true}).click();
  await expect(page.getByRole('button',{name:'Скачать PDF',exact:true})).toBeVisible();
  await fs.mkdir('.tmp/live-project',{recursive:true});
  const reportDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать PDF',exact:true}).click();await(await reportDownload).saveAs('.tmp/live-project/report.pdf');
  await open('overview');await page.screenshot({path:'.tmp/live-project/overview.png',fullPage:true});
  // Verify actual target visits and pause/resume, with all writes redirected to the isolated database.
  const target=await context.newPage();target.on('pageerror',error=>errors.push(error.message));
  await target.goto('http://127.0.0.1:5175/leads-table?ux_study=leed-local');
  await expect.poll(async()=>(await(await fetch(api+'/api/project')).json()).total.visits,{timeout:15000}).toBeGreaterThan(1);
  await fetch(api+'/api/project/config',{method:'POST',body:JSON.stringify({enabled:false})});
  await target.waitForTimeout(4000);
  const before=(await(await fetch(api+'/api/project')).json()).total.clicks;
  await target.mouse.click(600,900);await target.waitForTimeout(1600);
  assert.equal((await(await fetch(api+'/api/project')).json()).total.clicks,before,'paused clicks excluded');
  await fetch(api+'/api/project/config',{method:'POST',body:JSON.stringify({enabled:true})});
  await target.waitForTimeout(3500);await target.mouse.click(600,900);
  await expect.poll(async()=>(await(await fetch(api+'/api/project')).json()).total.clicks).toBeGreaterThan(before);
  // Settings reach already-open tabs and survive a target reload.
  const configure=async config=>{await fetch(api+'/api/project/config',{method:'POST',body:JSON.stringify(config)});await target.waitForTimeout(2500);};
  await configure({collectClicks:false,collectVisits:false,allowVideo:false});
  await expect(target.getByRole('button',{name:'Начать запись теста',exact:true})).toBeDisabled();
  const counts=(await(await fetch(api+'/api/project')).json()).total;
  await target.mouse.click(600,900);
  await target.reload();
  await target.waitForTimeout(2500);
  await target.mouse.click(600,900);await target.waitForTimeout(1600);
  const disabledCounts=(await(await fetch(api+'/api/project')).json()).total;
  assert.equal(disabledCounts.clicks,counts.clicks);
  assert.equal(disabledCounts.visits,counts.visits);
  await configure({collectClicks:true});
  await target.mouse.click(600,900);
  await expect.poll(async()=>(await(await fetch(api+'/api/project')).json()).total.clicks).toBeGreaterThan(counts.clicks);
  assert.equal((await(await fetch(api+'/api/project')).json()).total.visits,counts.visits);
  await configure({collectVisits:true,allowVideo:true});
  await expect.poll(async()=>(await(await fetch(api+'/api/project')).json()).total.visits).toBeGreaterThan(counts.visits);
  await expect(target.getByRole('button',{name:'Начать запись теста',exact:true})).toBeEnabled();
  assert.deepEqual(errors,[]);
  console.log('PASS live project navigation, sessions, findings, report PDF, visits, pause and resume');
}finally{await browser.close();}
