import { chromium, expect } from '@playwright/test';
import { mkdir,readFile } from 'node:fs/promises';
const folder='.tmp/heatmap/exports';await mkdir(folder,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1680,height:1050},acceptDownloads:true});
  await page.goto('http://127.0.0.1:5173/?screen=results-overview#/heatmap-live?link=leed-local');
  const refresh=page.getByRole('button',{name:'Обновить',exact:true});
  await refresh.hover();
  await expect(refresh).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
  if(await refresh.evaluate(el=>getComputedStyle(el,'::before').display)!=='none')throw Error('EUI hover overlay is still visible');
  const transition=await refresh.evaluate(el=>getComputedStyle(el).transitionDuration);
  if(!transition.includes('0.15s'))throw Error('Product hover transition is missing');
  const select=page.getByRole('button',{name:'Экран',exact:true});await select.click();
  const menu=page.getByRole('menu',{name:'Экран'});
  const item=menu.getByRole('menuitemradio').nth(1);await item.hover();
  await expect(item).toHaveCSS('text-decoration-line','none');
  await expect(item).toHaveCSS('background-color','rgb(236, 238, 220)');
  const buttonBox=await select.boundingBox();
  const panelBox=await menu.locator('..').boundingBox();
  if(Math.abs(buttonBox.width-panelBox.width)>12)throw Error(`Menu width differs: ${buttonBox.width}/${panelBox.width}`);
  await page.screenshot({path:folder+'/dropdown.png'});
  await page.keyboard.press('Escape');
  const map=page.getByTestId('captured-heatmap');await map.waitFor();
  const card=page.getByRole('heading',{name:'Вся страница',exact:true}).locator('..');
  const mapBox=await map.boundingBox(),cardBox=await card.boundingBox();
  if(Math.abs(mapBox.y-cardBox.y)>2)throw Error(`Map/card misaligned: ${mapBox.y}/${cardBox.y}`);
  const downloadPromise=page.waitForEvent('download',{timeout:195000});
  await page.getByRole('button',{name:'Скачать',exact:true}).click();
  const download=await downloadPromise;
  await download.saveAs(folder+'/single.png');
  const png=await readFile(folder+'/single.png');
  if(png.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error('Invalid PNG');
  const allPromise=page.waitForEvent('download',{timeout:195000});
  await page.getByRole('button',{name:'Варианты скачивания',exact:true}).click();
  await page.getByRole('menuitem',{name:'Все экраны ZIP',exact:true}).click();
  const all=await allPromise;await all.saveAs(folder+'/all.zip');
  await page.screenshot({path:folder+'/screen.png',fullPage:true});
  console.log(JSON.stringify({hover:'green',dropdown:'full-width without underline',aligned:true,png:[png.readUInt32BE(16),png.readUInt32BE(20)],zip:all.suggestedFilename()}));
}finally{await browser.close();}
