import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const api=process.env.LIVE_TEST_API;if(!api)throw Error('Isolated database required');
const browser=await chromium.launch({channel:'chrome',headless:true});
const get=async path=>(await fetch(api+path)).json();
const configure=async value=>{const response=await fetch(api+'/api/project/config',{method:'POST',body:JSON.stringify(value)});assert.equal(response.status,200);};
try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[];let offline=false;
  await context.route('http://127.0.0.1:5174/**',async route=>{
    if(offline&&route.request().method()==='POST')return route.fulfill({status:503,json:{error:'Simulated outage'}});
    await route.fulfill({response:await route.fetch({url:route.request().url().replace('http://127.0.0.1:5174',api)})});
  });
  const dashboard=await context.newPage();dashboard.on('pageerror',e=>errors.push(e.message));
  await dashboard.goto('http://127.0.0.1:5173/#/setup');
  await dashboard.getByRole('button',{name:'Формат записи',exact:true}).click();
  await dashboard.getByRole('menuitemradio',{name:'Скриншоты действий',exact:true}).click();
  await dashboard.getByLabel('Собирать клики',{exact:true}).uncheck();
  await dashboard.getByLabel('Собирать посещения экранов',{exact:true}).uncheck();
  await dashboard.getByRole('button',{name:'Сохранить параметры',exact:true}).click();
  await expect(dashboard.getByText('Параметры сохранены',{exact:true})).toBeVisible();
  await dashboard.reload();
  await expect(dashboard.getByRole('button',{name:'Формат записи',exact:true})).toContainText('Скриншоты действий');
  await fs.mkdir('.tmp/screenshot-replay',{recursive:true});await dashboard.screenshot({path:'.tmp/screenshot-replay/settings.png',fullPage:true});
  const target=await context.newPage();target.on('pageerror',e=>errors.push(e.message));
  await target.addInitScript(()=>{window.__captureCalls=0;Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:()=>{window.__captureCalls++;throw Error('Must not request screen capture');}});});
  await target.goto('http://127.0.0.1:5175/leads-table?ux_study=leed-local');
  await target.waitForFunction(()=>Boolean(window.__uxLabStatus?.session));
  await expect(target.getByText('Действия и снимки интерфейса сохраняются автоматически. Значения полей скрыты.',{exact:true})).toHaveCount(0);
  await expect(target.getByRole('button',{name:'Начать запись теста',exact:true})).toHaveCount(0);
  const session=await target.evaluate(()=>window.__uxLabStatus.session);
  const frames=async()=>(await get(`/api/project/frames?session=${session}`)).frames;
  await expect.poll(async()=>(await frames()).length).toBeGreaterThan(0);
  await target.getByRole('button',{name:'Канал: Все',exact:true}).click();
  await expect(target.getByRole('button',{name:'Форма',exact:true})).toBeVisible();
  await expect.poll(async()=>(await frames()).filter(f=>f.kind==='click'&&f.label.includes('Канал')).length).toBe(1);
  const click=(await frames()).find(f=>f.kind==='click'&&f.label.includes('Канал'));
  await expect.poll(async()=>(await frames()).filter(f=>f.kind==='change'&&f.seq>click.seq).length).toBeGreaterThan(0);
  const list=await frames();
  assert.ok(click.target.rect[2]>0);
  const after=list.find(f=>f.seq>click.seq&&f.kind==='change');
  await expect.poll(async()=>(await fetch(api+`/api/heatmap/snapshots?id=${after.snapshot}`)).status).toBe(200);
  const afterImage=await get(`/api/heatmap/snapshots?id=${after.snapshot}`);
  assert.match(afterImage.html,/>Форма<\/button>/,'Expanded dropdown is captured after the click');
  await target.getByRole('button',{name:'Канал: Все',exact:true}).click();
  const search=target.getByRole('textbox',{name:'Найти лида',exact:true});
  await search.fill('PRIVATE-REPLAY-TEST');await search.blur();
  await target.waitForTimeout(600);await target.mouse.click(700,900);
  await target.waitForTimeout(900);
  for(const frame of await frames()){
    const response=await fetch(api+`/api/heatmap/snapshots?id=${frame.snapshot}`);
    if(response.ok)assert.ok(!(await response.json()).html.includes('PRIVATE-REPLAY-TEST'));
  }
  await search.fill('');await search.blur();
  await target.getByRole('button',{name:'Генератор лидов',exact:true}).hover();
  await target.getByRole('button',{name:'Канбан',exact:true}).click();
  await expect.poll(async()=>(await frames()).filter(f=>f.kind==='screen'&&f.page==='leed-leads-kanban').length).toBeGreaterThan(0);
  const beforeOffline=(await frames()).length;offline=true;
  await target.getByRole('button',{name:'Генератор лидов',exact:true}).hover();
  await target.getByRole('button',{name:'Лиды',exact:true}).click();await target.waitForTimeout(800);
  await target.reload();await target.waitForTimeout(800);offline=false;
  await expect.poll(async()=>(await frames()).length,{timeout:15000}).toBeGreaterThan(beforeOffline);
  await target.waitForTimeout(1500);
  const all=await frames();assert.equal(new Set(all.map(f=>f.seq)).size,all.length);
  const summary=await get('/api/project');assert.equal(summary.total.clicks,0);assert.equal(summary.total.visits,0);assert.ok(summary.sessions.find(s=>s.id===session).frames>0);
  await configure({enabled:false});await target.waitForTimeout(2500);
  const paused=(await frames()).length;await target.mouse.click(700,900);await target.waitForTimeout(1500);assert.equal((await frames()).length,paused);
  await dashboard.goto(`http://127.0.0.1:5173/#/participant?participant=${session}`);
  await expect(dashboard.getByRole('heading',{name:'Скриншоты действий',exact:true})).toBeVisible();
  const slider=dashboard.getByRole('slider',{name:'Временная шкала снимков'});
  await slider.fill(String(all.findIndex(f=>f.id===click.id)));
  await expect(dashboard.getByTestId('heatmap-element-highlight').locator('rect')).toBeVisible();
  await dashboard.screenshot({path:'.tmp/screenshot-replay/click.png',fullPage:true});
  await slider.fill(String(all.findIndex(f=>f.id===after.id)));
  await expect(dashboard.frameLocator('iframe[title="Сохранённый фон Lead Generation"]').getByRole('button',{name:'Форма',exact:true})).toBeVisible();
  await expect(dashboard.getByTestId('heatmap-element-highlight')).toHaveCount(0);
  await dashboard.screenshot({path:'.tmp/screenshot-replay/filter.png',fullPage:true});
  await slider.fill('0');await dashboard.getByRole('button',{name:'Воспроизвести снимки',exact:true}).click();
  await expect.poll(()=>slider.inputValue()).not.toBe('0');await dashboard.getByRole('button',{name:'Пауза',exact:true}).click();
  await configure({recordingMode:'video',enabled:true});await target.waitForTimeout(3000);
  await expect(target.getByRole('button',{name:'Начать запись теста',exact:true})).toBeEnabled();
  const stopped=(await frames()).length;await target.mouse.click(700,900);await target.waitForTimeout(1500);assert.equal((await frames()).length,stopped);
  await dashboard.reload();await expect(dashboard.getByRole('heading',{name:'Скриншоты действий',exact:true})).toBeVisible();
  assert.equal(await target.evaluate(()=>window.__captureCalls),0);assert.deepEqual(errors,[]);
  console.log('PASS screenshot settings, after-action state, target highlight, masked values, navigation, offline/reload recovery, pause, playback, video switch and no capture permission');
}finally{await browser.close();}
