import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const study=process.env.HEATMAP_STUDY||`leed-verify-${Date.now()}`;
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900}});
const page=await context.newPage(),errors=[],batches=[],requests=[];
context.on('request',request=>{requests.push(request.url());if(request.url().endsWith('/api/heatmap/events'))batches.push(JSON.parse(request.postData()||'{}'));});
page.on('pageerror',error=>errors.push(error.message));
async function poll(fn) {for(let i=0;i<60;i++){const value=await fn();if(value)return value;await page.waitForTimeout(250)}throw Error('Timed out');}
const api=async(group='',mode='all')=>(await (await fetch(`http://127.0.0.1:5174/api/heatmap?${new URLSearchParams({study,group,mode})}`)).json());
const screenApi=async()=>await(await fetch(`http://127.0.0.1:5174/api/heatmap?study=${study}&aggregation=page`)).json();
try {
  await page.goto(`http://127.0.0.1:5175/leads-table?ux_study=${study}`);
  await page.waitForFunction(()=>!!window.__uxLabStatus);
  await page.waitForTimeout(1600);
  // Background clicks avoid changing UI state; repeated points must aggregate.
  await page.mouse.click(600,880);await page.mouse.click(600,880);
  await poll(async()=> (await api()).total.clicks===2);
  const initial=await api();assert.equal(initial.groups.length,1);
  const firstGroup=initial.groups[0];
  assert.equal(firstGroup.page,'leed-leads-table');
  const detail=await api(firstGroup.layout);
  assert.equal(detail.points[0].count,2);
  assert.ok(Math.abs(detail.points[0].x-600/1440)<.001);
  assert.ok(Math.abs(detail.points[0].y-880/900)<.001);
  assert.equal((await api(firstGroup.layout,'first')).points[0].count,1);
  const map=await context.newPage();
  // The product always uses leed-local. Redirect only this test page's read requests.
  await map.route('**/api/heatmap?*',async route=>{const url=new URL(route.request().url());url.searchParams.set('study',study);await route.fulfill({response:await route.fetch({url:url.href})});});
  await map.goto(`http://127.0.0.1:5173/?screen=results-overview#/heatmap-live?link=${study}`);
  await map.locator('iframe[title="Сохранённый фон Lead Generation"]').waitFor();
  const frame=map.frameLocator('iframe[title="Сохранённый фон Lead Generation"]');
  const visiblePoints=()=>map.getByTestId('captured-click-layer').evaluate(canvas=>[...canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data].some((v,i)=>i%4===3&&v>0));
  await poll(visiblePoints);
  const rect=el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};
  const originalRect=await page.getByRole('button',{name:'Новый лид',exact:true}).evaluate(rect);
  const savedRect=await frame.getByRole('button',{name:'Новый лид',exact:true}).evaluate(rect);
  for(const key of ['x','y','width','height'])assert.ok(Math.abs(originalRect[key]-savedRect[key])<2,`captured geometry: ${key}`);
  assert.equal((await api()).total.clicks,2,'preview must not collect clicks');
  await fs.mkdir('.tmp/heatmap',{recursive:true});
  await map.screenshot({path:'.tmp/heatmap/leed-live-map.png',fullPage:true});
  await page.goto(`http://127.0.0.1:5175/dashboard`);
  await page.waitForTimeout(1400);await page.mouse.click(600,880);
  await poll(async()=> (await api()).groups.some(g=>g.page==='leed-dashboard'));
  // Collector session and study survive full reload and SPA routes.
  assert.equal((await api()).total.sessions,1);
  await page.setViewportSize({width:1440,height:500});
  const scrollTop=await page.evaluate(()=>{const el=[...document.querySelectorAll('*')].find(e=>e.scrollHeight>e.clientHeight+100&&getComputedStyle(e).overflowY==='auto');if(!el)return 0;el.scrollTop=300;return el.scrollTop;});
  assert.ok(scrollTop>0,'test page must have a nested scroll container');
  await page.waitForTimeout(300);
  await page.mouse.click(1200,450);
  const scrolled=await poll(async()=> (await api()).groups.find(g=>g.page==='leed-dashboard'&&g.context.scrolls.length));
  assert.ok(scrolled);
  await map.getByRole('button',{name:'Экран',exact:true}).click();
  await map.getByRole('menuitemradio',{name:/Дашборд/}).click();
  await map.getByRole('button',{name:'Размер окна',exact:true}).click();
  await map.getByRole('menuitemradio',{name:/1440 × 500/}).click();
  await poll(visiblePoints);
  await frame.locator('[data-ux-scroll]').first().waitFor();
  await poll(async()=>frame.locator('[data-ux-scroll]').evaluateAll(nodes=>nodes.some(el=>el.scrollTop>0)));
  await page.setViewportSize({width:1440,height:900});
  await page.goto('http://127.0.0.1:5175/leads-table');await page.waitForTimeout(1400);
  const input=page.getByPlaceholder('Найти лида');
  await input.fill('PRIVATE-input-8675309');await input.click();
  await poll(async()=> (await api()).total.clicks>=5);
  const changed=(await api()).groups.find(g=>g.page==='leed-leads-table'&&g.layout!==firstGroup.layout);
  assert.ok(changed,'filtered state stored separately');
  await map.getByRole('button',{name:'Экран',exact:true}).click();
  await map.getByRole('menuitemradio',{name:/Таблица лидов/}).click();
  await poll(visiblePoints);
  assert.equal(await frame.getByPlaceholder('Найти лида').inputValue(),'');
  assert.equal((await screenApi()).groups.filter(g=>g.page==='leed-leads-table').length,1,'filter changes must not create another screen');
  assert.ok(changed.context.snapshot,'changed state has a captured background');
  const snapshot=await(await fetch(`http://127.0.0.1:5174/api/heatmap/snapshots?id=${changed.context.snapshot}`)).json();
  assert.ok(!snapshot.html.includes('PRIVATE-input-8675309'),'background excludes input values too');
  await input.fill('');
  await page.getByRole('button',{name:'Новый лид',exact:true}).click();
  await page.getByPlaceholder('Например: Иванов Пётр').fill('PRIVATE-MODAL-NAME');
  await page.getByPlaceholder('+7 900 000-00-00').click();
  const modalGroup=await poll(async()=>{
    const d=await api();
    for(const g of d.groups){if(!g.context?.snapshot)continue;const b=await(await fetch(`http://127.0.0.1:5174/api/heatmap/snapshots?id=${g.context.snapshot}`)).json();if(b.html?.includes('Например: Иванов Пётр'))return g;}
  });
  await poll(visiblePoints);
  const modalSnapshot=await(await fetch(`http://127.0.0.1:5174/api/heatmap/snapshots?id=${modalGroup.context.snapshot}`)).json();
  assert.ok(!modalSnapshot.html.includes('PRIVATE-MODAL-NAME'));
  const combined=(await screenApi()).groups.filter(g=>g.page==='leed-leads-table');
  assert.equal(combined.length,1,'modal clicks belong to the same screen');
  assert.equal(combined[0].clicks,5);
  await map.waitForFunction(()=>document.querySelector('[data-testid="real-click-count"]')?.textContent?.startsWith('5 кликов'));
  await map.getByTestId('captured-heatmap').screenshot({path:'.tmp/heatmap/leed-combined-map.png'});
  assert.ok(!JSON.stringify(batches).includes('PRIVATE-input-8675309'));
  assert.ok(!requests.some(url=>url.includes('45.139.76.34')),'old external tracker disconnected');
  assert.equal(errors.length,0,errors.join('\n'));
  const report={study,total:(await api()).total,checks:['coordinates','aggregation','first click','captured background overlay','preview is not tracked','route isolation','session persistence','nested scroll restoration','filter and modal clicks combined on one screen','no input values in events or snapshots','no old external endpoint','no browser errors']};
  await fs.writeFile('.tmp/heatmap/leed-audit.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
}finally {await browser.close();}
