import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const api=process.env.LIVE_TEST_API;if(!api)throw Error('Isolated API required');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
await context.route('http://127.0.0.1:5174/**',async r=>{const response=await r.fetch({url:r.request().url().replace('http://127.0.0.1:5174',api)});await r.fulfill({response});});
const get=async path=>(await fetch(api+path)).json();
const post=async(path,data)=>{const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});assert.ok(r.ok,await r.clone().text());return r.json();};
try{
 const config=await post('/api/project/studies',{studyTitle:'Свои критерии',scenario:'Запишитесь на консультацию.'}),id=config.studyId;
 await post('/api/project/config?study='+id,{enabled:true,recordingMode:'screenshots'});
 const dash=await context.newPage();await dash.goto('http://127.0.0.1:5173/#/setup?study='+id);
 await dash.getByLabel('Что считать успехом',{exact:true}).fill('Запись на консультацию подтверждена');
 await expect(dash.getByRole('button',{name:'Как проверять результат',exact:true})).toContainText('Вручную');
 await dash.getByRole('button',{name:'Сохранить сценарий'}).click();await expect(dash.getByText('Сценарий сохранён',{exact:true})).toBeVisible();
 const manual=(await get('/api/project/config?study='+id)).tasks[0];assert.equal(manual.verification.method,'manual');
 await dash.getByLabel('Что считать успехом',{exact:true}).scrollIntoViewIfNeeded();await dash.screenshot({path:'.tmp/custom-success-manual.png'});
 const participant=await context.newPage();await participant.goto(config.url);await expect(participant.getByRole('button',{name:'Завершить задание'})).toBeVisible();
 const sid=await participant.evaluate(()=>window.__uxLabStatus.session);
 await participant.getByRole('button',{name:'Завершить задание'}).click();await expect(participant.getByRole('dialog')).toContainText('Попытка завершена');
 await dash.getByRole('button',{name:'Сессии',exact:true}).click();await dash.getByRole('button',{name:sid.slice(0,8),exact:true}).click();
 const table=dash.getByRole('table',{name:'Задания сессии'});await expect(table).toContainText('Ожидает оценки');
 await table.getByRole('button',{name:'Оценка исследователя'}).click();await dash.getByRole('menuitemradio',{name:'Выполнено',exact:true}).click();
 await expect(table.getByText('Выполнено',{exact:true}).first()).toBeVisible();
 await expect.poll(async()=> (await get('/api/project?study='+id)).sessions.find(s=>s.id===sid).task.status).toBe('succeeded');
 await table.scrollIntoViewIfNeeded();await dash.screenshot({path:'.tmp/custom-success-review.png'});
 await dash.getByRole('button',{name:'Настройка исследования',exact:true}).click();
 await dash.getByRole('button',{name:'Как проверять результат',exact:true}).click();await dash.getByRole('menuitemradio',{name:'Автоматически',exact:true}).click();
 await dash.getByLabel('Или укажите имя своего события',{exact:true}).fill('booking_confirmed');
 await expect(dash.getByRole('button',{name:'Сохранить сценарий'})).toBeDisabled();
 await participant.evaluate(()=>window.dispatchEvent(new CustomEvent('ux-success-signal',{detail:{kind:'prototype_event',value:'booking_confirmed'}})));
 await expect(dash.getByText('Событие получено от этого прототипа. Условие можно сохранить.',{exact:true})).toBeVisible({timeout:15000});
 await dash.getByRole('button',{name:'Сохранить сценарий'}).click();await expect(dash.getByText('Сценарий сохранён',{exact:true})).toBeVisible();
 await dash.getByLabel('Или укажите имя своего события',{exact:true}).scrollIntoViewIfNeeded();await dash.screenshot({path:'.tmp/custom-success-automatic.png'});
 const auto=await context.newPage();await auto.goto(config.url);await expect(auto.getByRole('button',{name:'Завершить задание'})).toBeVisible();const aid=await auto.evaluate(()=>window.__uxLabStatus.session);
 const run=async()=> (await get('/api/project?study='+id)).sessions.find(s=>s.id===aid)?.task;
 assert.equal((await run()).status,'pending');
 await auto.evaluate(()=>window.dispatchEvent(new CustomEvent('ux-success-signal',{detail:{kind:'prototype_event',value:'booking_confirmed'}})));
 await expect.poll(async()=> (await run())?.status).toBe('succeeded');
 await auto.getByRole('button',{name:'Завершить задание'}).click();await expect(auto.getByRole('dialog')).toContainText('Попытка завершена');
 assert.equal((await get('/api/project?study='+id)).sessions.find(s=>s.id===sid).task.verification.method,'manual');
 await dash.reload();await expect(dash.getByLabel('Что считать успехом',{exact:true})).toHaveValue('Запись на консультацию подтверждена');
 await expect(dash.getByLabel('Или укажите имя своего события',{exact:true})).toHaveValue('booking_confirmed');
 assert.deepEqual(errors,[]);console.log('PASS custom description, manual assessment, persisted result, unknown event blocked, real prototype event connection and success, historical conditions preserved, reload.');
}finally{await browser.close();}
