import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const study=process.env.HEATMAP_STUDY||`verify-${Date.now()}`,api='http://127.0.0.1:5174';
const root='http://127.0.0.1:5173';const errors=[],batches=[];
const read=async(group='',mode='all')=>{const response=await fetch(`${api}/api/heatmap?${new URLSearchParams({study,group,mode})}`);if(!response.ok)throw Error(await response.text());return response.json();};
await mkdir('.tmp/heatmap',{recursive:true});
try {
  const context=await browser.newContext({viewport:{width:1280,height:900}});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(r.url().endsWith('/api/heatmap/events'))batches.push(r.postDataJSON());});
  await page.goto(`${root}/?screen=heatmap-target&study=${study}`);
  await page.waitForFunction(()=>!!window.UXLabCollector);
  await page.evaluate(()=>document.fonts.ready);
  const image=page.getByRole('img',{name:'Чёрный городской рюкзак'});
  const imageBox=await image.boundingBox(),surfaceBox=await page.locator('[data-ux-page]').boundingBox();
  await image.click({position:{x:35,y:40}});await image.click({position:{x:35,y:40}});
  await page.getByRole('button',{name:'Добавить в корзину',exact:true}).click();
  await expect.poll(async()=>(await read()).total.clicks).toBe(3);
  let data=await read();const desktop=data.groups.find(x=>x.page==='product'&&x.vw===1280);
  expect(desktop.clicks).toBe(3);
  const desktopPoints=await read(desktop.layout);expect(desktopPoints.points.find(x=>x.target==='backpack').count).toBe(2);
  const captured=batches[0].events[0];
  expect(Math.abs(captured.x-(imageBox.x+35-surfaceBox.x)/surfaceBox.width)).toBeLessThan(.001);
  expect(Math.abs(captured.y-(imageBox.y+40-surfaceBox.y)/surfaceBox.height)).toBeLessThan(.001);
  expect((await read(desktop.layout,'first')).points.reduce((sum,x)=>sum+x.count,0)).toBe(1);
  await page.route('**/api/heatmap/events',route=>route.abort());
  await page.getByRole('button',{name:'+',exact:true}).click();
  await expect(page.getByText(/Клики остаются в очереди/)).toBeVisible();
  expect((await read()).total.clicks).toBe(3);
  await page.unroute('**/api/heatmap/events');
  await expect.poll(async()=>(await read()).total.clicks,{timeout:10000}).toBe(4);
  // Retry the same accepted batch: server must not count it again.
  await fetch(`${api}/api/heatmap/events`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(batches[0])});
  expect((await read()).total.clicks).toBe(4);
  await page.getByRole('button',{name:'Каталог',exact:true}).click();
  await page.setViewportSize({width:390,height:600});
  await page.getByRole('button',{name:'Добавить в корзину',exact:true}).click();
  await expect.poll(async()=>(await read()).total.clicks).toBe(6);
  data=await read();const mobile=data.groups.find(x=>x.page==='product'&&x.vw===390);
  expect((await read(mobile.layout,'first')).points).toHaveLength(0);
  // A genuinely separate browser tab creates another session, including its first click.
  const second=await context.newPage();await second.setViewportSize({width:390,height:600});
  second.on('request',r=>{if(r.url().endsWith('/api/heatmap/events'))batches.push(r.postDataJSON());});
  await second.goto(`${root}/?screen=heatmap-target&study=${study}`);await second.waitForFunction(()=>!!window.UXLabCollector);await second.evaluate(()=>document.fonts.ready);
  await second.getByRole('button',{name:'Добавить в корзину',exact:true}).click();
  await expect.poll(async()=>(await read()).total.clicks).toBe(7);
  expect((await read()).total.sessions).toBe(2);
  expect((await read(mobile.layout,'first')).points.reduce((sum,x)=>sum+x.count,0)).toBe(1);
  // Form values are never sent, even when the user clicks inside a populated field.
  await second.getByRole('button',{name:'Оформить заказ',exact:true}).click();
  await second.getByLabel('Имя',{exact:true}).fill('Private Person');
  await second.getByLabel('Email',{exact:true}).fill('private@example.test');
  await second.getByLabel('Email',{exact:true}).click();
  await expect.poll(async()=>(await read()).total.clicks).toBe(9);
  const dashboard=await context.newPage();dashboard.on('pageerror',e=>errors.push(e.message));
  await dashboard.goto(`${root}/?screen=results-overview#/heatmap-live?link=${study}`);
  await dashboard.getByRole('button',{name:'Экран',exact:true}).click();
  await dashboard.getByRole('menuitemradio',{name:/Карточка товара/}).click();
  await dashboard.getByRole('button',{name:'Размер окна',exact:true}).click();
  await dashboard.getByRole('menuitemradio',{name:/1280 ×/}).click();
  await expect(dashboard.getByTestId('real-click-count')).toHaveText('3 кликов · 1 сессий');
  const frame=dashboard.frameLocator('iframe[title="Карта реальных кликов NOVA"]');
  await expect.poll(async()=>frame.locator('canvas').evaluate(c=>{const ctx=c.getContext('2d');return [...ctx.getImageData(0,0,c.width,c.height).data].some((x,i)=>i%4===3&&x>0);})).toBe(true);
  await expect(dashboard.getByText(/Размер или версия страницы изменились/)).toHaveCount(0);
  await dashboard.getByRole('tab',{name:'Первый клик',exact:true}).click();
  await expect(dashboard.getByTestId('real-click-count')).toHaveText('1 кликов · 1 сессий');
  await dashboard.getByRole('button',{name:'Скрыть слой кликов',exact:true}).click();
  await expect.poll(async()=>frame.locator('canvas').evaluate(c=>![...c.getContext('2d').getImageData(0,0,c.width,c.height).data].some((x,i)=>i%4===3&&x>0))).toBe(true);
  await dashboard.getByRole('button',{name:'Показать слой кликов',exact:true}).click();
  await dashboard.getByRole('tab',{name:'Все клики',exact:true}).click();
  await dashboard.getByRole('button',{name:'Изображение товара',exact:true}).click();
  await expect(dashboard.getByTestId('real-click-count')).toHaveText('2 кликов · 1 сессий');
  await dashboard.getByRole('button',{name:'Снять выбор элемента',exact:true}).click();
  await expect(dashboard.getByTestId('real-click-count')).toHaveText('3 кликов · 1 сессий');
  await dashboard.screenshot({path:'.tmp/heatmap/live-map.png',fullPage:true});
  await dashboard.reload();await expect(dashboard.getByText(/Сохранено в SQLite: 9 кликов, 2 сессий/)).toBeVisible();
  await dashboard.setViewportSize({width:390,height:844});expect(await dashboard.locator('main').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  expect(errors).toEqual([]);
  const serialized=JSON.stringify(batches);expect(serialized).not.toContain('private@example.test');expect(serialized).not.toContain('Private Person');
  expect(batches.flatMap(batch=>batch.events).some(event=>event.vw===390&&event.scroll_y>0)).toBe(true);
  const report={study,total:(await read()).total,checks:['real pointer events','capture before navigation','scroll and viewport isolation','first click per page/session','duplicate retry','offline retry','form values excluded','canvas density','layer toggle','target selection','reload persistence','mobile layout'],errors};
  await writeFile('.tmp/heatmap/audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
} finally {await browser.close();}
