import {chromium,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1100},reducedMotion:'reduce'});const results=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const story=async(name,route)=>{await page.goto(`http://localhost:6006/iframe.html?id=sandbox-results-overview--${name}&viewMode=story#/${route}`);await expect(page.locator('main')).toBeVisible();};
const click=async name=>page.getByRole('button',{name,exact:true}).click();
try {
  await story('connection-failure','setup');await click('Проверить подключение');await expect(page.getByText('Не удалось проверить подключение. Повторите проверку.',{exact:true})).toBeVisible();await click('Проверить подключение');await expect(page.getByRole('status').filter({hasText:'Демонстрационные события получены'})).toBeVisible();results.push('Connection error keeps draft and succeeds on retry');
  await story('launch-failure','studies');await page.getByRole('row').filter({hasText:'Навигация каталога'}).getByRole('button',{name:'Продолжить настройку'}).click();await click('К проверке и запуску');await click('Запустить исследование');await expect(page.getByText('Не удалось запустить исследование. Настройки сохранены.',{exact:true})).toBeVisible();await click('Запустить исследование');await expect(page.getByRole('heading',{name:'Без панели участника',exact:true})).toBeVisible();results.push('Launch error preserves readiness and retry creates both links');
  await story('transfer-failure','session?link=shopping');await page.getByRole('checkbox',{name:'Я согласен участвовать'}).check();await click('Начать исследование');await click('Приступить к заданию');await click('Добавить в корзину');await page.getByRole('radio',{name:'Выполнил задание',exact:true}).check();await click('Далее');await expect(page.getByText('Не удалось передать результаты. Ответ сохранён, повторите отправку.',{exact:true})).toBeVisible();await expect(page.getByRole('radio',{name:'Выполнил задание',exact:true})).toBeChecked();await click('Повторить отправку');await expect(page.getByRole('heading',{name:'Задание 2 из 3'})).toBeVisible();results.push('Transfer error retains response and retry advances without duplicate result');
  await story('default','studies');await page.getByRole('row').filter({hasText:'Первое знакомство с магазином'}).getByRole('button',{name:'Результаты',exact:true}).click();await expect(page.getByRole('heading',{name:'Режим: свободное изучение'})).toBeVisible();await expect(page.getByRole('table',{name:'Сценарии исследования'})).toHaveCount(0);await expect(page.getByRole('table',{name:'Страницы свободного изучения'})).toBeVisible();results.push('Free exploration uses a separate overview without success scoring');
  await story('default','replay?participant=missing');await expect(page.getByRole('heading',{name:'Запись недоступна'})).toBeVisible();await click('К участнику');await expect(page.getByText('Участник не найден в этом исследовании.',{exact:true})).toBeVisible();results.push('Missing recording/participant has a way back');
  await story('default','setup');await page.getByLabel('Название исследования *',{exact:true}).fill('');await expect(page.getByLabel('Название исследования *',{exact:true})).toHaveValue('');await page.getByLabel('Ссылка на тестируемый интерфейс *',{exact:true}).fill('not-a-url');await expect(page.getByLabel('Название исследования *',{exact:true})).toHaveValue('');await click('Сохранить черновик');await expect(page.getByText('Укажите название исследования и корректную ссылку http или https.',{exact:true})).toBeVisible();await expect(page.getByLabel('Название исследования *',{exact:true})).toHaveAttribute('aria-invalid','true');results.push('Required name and URL validate before saving');
  await story('default','session?link=shopping&clean=true');await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tmp/wire/full/interface-only-mobile.png'});results.push('Interface-only mobile fits 390px without panel');
  if(errors.length)throw Error(errors.join('\n'));
}catch(e){errors.push(e.message);process.exitCode=1;await page.screenshot({path:'.tmp/wire/full/edge-failure.png'});}
finally{await writeFile('.tmp/wire/full/edges.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors}));await browser.close();}
