import {seedChatSignal,chooseChatCriterion} from './criteria_browser_helpers.mjs';
import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const api=process.env.LIVE_TEST_API;if(!api)throw Error('Isolated API required');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
await context.route('http://127.0.0.1:5174/**',async r=>{const response=await r.fetch({url:r.request().url().replace('http://127.0.0.1:5174',api)});await r.fulfill({response});});
const get=async path=>(await fetch(api+path)).json();
const post=async(path,data)=>(await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json();
try{
 await seedChatSignal(post);
 const config=await post('/api/project/studies',{studyTitle:'Проверка чата',scenario:'Найдите окно чата и отправьте сообщение.'});const id=config.studyId;
 await post('/api/project/config?study='+id,{enabled:true,recordingMode:'screenshots'});
 const dash=await context.newPage();await dash.goto('http://127.0.0.1:5173/#/setup?study='+id);
 await chooseChatCriterion(dash,dash);await dash.getByRole('button',{name:'Сохранить сценарий'}).click();await expect(dash.getByText('Сценарий сохранён',{exact:true})).toBeVisible();
 await dash.getByRole('button',{name:'Свободное изучение',exact:true}).click();await expect(dash.getByRole('button',{name:'Как проверять результат'})).toHaveCount(0);await dash.getByRole('button',{name:'По сценарию',exact:true}).click();await expect(dash.getByLabel('Задание',{exact:true})).toHaveValue(config.scenario);
 await dash.screenshot({path:'.tmp/study-mode.png'});await dash.getByRole('button',{name:'Проверка и запуск',exact:true}).click();await dash.getByRole('button',{name:'Скопировать',exact:true}).click();await expect(dash.getByRole('status').filter({hasText:'Ссылка скопирована'})).toBeVisible();await dash.screenshot({path:'.tmp/copy-confirmation.png'});
 const participant=await context.newPage();await participant.goto(config.url);const modal=participant.getByRole('dialog',{name:'Задание исследования'});await expect(modal).toBeVisible();await expect(modal).toContainText(config.scenario);const box=await modal.boundingBox();assert.ok(Math.abs(box.x+box.width/2-720)<2&&Math.abs(box.y+box.height/2-500)<2);
 await participant.screenshot({path:'.tmp/task-dialog.png'});await modal.getByRole('button',{name:'Понятно, к заданию'}).click();
 const session=await participant.evaluate(()=>window.__uxLabStatus.session);
 const outcome=async sid=>(await get('/api/project?study='+id)).sessions.find(s=>s.id===sid)?.task;
 await expect.poll(async()=>(await outcome(session))?.status).toBe('pending');
 await participant.getByRole('button',{name:'Чаты',exact:true}).click();await participant.getByRole('button',{name:/Дмитриев Олег/}).click();
 assert.equal((await outcome(session)).status,'pending','Opening the chat is not completion');
 await participant.getByPlaceholder('Написать сообщение...').fill('   ');await expect(participant.getByRole('button',{name:'Отправить',exact:true})).toBeDisabled();
 await participant.getByPlaceholder('Написать сообщение...').fill('Проверка отправки');await participant.getByRole('button',{name:'Отправить',exact:true}).click();
 await expect.poll(async()=>(await outcome(session))?.status).toBe('succeeded');
 await participant.getByRole('button',{name:'Посмотреть задание'}).click();await modal.getByRole('button',{name:'Завершить задание'}).click();await expect(modal).toContainText('Попытка завершена');
 const failed=await context.newPage();await failed.goto(config.url);await expect(failed.getByRole('button',{name:'Завершить задание'})).toBeVisible();const failedSession=await failed.evaluate(()=>window.__uxLabStatus.session);await failed.getByRole('button',{name:'Завершить задание'}).click();await expect.poll(async()=>(await outcome(failedSession))?.status).toBe('failed');
 const pending=await context.newPage();await pending.goto(config.url);await expect(pending.getByRole('button',{name:'Завершить задание'})).toBeVisible();const pendingSession=await pending.evaluate(()=>window.__uxLabStatus.session);await pending.close();assert.equal((await outcome(pendingSession)).status,'pending');
 await dash.getByRole('button',{name:'Обзор результатов',exact:true}).click();await expect(dash.getByRole('table',{name:'Результаты заданий'}).getByText('1 из 3 сессий',{exact:true})).toBeVisible();await expect(dash.getByRole('columnheader',{name:'Доля кликов'})).toHaveCount(0);await dash.screenshot({path:'.tmp/task-results.png'});
 await dash.getByRole('button',{name:'Сессии',exact:true}).click();await expect(dash.getByRole('table').getByText('Не выполнено',{exact:true})).toBeVisible();await expect(dash.getByRole('table').getByText('Выполнено',{exact:true})).toBeVisible();
 const other=await post('/api/project/studies',{studyTitle:'Другое исследование'});await dash.reload();
 const nav=dash.getByRole('navigation',{name:'Основная навигация'});
 const picker=nav.getByRole('button',{name:'Выбрать исследование',exact:true});
 const sectionY=(await nav.getByRole('button',{name:'Настройка исследования',exact:true}).boundingBox()).y;
 await picker.focus();await dash.keyboard.press('Enter');
 await expect(dash.getByRole('menu',{name:'Исследования проекта'})).toBeVisible();
 await dash.route('**/api/project?**study='+other.studyId,async r=>{await new Promise(resolve=>setTimeout(resolve,1200));await r.fallback();});
 await dash.getByRole('menuitemradio',{name:'Другое исследование',exact:true}).click();
 await expect(picker).toContainText('Другое исследование',{timeout:500});
 assert.equal((await nav.getByRole('button',{name:'Настройка исследования',exact:true}).boundingBox()).y,sectionY);
 await expect(dash.getByText('Загружаем исследование…')).toBeVisible();
 await expect(dash).toHaveURL(new RegExp('#/participants.*study='+other.studyId));await expect(dash.getByText('Сессии не найдены.',{exact:true})).toBeVisible();
 await picker.click();await expect(dash.getByRole('menuitemradio',{name:'Другое исследование',exact:true})).toHaveAttribute('aria-checked','true');await dash.keyboard.press('Escape');
 await dash.screenshot({path:'.tmp/study-navigation.png'});
 assert.deepEqual(errors,[]);console.log('PASS modes, criteria, real chat send, blank/open non-success, finish/fail, abandoned pending, modal, copy toast, dropdown and scoped results');
}finally{await browser.close();}
