import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const api=process.env.LIVE_TEST_API,study=process.env.REPORT_TEST_STUDY;if(!api||!study)throw Error('Isolated fixture required');
await fs.mkdir('.tmp/project-reports',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100}});
const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
await context.route('http://127.0.0.1:5174/**',async r=>{const response=await r.fetch({url:r.request().url().replace('http://127.0.0.1:5174',api)});await r.fulfill({response})});
const page=await context.newPage();
try{
 await page.goto('http://127.0.0.1:5173/#/studies');await page.getByRole('button',{name:'Отчёты',exact:true}).click();await expect(page.getByRole('heading',{name:'Отчёты',exact:true})).toBeVisible();
 await expect(page.getByRole('table',{name:'Отчёты проекта'}).getByRole('row')).toHaveCount(2);
 await page.getByRole('button',{name:'Создать отчёт',exact:true}).click();await page.getByLabel('Название отчёта',{exact:true}).fill('Мобильный отчёт');
 await page.getByRole('button',{name:'Исследование для отчёта',exact:true}).click();await page.getByRole('menuitemradio',{name:'Мобильное исследование',exact:true}).click();
 await page.getByRole('button',{name:'Размер экрана в отчёте',exact:true}).click();await page.getByRole('menuitemradio',{name:'До 768 px',exact:true}).click();
 for(const label of ['Выполнение заданий','Активность по экранам','Сессии и результаты','Воронка переходов','Сигналы затруднений','Находки'])await page.getByRole('checkbox',{name:label,exact:true}).uncheck();
 await expect(page.getByRole('button',{name:'Сформировать PDF',exact:true})).toBeDisabled();
 await page.getByRole('checkbox',{name:'Сессии и результаты',exact:true}).check();
 await page.screenshot({path:'.tmp/project-reports/settings.png'});
 await page.getByRole('button',{name:'Сформировать PDF',exact:true}).click();await expect(page.getByRole('heading',{name:'Мобильный отчёт',exact:true})).toBeVisible();
 await expect(page.getByRole('table',{name:'Сессии отчёта'})).toContainText('mobile-session');await expect(page.getByRole('heading',{name:'Воронка переходов',exact:true})).toHaveCount(0);
 await page.reload();await expect(page.getByRole('heading',{name:'Мобильный отчёт',exact:true})).toBeVisible();
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать PDF',exact:true}).click();await (await downloaded).saveAs('.tmp/project-reports/mobile-report.pdf');
 const bytes=await fs.readFile('.tmp/project-reports/mobile-report.pdf');assert.equal(bytes.subarray(0,5).toString(),'%PDF-');
 await page.getByRole('button',{name:'К списку отчётов',exact:true}).click();await expect(page.getByRole('table',{name:'Отчёты проекта'}).getByRole('row')).toHaveCount(3);
 const mobileRow=page.getByRole('table',{name:'Отчёты проекта'}).getByRole('row').filter({hasText:'Мобильный отчёт'});
 await expect(mobileRow.getByRole('button',{name:'Открыть',exact:true})).toHaveCount(0);
 const icon=mobileRow.getByRole('button',{name:'Скачать PDF: Мобильный отчёт',exact:true});await expect(icon).toHaveText('');
 const listUrl=page.url(),iconDownload=page.waitForEvent('download');await icon.click();await(await iconDownload).saveAs('.tmp/project-reports/list-download.pdf');assert.equal(page.url(),listUrl,'Download must not open the report');
 await mobileRow.getByRole('cell').nth(1).click();await expect(page.getByRole('heading',{name:'Мобильный отчёт',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'К списку отчётов',exact:true}).click();
 await page.screenshot({path:'.tmp/project-reports/list.png'});
 await page.getByRole('button',{name:'Фильтр по исследованию',exact:true}).click();await page.getByRole('menuitemradio',{name:'Мобильное исследование',exact:true}).click();await expect(page.getByRole('table',{name:'Отчёты проекта'}).getByRole('row')).toHaveCount(2);
 const reports=await (await fetch(api+'/api/project/reports')).json(),report=reports.reports.find(r=>r.title==='Мобильный отчёт');assert.equal(report.project.studyId,study);assert.equal(report.total.sessions,1);assert.deepEqual(report.sections,['sessions']);assert.equal(report.device,'mobile');
 await page.getByRole('button',{name:'Фильтр по исследованию',exact:true}).click();await page.getByRole('menuitemradio',{name:'Все исследования',exact:true}).click();
 await page.getByRole('table',{name:'Отчёты проекта'}).getByRole('row').filter({hasText:'Исследование Lead Generation'}).locator('[data-row-action]').focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('heading',{name:'Воронка переходов',exact:true})).toBeVisible();
 const oldDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать PDF',exact:true}).click();await(await oldDownload).saveAs('.tmp/project-reports/legacy-report.pdf');
 assert.deepEqual(errors,[]);console.log('PASS project navigation, legacy reports, cross-study selection, filters, section validation, snapshot reload, downloadable PDFs, isolation.');
}catch(e){await page.screenshot({path:'.tmp/project-reports/failure.png'});throw e}finally{await browser.close()}
