"""Synchronize CSF3 stories from the existing React/Figma catalog, never redraw UI."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / 'src/components/catalog.json').read_text(encoding='utf-8'))
js = lambda value: json.dumps(value, ensure_ascii=False)
index = []
for entry in catalog:
    name = entry['exportName']
    local_name = 'SourceDefault' if name == 'Default' else name
    story_id = 'ds-' + entry['id'].replace(':', '-')
    desc = entry.get('description') or f"{entry['name']} — компонент существующей базы UX-Lab."
    if entry.get('deprecated'):
        desc += '\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.'
    key = '1LeVoicxDT7Sl8TpMPs4hr' if entry['source'] == 'product' else 'SNBSKtwsO81j3BdjRGFpAw'
    url = f"https://www.figma.com/design/{key}/?node-id={entry['id'].replace(':', '-')}"
    desc += f"\n\n[Исходный компонент Figma]({url}) · {len(entry['variants'])} вариантов."
    arg_types = {}
    for prop, definition in entry['properties'].items():
        options = definition.get('variantOptions')
        control = ('inline-radio' if len(options) <= 4 else 'select') if options else 'boolean' if definition['type'] == 'BOOLEAN' else 'text'
        arg_types[prop] = {'control': control, 'description': f"Свойство Figma: {prop.split('#')[0]}", 'table': {'category': 'Figma', 'defaultValue': {'summary': str(definition.get('defaultValue', ''))}}}
        if options:
            arg_types[prop]['options'] = options
        if definition['type'] == 'INSTANCE_SWAP':
            arg_types[prop]['description'] += ' · ID исходного компонента иконки; см. Foundation/Icons.'
    for prop in ['children', 'label', 'className']:
        arg_types[prop] = {'control': 'text', 'table': {'category': 'React'}, 'description': {'children':'Содержимое компонента', 'label':'Доступная подпись', 'className':'Дополнительный CSS-класс'}[prop]}
    for prop in ['onClick','onChange']:
        arg_types[prop] = {'control': False, 'action': prop, 'table': {'category': 'Events'}, 'description':'Обработчик взаимодействия'}
    if entry['source'] == 'product':
        extras = {
            'ParticipantsTable': {'rows':'object','onOpenRecording':False},
            'ScenarioTable': {'rows':'object','onSelectScenario':False},
            'ReplayControls': {'duration':'number','position':'number','onSeek':False,'onPlaybackChange':False,'onSpeedChange':False,'onFitChange':False,'onFullscreen':False},
            'AttemptAction': {'attempts':'object','onSelectAttempt':False,'onOpenRecording':False},
            'TaskChoiceCard': {'groupName':'text'},
            'ProductField': {'value':'text','options':'object'},
            'ProductButton': {'icon':'text','iconRight':'text'},
            'ProductNavItem': {'icon':'text'},
        }.get(name,{})
        for prop, control in extras.items():
            arg_types[prop] = {'control':control,'description':'Данные / обработчик компонента','table':{'category':'React'}}
            if control is False: arg_types[prop]['action'] = prop
    if name == 'Modal':
        arg_types.update({'title':{'control':'text','description':'Заголовок диалога'},'footer':{'control':False,'description':'ReactNode: действия и статус внизу окна'}})
    if name == 'Toast':
        arg_types['title']={'control':'text','description':'Заголовок уведомления'}
    defaults = entry['defaults'].copy()
    if name == 'ProductButton': defaults['children'] = 'Сохранить исследование'
    if name == 'ProductTab': defaults['children'] = 'Сигналы'
    if name == 'ProductNavItem': defaults['children'] = 'Обзор результатов'
    group = 'UX-Lab' if entry['source']=='product' else 'Elastic UI'
    safe_title = entry['name'].replace('/', ' · ').strip()
    lines = [
        '// Generated by execution/generate_storybook_catalog.py; source: catalog.json.',
        "import type { Meta, StoryObj } from '@storybook/react-vite';",
        f"import {{ {name}{' as SourceDefault' if name == 'Default' else ''} }} from './{name}';",
        "import { VariantMatrix } from '../../storybook/VariantMatrix';",
        f'/** {name}: варианты, контролы и готовый код использования. */',
        'const meta = {',
        f'  id: {js(story_id)}, title: {js("Components/"+group+"/"+safe_title+" ["+entry["id"]+"]")},',
        f'  component: {local_name}, tags: [\'autodocs\'],',
        f'  args: {js(defaults)},',
        f'  argTypes: {js(arg_types)},',
        f'  parameters: {{ layout: "padded", catalogId: {js(entry["id"])}, exportName: {js(name)}, docs: {{ description: {{ component: {js(desc)} }} }} }},',
        f'}} satisfies Meta<typeof {local_name}>;',
        'export default meta;',
        'type Story = StoryObj<typeof meta>;',
        '/** Живой пример; свойства меняются в Controls. */',
        'export const Default: Story = {};',
        '/** Полная исходная матрица, без искусственного декартова произведения. */',
        f'export const AllVariants: Story = {{ tags: ["!autodocs"], render: () => <VariantMatrix catalogId={js(entry["id"])} component={{{local_name}}} storyId={js(story_id)}/> }};',
    ]
    variants=[]
    for n, variant in enumerate(entry['variants']):
        export = f'Variant{n+1:03}'
        label = ' · '.join(f'{k}: {v}' for k,v in variant.items()) or 'Одиночный компонент'
        lines += [f'/** {label.replace("*/", "")} */',f'export const {export}: Story = {{ name: {js(label)}, args: {js(variant)}, tags: ["!autodocs"] }};']
        variants.append({'id': f'{story_id}--variant-{n+1:03}', 'args':variant})
    target=ROOT/f'src/components/{name}/{name}.stories.tsx'
    target.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    index.append({'catalogId':entry['id'],'exportName':name,'id':story_id,'variants':variants,'file':str(target.relative_to(ROOT)).replace('\\','/')})
(ROOT/'src/storybook').mkdir(exist_ok=True)
(ROOT/'src/storybook/story-index.json').write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'components':len(index),'variants':sum(len(e['variants']) for e in index)}))
