// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ProductCheckbox } from './ProductCheckbox';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ProductCheckbox: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-282-2918", title: "Components/UX-Lab/ProductCheckbox [282:2918]",
  component: ProductCheckbox, tags: ['autodocs'],
  args: {"Label#282:0": "Включить раздел в отчёт", "Value": "Off", "State": "Default"},
  argTypes: {"Label#282:0": {"control": "text", "description": "Свойство Figma: Label", "table": {"category": "Figma", "defaultValue": {"summary": "Включить раздел в отчёт"}}}, "Value": {"control": "inline-radio", "description": "Свойство Figma: Value", "table": {"category": "Figma", "defaultValue": {"summary": "Off"}}, "options": ["Off", "On", "Mixed"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Focus", "Disabled"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "282:2918", exportName: "ProductCheckbox", docs: { description: { component: "ProductCheckbox — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=282-2918) · 12 вариантов." } } },
} satisfies Meta<typeof ProductCheckbox>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="282:2918" component={ProductCheckbox} storyId="ds-282-2918"/> };
/** Value: Off · State: Default */
export const Variant001: Story = { name: "Value: Off · State: Default", args: {"Value": "Off", "State": "Default"}, tags: ["!autodocs"] };
/** Value: On · State: Default */
export const Variant002: Story = { name: "Value: On · State: Default", args: {"Value": "On", "State": "Default"}, tags: ["!autodocs"] };
/** Value: Mixed · State: Default */
export const Variant003: Story = { name: "Value: Mixed · State: Default", args: {"Value": "Mixed", "State": "Default"}, tags: ["!autodocs"] };
/** Value: Off · State: Hover */
export const Variant004: Story = { name: "Value: Off · State: Hover", args: {"Value": "Off", "State": "Hover"}, tags: ["!autodocs"] };
/** Value: On · State: Hover */
export const Variant005: Story = { name: "Value: On · State: Hover", args: {"Value": "On", "State": "Hover"}, tags: ["!autodocs"] };
/** Value: Mixed · State: Hover */
export const Variant006: Story = { name: "Value: Mixed · State: Hover", args: {"Value": "Mixed", "State": "Hover"}, tags: ["!autodocs"] };
/** Value: Off · State: Focus */
export const Variant007: Story = { name: "Value: Off · State: Focus", args: {"Value": "Off", "State": "Focus"}, tags: ["!autodocs"] };
/** Value: On · State: Focus */
export const Variant008: Story = { name: "Value: On · State: Focus", args: {"Value": "On", "State": "Focus"}, tags: ["!autodocs"] };
/** Value: Mixed · State: Focus */
export const Variant009: Story = { name: "Value: Mixed · State: Focus", args: {"Value": "Mixed", "State": "Focus"}, tags: ["!autodocs"] };
/** Value: Off · State: Disabled */
export const Variant010: Story = { name: "Value: Off · State: Disabled", args: {"Value": "Off", "State": "Disabled"}, tags: ["!autodocs"] };
/** Value: On · State: Disabled */
export const Variant011: Story = { name: "Value: On · State: Disabled", args: {"Value": "On", "State": "Disabled"}, tags: ["!autodocs"] };
/** Value: Mixed · State: Disabled */
export const Variant012: Story = { name: "Value: Mixed · State: Disabled", args: {"Value": "Mixed", "State": "Disabled"}, tags: ["!autodocs"] };
