// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SelectableListSearchable } from './SelectableListSearchable';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SelectableListSearchable: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14674-8052", title: "Components/Elastic UI/☠️ Selectable List - Searchable [14674:8052]",
  component: SelectableListSearchable, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14674:8052", exportName: "SelectableListSearchable", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14674-8052) · 1 вариантов." } } },
} satisfies Meta<typeof SelectableListSearchable>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14674:8052" component={SelectableListSearchable} storyId="ds-14674-8052"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
