// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DataGridToolbar } from './DataGridToolbar';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DataGridToolbar: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-46305-10170", title: "Components/Elastic UI/.🧱 Data Grid - Toolbar [46305:10170]",
  component: DataGridToolbar, tags: ['autodocs'],
  args: {"Text #46240:0": false, "Sorted#46240:1": true, "Bulk Actions Button#46290:0": true, "Show columns#46905:0": true, "Border": "None"},
  argTypes: {"Text #46240:0": {"control": "boolean", "description": "Свойство Figma: Text ", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Sorted#46240:1": {"control": "boolean", "description": "Свойство Figma: Sorted", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Bulk Actions Button#46290:0": {"control": "boolean", "description": "Свойство Figma: Bulk Actions Button", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Show columns#46905:0": {"control": "boolean", "description": "Свойство Figma: Show columns", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Border": {"control": "inline-radio", "description": "Свойство Figma: Border", "table": {"category": "Figma", "defaultValue": {"summary": "None"}}, "options": ["None", "All", "Horizontal"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "46305:10170", exportName: "DataGridToolbar", docs: { description: { component: ".🧱 Data Grid - Toolbar — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=46305-10170) · 3 вариантов." } } },
} satisfies Meta<typeof DataGridToolbar>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="46305:10170" component={DataGridToolbar} storyId="ds-46305-10170"/> };
/** Border: None */
export const Variant001: Story = { name: "Border: None", args: {"Border": "None"}, tags: ["!autodocs"] };
/** Border: All */
export const Variant002: Story = { name: "Border: All", args: {"Border": "All"}, tags: ["!autodocs"] };
/** Border: Horizontal */
export const Variant003: Story = { name: "Border: Horizontal", args: {"Border": "Horizontal"}, tags: ["!autodocs"] };
