// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { StepHorizontal } from './StepHorizontal';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** StepHorizontal: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14775-90378", title: "Components/Elastic UI/.📦 Step - Horizontal [14775:90378]",
  component: StepHorizontal, tags: ['autodocs'],
  args: {"Size": "Medium", "Position": "First", "Status": "default"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "XSmall"]}, "Position": {"control": "inline-radio", "description": "Свойство Figma: Position", "table": {"category": "Figma", "defaultValue": {"summary": "First"}}, "options": ["First", "Last", "Middle"]}, "Status": {"control": "select", "description": "Свойство Figma: Status", "table": {"category": "Figma", "defaultValue": {"summary": "default"}}, "options": ["default", "incomplete", "disabled", "loading", "warning", "danger", "complete", "current"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14775:90378", exportName: "StepHorizontal", docs: { description: { component: ".📦 Step - Horizontal — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14775-90378) · 72 вариантов." } } },
} satisfies Meta<typeof StepHorizontal>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14775:90378" component={StepHorizontal} storyId="ds-14775-90378"/> };
/** Size: Medium · Position: First · Status: default */
export const Variant001: Story = { name: "Size: Medium · Position: First · Status: default", args: {"Size": "Medium", "Position": "First", "Status": "default"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: incomplete */
export const Variant002: Story = { name: "Size: Medium · Position: First · Status: incomplete", args: {"Size": "Medium", "Position": "First", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: loading */
export const Variant003: Story = { name: "Size: Medium · Position: First · Status: loading", args: {"Size": "Medium", "Position": "First", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: complete */
export const Variant004: Story = { name: "Size: Medium · Position: First · Status: complete", args: {"Size": "Medium", "Position": "First", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: warning */
export const Variant005: Story = { name: "Size: Medium · Position: First · Status: warning", args: {"Size": "Medium", "Position": "First", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: danger */
export const Variant006: Story = { name: "Size: Medium · Position: First · Status: danger", args: {"Size": "Medium", "Position": "First", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: default */
export const Variant007: Story = { name: "Size: Medium · Position: Middle · Status: default", args: {"Size": "Medium", "Position": "Middle", "Status": "default"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: disabled */
export const Variant008: Story = { name: "Size: Medium · Position: First · Status: disabled", args: {"Size": "Medium", "Position": "First", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: incomplete */
export const Variant009: Story = { name: "Size: Medium · Position: Middle · Status: incomplete", args: {"Size": "Medium", "Position": "Middle", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: loading */
export const Variant010: Story = { name: "Size: Medium · Position: Middle · Status: loading", args: {"Size": "Medium", "Position": "Middle", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: complete */
export const Variant011: Story = { name: "Size: Medium · Position: Middle · Status: complete", args: {"Size": "Medium", "Position": "Middle", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: warning */
export const Variant012: Story = { name: "Size: Medium · Position: Middle · Status: warning", args: {"Size": "Medium", "Position": "Middle", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: danger */
export const Variant013: Story = { name: "Size: Medium · Position: Middle · Status: danger", args: {"Size": "Medium", "Position": "Middle", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: default */
export const Variant014: Story = { name: "Size: Medium · Position: Last · Status: default", args: {"Size": "Medium", "Position": "Last", "Status": "default"}, tags: ["!autodocs"] };
/** Size: Medium · Position: First · Status: current */
export const Variant015: Story = { name: "Size: Medium · Position: First · Status: current", args: {"Size": "Medium", "Position": "First", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: current */
export const Variant016: Story = { name: "Size: Medium · Position: Middle · Status: current", args: {"Size": "Medium", "Position": "Middle", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: current */
export const Variant017: Story = { name: "Size: Medium · Position: Last · Status: current", args: {"Size": "Medium", "Position": "Last", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Middle · Status: disabled */
export const Variant018: Story = { name: "Size: Medium · Position: Middle · Status: disabled", args: {"Size": "Medium", "Position": "Middle", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: incomplete */
export const Variant019: Story = { name: "Size: Medium · Position: Last · Status: incomplete", args: {"Size": "Medium", "Position": "Last", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: loading */
export const Variant020: Story = { name: "Size: Medium · Position: Last · Status: loading", args: {"Size": "Medium", "Position": "Last", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: complete */
export const Variant021: Story = { name: "Size: Medium · Position: Last · Status: complete", args: {"Size": "Medium", "Position": "Last", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: warning */
export const Variant022: Story = { name: "Size: Medium · Position: Last · Status: warning", args: {"Size": "Medium", "Position": "Last", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: danger */
export const Variant023: Story = { name: "Size: Medium · Position: Last · Status: danger", args: {"Size": "Medium", "Position": "Last", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Medium · Position: Last · Status: disabled */
export const Variant024: Story = { name: "Size: Medium · Position: Last · Status: disabled", args: {"Size": "Medium", "Position": "Last", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: current */
export const Variant025: Story = { name: "Size: Small · Position: First · Status: current", args: {"Size": "Small", "Position": "First", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: incomplete */
export const Variant026: Story = { name: "Size: Small · Position: First · Status: incomplete", args: {"Size": "Small", "Position": "First", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: loading */
export const Variant027: Story = { name: "Size: Small · Position: First · Status: loading", args: {"Size": "Small", "Position": "First", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: complete */
export const Variant028: Story = { name: "Size: Small · Position: First · Status: complete", args: {"Size": "Small", "Position": "First", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: warning */
export const Variant029: Story = { name: "Size: Small · Position: First · Status: warning", args: {"Size": "Small", "Position": "First", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: danger */
export const Variant030: Story = { name: "Size: Small · Position: First · Status: danger", args: {"Size": "Small", "Position": "First", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: current */
export const Variant031: Story = { name: "Size: Small · Position: Middle · Status: current", args: {"Size": "Small", "Position": "Middle", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: disabled */
export const Variant032: Story = { name: "Size: Small · Position: First · Status: disabled", args: {"Size": "Small", "Position": "First", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: incomplete */
export const Variant033: Story = { name: "Size: Small · Position: Middle · Status: incomplete", args: {"Size": "Small", "Position": "Middle", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: loading */
export const Variant034: Story = { name: "Size: Small · Position: Middle · Status: loading", args: {"Size": "Small", "Position": "Middle", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: complete */
export const Variant035: Story = { name: "Size: Small · Position: Middle · Status: complete", args: {"Size": "Small", "Position": "Middle", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: warning */
export const Variant036: Story = { name: "Size: Small · Position: Middle · Status: warning", args: {"Size": "Small", "Position": "Middle", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: danger */
export const Variant037: Story = { name: "Size: Small · Position: Middle · Status: danger", args: {"Size": "Small", "Position": "Middle", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: current */
export const Variant038: Story = { name: "Size: Small · Position: Last · Status: current", args: {"Size": "Small", "Position": "Last", "Status": "current"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: disabled */
export const Variant039: Story = { name: "Size: Small · Position: Middle · Status: disabled", args: {"Size": "Small", "Position": "Middle", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: incomplete */
export const Variant040: Story = { name: "Size: Small · Position: Last · Status: incomplete", args: {"Size": "Small", "Position": "Last", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: loading */
export const Variant041: Story = { name: "Size: Small · Position: Last · Status: loading", args: {"Size": "Small", "Position": "Last", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: complete */
export const Variant042: Story = { name: "Size: Small · Position: Last · Status: complete", args: {"Size": "Small", "Position": "Last", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: warning */
export const Variant043: Story = { name: "Size: Small · Position: Last · Status: warning", args: {"Size": "Small", "Position": "Last", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: danger */
export const Variant044: Story = { name: "Size: Small · Position: Last · Status: danger", args: {"Size": "Small", "Position": "Last", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: disabled */
export const Variant045: Story = { name: "Size: Small · Position: Last · Status: disabled", args: {"Size": "Small", "Position": "Last", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: Small · Position: First · Status: default */
export const Variant046: Story = { name: "Size: Small · Position: First · Status: default", args: {"Size": "Small", "Position": "First", "Status": "default"}, tags: ["!autodocs"] };
/** Size: Small · Position: Middle · Status: default */
export const Variant047: Story = { name: "Size: Small · Position: Middle · Status: default", args: {"Size": "Small", "Position": "Middle", "Status": "default"}, tags: ["!autodocs"] };
/** Size: Small · Position: Last · Status: default */
export const Variant048: Story = { name: "Size: Small · Position: Last · Status: default", args: {"Size": "Small", "Position": "Last", "Status": "default"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: current */
export const Variant049: Story = { name: "Size: XSmall · Position: First · Status: current", args: {"Size": "XSmall", "Position": "First", "Status": "current"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: incomplete */
export const Variant050: Story = { name: "Size: XSmall · Position: First · Status: incomplete", args: {"Size": "XSmall", "Position": "First", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: loading */
export const Variant051: Story = { name: "Size: XSmall · Position: First · Status: loading", args: {"Size": "XSmall", "Position": "First", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: complete */
export const Variant052: Story = { name: "Size: XSmall · Position: First · Status: complete", args: {"Size": "XSmall", "Position": "First", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: warning */
export const Variant053: Story = { name: "Size: XSmall · Position: First · Status: warning", args: {"Size": "XSmall", "Position": "First", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: danger */
export const Variant054: Story = { name: "Size: XSmall · Position: First · Status: danger", args: {"Size": "XSmall", "Position": "First", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: current */
export const Variant055: Story = { name: "Size: XSmall · Position: Middle · Status: current", args: {"Size": "XSmall", "Position": "Middle", "Status": "current"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: disabled */
export const Variant056: Story = { name: "Size: XSmall · Position: First · Status: disabled", args: {"Size": "XSmall", "Position": "First", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: incomplete */
export const Variant057: Story = { name: "Size: XSmall · Position: Middle · Status: incomplete", args: {"Size": "XSmall", "Position": "Middle", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: loading */
export const Variant058: Story = { name: "Size: XSmall · Position: Middle · Status: loading", args: {"Size": "XSmall", "Position": "Middle", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: complete */
export const Variant059: Story = { name: "Size: XSmall · Position: Middle · Status: complete", args: {"Size": "XSmall", "Position": "Middle", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: warning */
export const Variant060: Story = { name: "Size: XSmall · Position: Middle · Status: warning", args: {"Size": "XSmall", "Position": "Middle", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: danger */
export const Variant061: Story = { name: "Size: XSmall · Position: Middle · Status: danger", args: {"Size": "XSmall", "Position": "Middle", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: current */
export const Variant062: Story = { name: "Size: XSmall · Position: Last · Status: current", args: {"Size": "XSmall", "Position": "Last", "Status": "current"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: disabled */
export const Variant063: Story = { name: "Size: XSmall · Position: Middle · Status: disabled", args: {"Size": "XSmall", "Position": "Middle", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: incomplete */
export const Variant064: Story = { name: "Size: XSmall · Position: Last · Status: incomplete", args: {"Size": "XSmall", "Position": "Last", "Status": "incomplete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: loading */
export const Variant065: Story = { name: "Size: XSmall · Position: Last · Status: loading", args: {"Size": "XSmall", "Position": "Last", "Status": "loading"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: complete */
export const Variant066: Story = { name: "Size: XSmall · Position: Last · Status: complete", args: {"Size": "XSmall", "Position": "Last", "Status": "complete"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: warning */
export const Variant067: Story = { name: "Size: XSmall · Position: Last · Status: warning", args: {"Size": "XSmall", "Position": "Last", "Status": "warning"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: danger */
export const Variant068: Story = { name: "Size: XSmall · Position: Last · Status: danger", args: {"Size": "XSmall", "Position": "Last", "Status": "danger"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: disabled */
export const Variant069: Story = { name: "Size: XSmall · Position: Last · Status: disabled", args: {"Size": "XSmall", "Position": "Last", "Status": "disabled"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: First · Status: default */
export const Variant070: Story = { name: "Size: XSmall · Position: First · Status: default", args: {"Size": "XSmall", "Position": "First", "Status": "default"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Middle · Status: default */
export const Variant071: Story = { name: "Size: XSmall · Position: Middle · Status: default", args: {"Size": "XSmall", "Position": "Middle", "Status": "default"}, tags: ["!autodocs"] };
/** Size: XSmall · Position: Last · Status: default */
export const Variant072: Story = { name: "Size: XSmall · Position: Last · Status: default", args: {"Size": "XSmall", "Position": "Last", "Status": "default"}, tags: ["!autodocs"] };
