// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Tabs } from './Tabs';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Tabs: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-32618-392277", title: "Components/Elastic UI/☠️ Tabs [32618:392277]",
  component: Tabs, tags: ['autodocs'],
  args: {"Border#32618:13": true, "Size": "Medium*", "Expand": "False"},
  argTypes: {"Border#32618:13": {"control": "boolean", "description": "Свойство Figma: Border", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium*"}}, "options": ["Medium*", "Small", "Large", "X-Large"]}, "Expand": {"control": "inline-radio", "description": "Свойство Figma: Expand", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "32618:392277", exportName: "Tabs", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=32618-392277) · 8 вариантов." } } },
} satisfies Meta<typeof Tabs>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="32618:392277" component={Tabs} storyId="ds-32618-392277"/> };
/** Size: Medium* · Expand: False */
export const Variant001: Story = { name: "Size: Medium* · Expand: False", args: {"Size": "Medium*", "Expand": "False"}, tags: ["!autodocs"] };
/** Size: Small · Expand: False */
export const Variant002: Story = { name: "Size: Small · Expand: False", args: {"Size": "Small", "Expand": "False"}, tags: ["!autodocs"] };
/** Size: Large · Expand: False */
export const Variant003: Story = { name: "Size: Large · Expand: False", args: {"Size": "Large", "Expand": "False"}, tags: ["!autodocs"] };
/** Size: X-Large · Expand: False */
export const Variant004: Story = { name: "Size: X-Large · Expand: False", args: {"Size": "X-Large", "Expand": "False"}, tags: ["!autodocs"] };
/** Size: Small · Expand: True */
export const Variant005: Story = { name: "Size: Small · Expand: True", args: {"Size": "Small", "Expand": "True"}, tags: ["!autodocs"] };
/** Size: Medium* · Expand: True */
export const Variant006: Story = { name: "Size: Medium* · Expand: True", args: {"Size": "Medium*", "Expand": "True"}, tags: ["!autodocs"] };
/** Size: Large · Expand: True */
export const Variant007: Story = { name: "Size: Large · Expand: True", args: {"Size": "Large", "Expand": "True"}, tags: ["!autodocs"] };
/** Size: X-Large · Expand: True */
export const Variant008: Story = { name: "Size: X-Large · Expand: True", args: {"Size": "X-Large", "Expand": "True"}, tags: ["!autodocs"] };
