// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ListGroupItemNode15132_116026 } from './ListGroupItemNode15132_116026';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ListGroupItemNode15132_116026: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15132-116026", title: "Components/Elastic UI/.📦 List Group  ·  Item [15132:116026]",
  component: ListGroupItemNode15132_116026, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15132:116026", exportName: "ListGroupItemNode15132_116026", docs: { description: { component: ".📦 List Group / Item — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15132-116026) · 1 вариантов." } } },
} satisfies Meta<typeof ListGroupItemNode15132_116026>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15132:116026" component={ListGroupItemNode15132_116026} storyId="ds-15132-116026"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
