// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ColorPaletteDisplay } from './ColorPaletteDisplay';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ColorPaletteDisplay: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15884-173623", title: "Components/Elastic UI/📦 Color Palette Display [15884:173623]",
  component: ColorPaletteDisplay, tags: ['autodocs'],
  args: {"Palette": "Color blind"},
  argTypes: {"Palette": {"control": "inline-radio", "description": "Свойство Figma: Palette", "table": {"category": "Figma", "defaultValue": {"summary": "Color blind"}}, "options": ["Color blind", "Color blind (natural)"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15884:173623", exportName: "ColorPaletteDisplay", docs: { description: { component: "&lt;EuiColorPaletteDisplay&gt;\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15884-173623) · 2 вариантов." } } },
} satisfies Meta<typeof ColorPaletteDisplay>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15884:173623" component={ColorPaletteDisplay} storyId="ds-15884-173623"/> };
/** Palette: Color blind */
export const Variant001: Story = { name: "Palette: Color blind", args: {"Palette": "Color blind"}, tags: ["!autodocs"] };
/** Palette: Color blind (natural) */
export const Variant002: Story = { name: "Palette: Color blind (natural)", args: {"Palette": "Color blind (natural)"}, tags: ["!autodocs"] };
