// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DataCoverage } from './DataCoverage';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DataCoverage: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-86-370", title: "Components/UX-Lab/DataCoverage [86:370]",
  component: DataCoverage, tags: ['autodocs'],
  args: {"ShowAction#86:10": true, "DetailTextComplete#89:0": "События и запись доступны для анализа.", "DetailTextPartial#89:4": "Часть записи отсутствует. Это не означает неуспех задания.", "DetailTextUnavailable#89:8": "Причина недоступности уточняется.", "Coverage": "Complete"},
  argTypes: {"ShowAction#86:10": {"control": "boolean", "description": "Свойство Figma: ShowAction", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "DetailTextComplete#89:0": {"control": "text", "description": "Свойство Figma: DetailTextComplete", "table": {"category": "Figma", "defaultValue": {"summary": "События и запись доступны для анализа."}}}, "DetailTextPartial#89:4": {"control": "text", "description": "Свойство Figma: DetailTextPartial", "table": {"category": "Figma", "defaultValue": {"summary": "Часть записи отсутствует. Это не означает неуспех задания."}}}, "DetailTextUnavailable#89:8": {"control": "text", "description": "Свойство Figma: DetailTextUnavailable", "table": {"category": "Figma", "defaultValue": {"summary": "Причина недоступности уточняется."}}}, "Coverage": {"control": "inline-radio", "description": "Свойство Figma: Coverage", "table": {"category": "Figma", "defaultValue": {"summary": "Complete"}}, "options": ["Complete", "Partial", "Unavailable"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "86:370", exportName: "DataCoverage", docs: { description: { component: "DataCoverage — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=86-370) · 3 вариантов." } } },
} satisfies Meta<typeof DataCoverage>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="86:370" component={DataCoverage} storyId="ds-86-370"/> };
/** Coverage: Complete */
export const Variant001: Story = { name: "Coverage: Complete", args: {"Coverage": "Complete"}, tags: ["!autodocs"] };
/** Coverage: Partial */
export const Variant002: Story = { name: "Coverage: Partial", args: {"Coverage": "Partial"}, tags: ["!autodocs"] };
/** Coverage: Unavailable */
export const Variant003: Story = { name: "Coverage: Unavailable", args: {"Coverage": "Unavailable"}, tags: ["!autodocs"] };
