// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FilePickerLargeInput } from './FilePickerLargeInput';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FilePickerLargeInput: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-44632-22134", title: "Components/Elastic UI/.File Picker  ·  Large Input [44632:22134]",
  component: FilePickerLargeInput, tags: ['autodocs'],
  args: {"State": "Placeholder"},
  argTypes: {"State": {"control": "select", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Placeholder"}}, "options": ["Disabled", "Placeholder", "Focus", "Invalid", "Filled"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "44632:22134", exportName: "FilePickerLargeInput", docs: { description: { component: ".File Picker / Large Input — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=44632-22134) · 5 вариантов." } } },
} satisfies Meta<typeof FilePickerLargeInput>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="44632:22134" component={FilePickerLargeInput} storyId="ds-44632-22134"/> };
/** State: Placeholder */
export const Variant001: Story = { name: "State: Placeholder", args: {"State": "Placeholder"}, tags: ["!autodocs"] };
/** State: Focus */
export const Variant002: Story = { name: "State: Focus", args: {"State": "Focus"}, tags: ["!autodocs"] };
/** State: Invalid */
export const Variant003: Story = { name: "State: Invalid", args: {"State": "Invalid"}, tags: ["!autodocs"] };
/** State: Filled */
export const Variant004: Story = { name: "State: Filled", args: {"State": "Filled"}, tags: ["!autodocs"] };
/** State: Disabled */
export const Variant005: Story = { name: "State: Disabled", args: {"State": "Disabled"}, tags: ["!autodocs"] };
