// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Arrow } from './Arrow';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Arrow: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36391-398493", title: "Components/Elastic UI/Arrow [36391:398493]",
  component: Arrow, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36391:398493", exportName: "Arrow", docs: { description: { component: "Arrow — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36391-398493) · 1 вариантов." } } },
} satisfies Meta<typeof Arrow>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36391:398493" component={Arrow} storyId="ds-36391-398493"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
