// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SuperDatePickerDropdownFooter } from './SuperDatePickerDropdownFooter';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SuperDatePickerDropdownFooter: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-20307-328531", title: "Components/Elastic UI/.📦Super Date Picker  ·  Dropdown -> Footer [20307:328531]",
  component: SuperDatePickerDropdownFooter, tags: ['autodocs'],
  args: {"Disabled": "False"},
  argTypes: {"Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "20307:328531", exportName: "SuperDatePickerDropdownFooter", docs: { description: { component: ".📦Super Date Picker / Dropdown -> Footer — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=20307-328531) · 2 вариантов." } } },
} satisfies Meta<typeof SuperDatePickerDropdownFooter>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="20307:328531" component={SuperDatePickerDropdownFooter} storyId="ds-20307-328531"/> };
/** Disabled: False */
export const Variant001: Story = { name: "Disabled: False", args: {"Disabled": "False"}, tags: ["!autodocs"] };
/** Disabled: True */
export const Variant002: Story = { name: "Disabled: True", args: {"Disabled": "True"}, tags: ["!autodocs"] };
