// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Toast } from './Toast';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Toast: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13555-24644", title: "Components/Elastic UI/Toast [13555:24644]",
  component: Toast, tags: ['autodocs'],
  args: {"Type": "Default", "Icon": "False", "Button": "False"},
  argTypes: {"Type": {"control": "select", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Success", "Danger", "Warning", "Info"]}, "Icon": {"control": "inline-radio", "description": "Свойство Figma: Icon", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Button": {"control": "inline-radio", "description": "Свойство Figma: Button", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "title": {"control": "text", "description": "Заголовок уведомления"}},
  parameters: { layout: "padded", catalogId: "13555:24644", exportName: "Toast", docs: { description: { component: "&lt;EuiToast&gt;\n\nTry to keep toast content short. If more details need to be provided turn on the Button which should trigger a permanent overlay or navigate user to a page.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13555-24644) · 20 вариантов." } } },
} satisfies Meta<typeof Toast>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13555:24644" component={Toast} storyId="ds-13555-24644"/> };
/** Type: Danger · Icon: False · Button: False */
export const Variant001: Story = { name: "Type: Danger · Icon: False · Button: False", args: {"Type": "Danger", "Icon": "False", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Danger · Icon: False · Button: True */
export const Variant002: Story = { name: "Type: Danger · Icon: False · Button: True", args: {"Type": "Danger", "Icon": "False", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Danger · Icon: True · Button: False */
export const Variant003: Story = { name: "Type: Danger · Icon: True · Button: False", args: {"Type": "Danger", "Icon": "True", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Danger · Icon: True · Button: True */
export const Variant004: Story = { name: "Type: Danger · Icon: True · Button: True", args: {"Type": "Danger", "Icon": "True", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Warning · Icon: False · Button: False */
export const Variant005: Story = { name: "Type: Warning · Icon: False · Button: False", args: {"Type": "Warning", "Icon": "False", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Warning · Icon: False · Button: True */
export const Variant006: Story = { name: "Type: Warning · Icon: False · Button: True", args: {"Type": "Warning", "Icon": "False", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Warning · Icon: True · Button: False */
export const Variant007: Story = { name: "Type: Warning · Icon: True · Button: False", args: {"Type": "Warning", "Icon": "True", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Warning · Icon: True · Button: True */
export const Variant008: Story = { name: "Type: Warning · Icon: True · Button: True", args: {"Type": "Warning", "Icon": "True", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Success · Icon: False · Button: False */
export const Variant009: Story = { name: "Type: Success · Icon: False · Button: False", args: {"Type": "Success", "Icon": "False", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Success · Icon: False · Button: True */
export const Variant010: Story = { name: "Type: Success · Icon: False · Button: True", args: {"Type": "Success", "Icon": "False", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Success · Icon: True · Button: False */
export const Variant011: Story = { name: "Type: Success · Icon: True · Button: False", args: {"Type": "Success", "Icon": "True", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Success · Icon: True · Button: True */
export const Variant012: Story = { name: "Type: Success · Icon: True · Button: True", args: {"Type": "Success", "Icon": "True", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Info · Icon: False · Button: False */
export const Variant013: Story = { name: "Type: Info · Icon: False · Button: False", args: {"Type": "Info", "Icon": "False", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Info · Icon: False · Button: True */
export const Variant014: Story = { name: "Type: Info · Icon: False · Button: True", args: {"Type": "Info", "Icon": "False", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Info · Icon: True · Button: False */
export const Variant015: Story = { name: "Type: Info · Icon: True · Button: False", args: {"Type": "Info", "Icon": "True", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Info · Icon: True · Button: True */
export const Variant016: Story = { name: "Type: Info · Icon: True · Button: True", args: {"Type": "Info", "Icon": "True", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Default · Icon: False · Button: False */
export const Variant017: Story = { name: "Type: Default · Icon: False · Button: False", args: {"Type": "Default", "Icon": "False", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Default · Icon: False · Button: True */
export const Variant018: Story = { name: "Type: Default · Icon: False · Button: True", args: {"Type": "Default", "Icon": "False", "Button": "True"}, tags: ["!autodocs"] };
/** Type: Default · Icon: True · Button: False */
export const Variant019: Story = { name: "Type: Default · Icon: True · Button: False", args: {"Type": "Default", "Icon": "True", "Button": "False"}, tags: ["!autodocs"] };
/** Type: Default · Icon: True · Button: True */
export const Variant020: Story = { name: "Type: Default · Icon: True · Button: True", args: {"Type": "Default", "Icon": "True", "Button": "True"}, tags: ["!autodocs"] };
