// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ProductButton } from './ProductButton';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ProductButton: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-125-450", title: "Components/UX-Lab/ProductButton [125:450]",
  component: ProductButton, tags: ['autodocs'],
  args: {"Kind": "Primary", "State": "Default", "Size": "Small", "children": "Сохранить исследование"},
  argTypes: {"Kind": {"control": "inline-radio", "description": "Свойство Figma: Kind", "table": {"category": "Figma", "defaultValue": {"summary": "Primary"}}, "options": ["Primary", "Secondary", "Tertiary"]}, "State": {"control": "select", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Pressed", "Focus", "Disabled", "Loading"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Small"}}, "options": ["Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "icon": {"control": "text", "description": "Данные / обработчик компонента", "table": {"category": "React"}}, "iconRight": {"control": "text", "description": "Данные / обработчик компонента", "table": {"category": "React"}}},
  parameters: { layout: "padded", catalogId: "125:450", exportName: "ProductButton", docs: { description: { component: "ProductButton — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=125-450) · 18 вариантов." } } },
} satisfies Meta<typeof ProductButton>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="125:450" component={ProductButton} storyId="ds-125-450"/> };
/** Kind: Primary · State: Default · Size: Small */
export const Variant001: Story = { name: "Kind: Primary · State: Default · Size: Small", args: {"Kind": "Primary", "State": "Default", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Default · Size: Small */
export const Variant002: Story = { name: "Kind: Secondary · State: Default · Size: Small", args: {"Kind": "Secondary", "State": "Default", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Default · Size: Small */
export const Variant003: Story = { name: "Kind: Tertiary · State: Default · Size: Small", args: {"Kind": "Tertiary", "State": "Default", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Primary · State: Hover · Size: Small */
export const Variant004: Story = { name: "Kind: Primary · State: Hover · Size: Small", args: {"Kind": "Primary", "State": "Hover", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Hover · Size: Small */
export const Variant005: Story = { name: "Kind: Secondary · State: Hover · Size: Small", args: {"Kind": "Secondary", "State": "Hover", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Hover · Size: Small */
export const Variant006: Story = { name: "Kind: Tertiary · State: Hover · Size: Small", args: {"Kind": "Tertiary", "State": "Hover", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Primary · State: Pressed · Size: Small */
export const Variant007: Story = { name: "Kind: Primary · State: Pressed · Size: Small", args: {"Kind": "Primary", "State": "Pressed", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Pressed · Size: Small */
export const Variant008: Story = { name: "Kind: Secondary · State: Pressed · Size: Small", args: {"Kind": "Secondary", "State": "Pressed", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Pressed · Size: Small */
export const Variant009: Story = { name: "Kind: Tertiary · State: Pressed · Size: Small", args: {"Kind": "Tertiary", "State": "Pressed", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Primary · State: Focus · Size: Small */
export const Variant010: Story = { name: "Kind: Primary · State: Focus · Size: Small", args: {"Kind": "Primary", "State": "Focus", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Focus · Size: Small */
export const Variant011: Story = { name: "Kind: Secondary · State: Focus · Size: Small", args: {"Kind": "Secondary", "State": "Focus", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Focus · Size: Small */
export const Variant012: Story = { name: "Kind: Tertiary · State: Focus · Size: Small", args: {"Kind": "Tertiary", "State": "Focus", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Primary · State: Disabled · Size: Small */
export const Variant013: Story = { name: "Kind: Primary · State: Disabled · Size: Small", args: {"Kind": "Primary", "State": "Disabled", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Disabled · Size: Small */
export const Variant014: Story = { name: "Kind: Secondary · State: Disabled · Size: Small", args: {"Kind": "Secondary", "State": "Disabled", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Disabled · Size: Small */
export const Variant015: Story = { name: "Kind: Tertiary · State: Disabled · Size: Small", args: {"Kind": "Tertiary", "State": "Disabled", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Primary · State: Loading · Size: Small */
export const Variant016: Story = { name: "Kind: Primary · State: Loading · Size: Small", args: {"Kind": "Primary", "State": "Loading", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Secondary · State: Loading · Size: Small */
export const Variant017: Story = { name: "Kind: Secondary · State: Loading · Size: Small", args: {"Kind": "Secondary", "State": "Loading", "Size": "Small"}, tags: ["!autodocs"] };
/** Kind: Tertiary · State: Loading · Size: Small */
export const Variant018: Story = { name: "Kind: Tertiary · State: Loading · Size: Small", args: {"Kind": "Tertiary", "State": "Loading", "Size": "Small"}, tags: ["!autodocs"] };
