// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Switch } from './Switch';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Switch: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-37824-396069", title: "Components/Elastic UI/☠️ Switch [37824:396069]",
  component: Switch, tags: ['autodocs'],
  args: {"Show Label#37824:3": true, "Label#37824:4": "Label", "Checked": "True", "Compressed": "False", "Disabled": "False"},
  argTypes: {"Show Label#37824:3": {"control": "boolean", "description": "Свойство Figma: Show Label", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Label#37824:4": {"control": "text", "description": "Свойство Figma: Label", "table": {"category": "Figma", "defaultValue": {"summary": "Label"}}}, "Checked": {"control": "inline-radio", "description": "Свойство Figma: Checked", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "37824:396069", exportName: "Switch", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=37824-396069) · 8 вариантов." } } },
} satisfies Meta<typeof Switch>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="37824:396069" component={Switch} storyId="ds-37824-396069"/> };
/** Checked: True · Compressed: False · Disabled: False */
export const Variant001: Story = { name: "Checked: True · Compressed: False · Disabled: False", args: {"Checked": "True", "Compressed": "False", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: True · Compressed: False · Disabled: True */
export const Variant002: Story = { name: "Checked: True · Compressed: False · Disabled: True", args: {"Checked": "True", "Compressed": "False", "Disabled": "True"}, tags: ["!autodocs"] };
/** Checked: False · Compressed: False · Disabled: False */
export const Variant003: Story = { name: "Checked: False · Compressed: False · Disabled: False", args: {"Checked": "False", "Compressed": "False", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: False · Compressed: False · Disabled: True */
export const Variant004: Story = { name: "Checked: False · Compressed: False · Disabled: True", args: {"Checked": "False", "Compressed": "False", "Disabled": "True"}, tags: ["!autodocs"] };
/** Checked: True · Compressed: True · Disabled: False */
export const Variant005: Story = { name: "Checked: True · Compressed: True · Disabled: False", args: {"Checked": "True", "Compressed": "True", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: True · Compressed: True · Disabled: True */
export const Variant006: Story = { name: "Checked: True · Compressed: True · Disabled: True", args: {"Checked": "True", "Compressed": "True", "Disabled": "True"}, tags: ["!autodocs"] };
/** Checked: False · Compressed: True · Disabled: False */
export const Variant007: Story = { name: "Checked: False · Compressed: True · Disabled: False", args: {"Checked": "False", "Compressed": "True", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: False · Compressed: True · Disabled: True */
export const Variant008: Story = { name: "Checked: False · Compressed: True · Disabled: True", args: {"Checked": "False", "Compressed": "True", "Disabled": "True"}, tags: ["!autodocs"] };
