/** Shared source data for both Showcase.tsx and the Storybook Foundation section — one list, two consumers. */

export const PRIMITIVE_COLORS: { name: string; varName: string; group: string }[] = [
  { name: 'brand/primary', varName: '--brand-primary', group: 'Brand' },
  { name: 'brand/secondary', varName: '--brand-secondary', group: 'Brand' },
  { name: 'brand/tertiary', varName: '--brand-tertiary', group: 'Brand' },
  { name: 'neutral/white', varName: '--neutral-white', group: 'Neutral' },
  { name: 'neutral/25', varName: '--neutral-25', group: 'Neutral' },
  { name: 'neutral/50', varName: '--neutral-50', group: 'Neutral' },
  { name: 'neutral/150', varName: '--neutral-150', group: 'Neutral' },
  { name: 'neutral/200', varName: '--neutral-200', group: 'Neutral' },
  { name: 'neutral/300', varName: '--neutral-300', group: 'Neutral' },
  { name: 'neutral/400', varName: '--neutral-400', group: 'Neutral' },
  { name: 'neutral/500', varName: '--neutral-500', group: 'Neutral' },
  { name: 'neutral/600', varName: '--neutral-600', group: 'Neutral' },
  { name: 'neutral/800', varName: '--neutral-800', group: 'Neutral' },
  { name: 'neutral/850', varName: '--neutral-850', group: 'Neutral' },
  { name: 'neutral/900', varName: '--neutral-900', group: 'Neutral' },
  { name: 'neutral/background', varName: '--neutral-background', group: 'Neutral' },
  { name: 'neutral/footer', varName: '--neutral-footer', group: 'Neutral' },
  { name: 'system/error-100', varName: '--system-error-100', group: 'System' },
  { name: 'system/error-20', varName: '--system-error-20', group: 'System' },
  { name: 'system/success-100', varName: '--system-success-100', group: 'System' },
  { name: 'system/success-20', varName: '--system-success-20', group: 'System' },
  { name: 'system/notification-100', varName: '--system-notification-100', group: 'System' },
  { name: 'system/notification-20', varName: '--system-notification-20', group: 'System' },
  { name: 'extra/blue-100', varName: '--extra-blue-100', group: 'Extra' },
  { name: 'extra/blue-30', varName: '--extra-blue-30', group: 'Extra' },
  { name: 'extra/blue-10', varName: '--extra-blue-10', group: 'Extra' },
  { name: 'extra/purple-100', varName: '--extra-purple-100', group: 'Extra' },
  { name: 'extra/purple-30', varName: '--extra-purple-30', group: 'Extra' },
  { name: 'extra/purple-10', varName: '--extra-purple-10', group: 'Extra' },
  { name: 'extra/green-100', varName: '--extra-green-100', group: 'Extra' },
  { name: 'extra/green-30', varName: '--extra-green-30', group: 'Extra' },
  { name: 'extra/green-10', varName: '--extra-green-10', group: 'Extra' },
  { name: 'extra/pink-100', varName: '--extra-pink-100', group: 'Extra' },
  { name: 'extra/pink-30', varName: '--extra-pink-30', group: 'Extra' },
  { name: 'extra/pink-10', varName: '--extra-pink-10', group: 'Extra' },
  { name: 'extra/orange-100', varName: '--extra-orange-100', group: 'Extra' },
  { name: 'extra/orange-30', varName: '--extra-orange-30', group: 'Extra' },
  { name: 'extra/orange-10', varName: '--extra-orange-10', group: 'Extra' },
  { name: 'extra/yellow-100', varName: '--extra-yellow-100', group: 'Extra' },
  { name: 'extra/yellow-30', varName: '--extra-yellow-30', group: 'Extra' },
  { name: 'extra/yellow-10', varName: '--extra-yellow-10', group: 'Extra' },
  { name: 'extra/gray-30', varName: '--extra-gray-30', group: 'Extra' },
]

export const SEMANTIC_COLORS: { name: string; varName: string; aliasOf: string; group: string }[] = [
  { name: 'bg/page', varName: '--color-bg-page', aliasOf: 'neutral/background', group: 'Backgrounds' },
  { name: 'bg/surface-primary', varName: '--color-bg-surface-primary', aliasOf: 'neutral/white', group: 'Backgrounds' },
  { name: 'bg/surface-secondary', varName: '--color-bg-surface-secondary', aliasOf: 'neutral/800', group: 'Backgrounds' },
  { name: 'bg/disabled', varName: '--color-bg-disabled', aliasOf: 'neutral/150', group: 'Backgrounds' },
  { name: 'bg/footer', varName: '--color-bg-footer', aliasOf: 'neutral/footer', group: 'Backgrounds' },
  { name: 'bg/hover-subtle', varName: '--color-bg-hover-subtle', aliasOf: 'neutral/50', group: 'Backgrounds' },
  { name: 'text/primary', varName: '--color-text-primary', aliasOf: 'neutral/850', group: 'Text' },
  { name: 'text/secondary', varName: '--color-text-secondary', aliasOf: 'neutral/600', group: 'Text' },
  { name: 'text/icons', varName: '--color-text-icons', aliasOf: 'neutral/400', group: 'Text' },
  { name: 'text/link', varName: '--color-text-link', aliasOf: 'brand/tertiary', group: 'Text' },
  { name: 'text/on-disabled', varName: '--color-text-on-disabled', aliasOf: 'neutral/500', group: 'Text' },
  { name: 'text/on-dark', varName: '--color-text-on-dark', aliasOf: 'neutral/25', group: 'Text' },
  { name: 'text/on-button', varName: '--color-text-on-button', aliasOf: 'neutral/900', group: 'Text' },
  { name: 'border/default', varName: '--color-border-default', aliasOf: 'neutral/300', group: 'Borders' },
  { name: 'border/hover', varName: '--color-border-hover', aliasOf: 'neutral/500', group: 'Borders' },
  { name: 'border/error', varName: '--color-border-error', aliasOf: 'system/error-100', group: 'Borders' },
  { name: 'border/focus', varName: '--color-border-focus', aliasOf: 'brand/primary', group: 'Borders' },
  { name: 'brand/primary', varName: '--color-brand-primary', aliasOf: 'brand/primary', group: 'Brand' },
  { name: 'brand/secondary', varName: '--color-brand-secondary', aliasOf: 'brand/secondary', group: 'Brand' },
  { name: 'brand/tertiary', varName: '--color-brand-tertiary', aliasOf: 'brand/tertiary', group: 'Brand' },
  { name: 'system/error', varName: '--color-system-error', aliasOf: 'system/error-100', group: 'System' },
  { name: 'system/error-subtle', varName: '--color-system-error-subtle', aliasOf: 'system/error-20', group: 'System' },
  { name: 'system/success', varName: '--color-system-success', aliasOf: 'system/success-100', group: 'System' },
  { name: 'system/success-subtle', varName: '--color-system-success-subtle', aliasOf: 'system/success-20', group: 'System' },
  { name: 'system/notification', varName: '--color-system-notification', aliasOf: 'system/notification-100', group: 'System' },
  { name: 'system/notification-subtle', varName: '--color-system-notification-subtle', aliasOf: 'system/notification-20', group: 'System' },
  { name: 'generated/button-primary-hover', varName: '--color-generated-button-primary-hover', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'generated/button-primary-pressed', varName: '--color-generated-button-primary-pressed', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'generated/button-secondary-bg', varName: '--color-generated-button-secondary-bg', aliasOf: 'neutral/200', group: 'Generated' },
  { name: 'generated/button-secondary-hover', varName: '--color-generated-button-secondary-hover', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'generated/button-secondary-pressed', varName: '--color-generated-button-secondary-pressed', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'generated/toggle-on-hover', varName: '--color-generated-toggle-on-hover', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'generated/toggle-on-disabled', varName: '--color-generated-toggle-on-disabled', aliasOf: 'вычислено (не алиас)', group: 'Generated' },
  { name: 'overlay/scrim', varName: '--color-overlay-scrim', aliasOf: 'text/primary @ 50%', group: 'Overlay' },
]

export const TYPE_ROWS: { className: string; label: string }[] = [
  { className: 'ds-desktop-header-1-semibold', label: 'Desktop / Header 1 SemiBold — 24/36' },
  { className: 'ds-desktop-header-1-medium', label: 'Desktop / Header 1 Medium — 24/36' },
  { className: 'ds-desktop-header-1-regular', label: 'Desktop / Header 1 Regular — 24/36' },
  { className: 'ds-desktop-header-2-medium', label: 'Desktop / Header 2 Medium — 18/24' },
  { className: 'ds-desktop-menu-semibold', label: 'Desktop / Menu SemiBold — 18/24' },
  { className: 'ds-desktop-menu-regular', label: 'Desktop / Menu Regular — 18/24' },
  { className: 'ds-desktop-main-semibold', label: 'Desktop / Main SemiBold — 14/20' },
  { className: 'ds-desktop-main-medium', label: 'Desktop / Main Medium — 14/20' },
  { className: 'ds-desktop-main-regular', label: 'Desktop / Main Regular — 14/20' },
  { className: 'ds-desktop-regular-16', label: 'Desktop / Regular 16 — 16/20' },
  { className: 'ds-desktop-label-medium', label: 'Desktop / Label Medium — 12/16' },
  { className: 'ds-desktop-breadcrumbs-regular', label: 'Desktop / Breadcrumbs Regular — 12/16' },
  { className: 'ds-desktop-breadcrumbs-underline', label: 'Desktop / Breadcrumbs Underline — 12/16' },
  { className: 'ds-mobile-header-1-semibold', label: 'Mobile / Header 1 SemiBold — 24/32' },
  { className: 'ds-mobile-header-2-semibold', label: 'Mobile / Header 2 SemiBold — 16/24' },
  { className: 'ds-mobile-header-3-semibold', label: 'Mobile / Header 3 SemiBold — 14/20' },
  { className: 'ds-mobile-main-regular', label: 'Mobile / Main Regular — 14/20' },
  { className: 'ds-mobile-button-regular', label: 'Mobile / Button Regular — 14/24' },
]

export const SPACING_TOKENS: { name: string; varName: string; px: number }[] = [
  { name: 'spacing/xs', varName: '--space-xs', px: 4 },
  { name: 'spacing/sm', varName: '--space-sm', px: 8 },
  { name: 'spacing/md', varName: '--space-md', px: 12 },
  { name: 'spacing/lg', varName: '--space-lg', px: 16 },
  { name: 'spacing/xl', varName: '--space-xl', px: 24 },
  { name: 'spacing/2xl', varName: '--space-2xl', px: 32 },
]

export const RADIUS_TOKENS: { name: string; varName: string; px: number }[] = [
  { name: 'radius/sm', varName: '--radius-sm', px: 4 },
  { name: 'radius/focus', varName: '--radius-focus', px: 6 },
  { name: 'radius/full', varName: '--radius-full', px: 999 },
]

export const BORDER_WIDTH_TOKENS: { name: string; varName: string; px: number }[] = [
  { name: 'border-width/thin', varName: '--border-width-thin', px: 1 },
  { name: 'border-width/default', varName: '--border-width-default', px: 1.5 },
  { name: 'border-width/thick', varName: '--border-width-thick', px: 2 },
]

export const SHADOW_TOKENS: { name: string; varName: string }[] = [
  { name: 'shadow-sm', varName: '--shadow-sm' },
  { name: 'shadow-md', varName: '--shadow-md' },
  { name: 'shadow-lg', varName: '--shadow-lg' },
]
