// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Facet } from './Facet';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Facet: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13653-64632", title: "Components/Elastic UI/Facet [13653:64632]",
  component: Facet, tags: ['autodocs'],
  args: {"State": "Default", "Icon": "False", "Selected": "False", "Disabled": "False", "Loading": "False"},
  argTypes: {"State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Focus"]}, "Icon": {"control": "inline-radio", "description": "Свойство Figma: Icon", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "Selected": {"control": "inline-radio", "description": "Свойство Figma: Selected", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Loading": {"control": "inline-radio", "description": "Свойство Figma: Loading", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13653:64632", exportName: "Facet", docs: { description: { component: "&lt;EuiFacetButton&gt;\n\nFacets are a helpful way to list filters and their quantity, though you can hide the notification badge layer if you don&#39;t want to show quantity.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13653-64632) · 16 вариантов." } } },
} satisfies Meta<typeof Facet>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13653:64632" component={Facet} storyId="ds-13653-64632"/> };
/** State: Default · Icon: True · Selected: False · Disabled: False · Loading: False */
export const Variant001: Story = { name: "State: Default · Icon: True · Selected: False · Disabled: False · Loading: False", args: {"State": "Default", "Icon": "True", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Default · Icon: True · Selected: True · Disabled: False · Loading: False */
export const Variant002: Story = { name: "State: Default · Icon: True · Selected: True · Disabled: False · Loading: False", args: {"State": "Default", "Icon": "True", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Default · Icon: True · Selected: False · Disabled: True · Loading: True */
export const Variant003: Story = { name: "State: Default · Icon: True · Selected: False · Disabled: True · Loading: True", args: {"State": "Default", "Icon": "True", "Selected": "False", "Disabled": "True", "Loading": "True"}, tags: ["!autodocs"] };
/** State: Default · Icon: False · Selected: False · Disabled: True · Loading: True */
export const Variant004: Story = { name: "State: Default · Icon: False · Selected: False · Disabled: True · Loading: True", args: {"State": "Default", "Icon": "False", "Selected": "False", "Disabled": "True", "Loading": "True"}, tags: ["!autodocs"] };
/** State: Default · Icon: True · Selected: False · Disabled: True · Loading: False */
export const Variant005: Story = { name: "State: Default · Icon: True · Selected: False · Disabled: True · Loading: False", args: {"State": "Default", "Icon": "True", "Selected": "False", "Disabled": "True", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Default · Icon: False · Selected: False · Disabled: True · Loading: False */
export const Variant006: Story = { name: "State: Default · Icon: False · Selected: False · Disabled: True · Loading: False", args: {"State": "Default", "Icon": "False", "Selected": "False", "Disabled": "True", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Default · Icon: False · Selected: False · Disabled: False · Loading: False */
export const Variant007: Story = { name: "State: Default · Icon: False · Selected: False · Disabled: False · Loading: False", args: {"State": "Default", "Icon": "False", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Default · Icon: False · Selected: True · Disabled: False · Loading: False */
export const Variant008: Story = { name: "State: Default · Icon: False · Selected: True · Disabled: False · Loading: False", args: {"State": "Default", "Icon": "False", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Hover · Icon: True · Selected: False · Disabled: False · Loading: False */
export const Variant009: Story = { name: "State: Hover · Icon: True · Selected: False · Disabled: False · Loading: False", args: {"State": "Hover", "Icon": "True", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Hover · Icon: True · Selected: True · Disabled: False · Loading: False */
export const Variant010: Story = { name: "State: Hover · Icon: True · Selected: True · Disabled: False · Loading: False", args: {"State": "Hover", "Icon": "True", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Hover · Icon: False · Selected: False · Disabled: False · Loading: False */
export const Variant011: Story = { name: "State: Hover · Icon: False · Selected: False · Disabled: False · Loading: False", args: {"State": "Hover", "Icon": "False", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Hover · Icon: False · Selected: True · Disabled: False · Loading: False */
export const Variant012: Story = { name: "State: Hover · Icon: False · Selected: True · Disabled: False · Loading: False", args: {"State": "Hover", "Icon": "False", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Focus · Icon: True · Selected: False · Disabled: False · Loading: False */
export const Variant013: Story = { name: "State: Focus · Icon: True · Selected: False · Disabled: False · Loading: False", args: {"State": "Focus", "Icon": "True", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Focus · Icon: True · Selected: True · Disabled: False · Loading: False */
export const Variant014: Story = { name: "State: Focus · Icon: True · Selected: True · Disabled: False · Loading: False", args: {"State": "Focus", "Icon": "True", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Focus · Icon: False · Selected: False · Disabled: False · Loading: False */
export const Variant015: Story = { name: "State: Focus · Icon: False · Selected: False · Disabled: False · Loading: False", args: {"State": "Focus", "Icon": "False", "Selected": "False", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
/** State: Focus · Icon: False · Selected: True · Disabled: False · Loading: False */
export const Variant016: Story = { name: "State: Focus · Icon: False · Selected: True · Disabled: False · Loading: False", args: {"State": "Focus", "Icon": "False", "Selected": "True", "Disabled": "False", "Loading": "False"}, tags: ["!autodocs"] };
