// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DescribedFormGroup } from './DescribedFormGroup';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DescribedFormGroup: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-27008-287534", title: "Components/Elastic UI/☠️ Described Form Group [27008:287534]",
  component: DescribedFormGroup, tags: ['autodocs'],
  args: {"Ratio": "Half*"},
  argTypes: {"Ratio": {"control": "inline-radio", "description": "Свойство Figma: Ratio", "table": {"category": "Figma", "defaultValue": {"summary": "Half*"}}, "options": ["Half*", "Third", "Quarter"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "27008:287534", exportName: "DescribedFormGroup", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=27008-287534) · 3 вариантов." } } },
} satisfies Meta<typeof DescribedFormGroup>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="27008:287534" component={DescribedFormGroup} storyId="ds-27008-287534"/> };
/** Ratio: Half* */
export const Variant001: Story = { name: "Ratio: Half*", args: {"Ratio": "Half*"}, tags: ["!autodocs"] };
/** Ratio: Third */
export const Variant002: Story = { name: "Ratio: Third", args: {"Ratio": "Third"}, tags: ["!autodocs"] };
/** Ratio: Quarter */
export const Variant003: Story = { name: "Ratio: Quarter", args: {"Ratio": "Quarter"}, tags: ["!autodocs"] };
