// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DataGridPopover } from './DataGridPopover';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DataGridPopover: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-46305-10412", title: "Components/Elastic UI/Data Grid Popover [46305:10412]",
  component: DataGridPopover, tags: ['autodocs'],
  args: {"Content": "Display Options"},
  argTypes: {"Content": {"control": "inline-radio", "description": "Свойство Figma: Content", "table": {"category": "Figma", "defaultValue": {"summary": "Display Options"}}, "options": ["Display Options", "Columns", "Sorting", "Keyboard shortcuts"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "46305:10412", exportName: "DataGridPopover", docs: { description: { component: "Data Grid Popover — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=46305-10412) · 4 вариантов." } } },
} satisfies Meta<typeof DataGridPopover>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="46305:10412" component={DataGridPopover} storyId="ds-46305-10412"/> };
/** Content: Keyboard shortcuts */
export const Variant001: Story = { name: "Content: Keyboard shortcuts", args: {"Content": "Keyboard shortcuts"}, tags: ["!autodocs"] };
/** Content: Display Options */
export const Variant002: Story = { name: "Content: Display Options", args: {"Content": "Display Options"}, tags: ["!autodocs"] };
/** Content: Sorting */
export const Variant003: Story = { name: "Content: Sorting", args: {"Content": "Sorting"}, tags: ["!autodocs"] };
/** Content: Columns */
export const Variant004: Story = { name: "Content: Columns", args: {"Content": "Columns"}, tags: ["!autodocs"] };
