// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FooterNode25126_282385 } from './FooterNode25126_282385';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FooterNode25126_282385: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-25126-282385", title: "Components/Elastic UI/.📦Footer [25126:282385]",
  component: FooterNode25126_282385, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "25126:282385", exportName: "FooterNode25126_282385", docs: { description: { component: ".📦Footer — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=25126-282385) · 1 вариантов." } } },
} satisfies Meta<typeof FooterNode25126_282385>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="25126:282385" component={FooterNode25126_282385} storyId="ds-25126-282385"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
