// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { LayoutThumbnail } from './LayoutThumbnail';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** LayoutThumbnail: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-22907-283773", title: "Components/Elastic UI/.📦Layout thumbnail [22907:283773]",
  component: LayoutThumbnail, tags: ['autodocs'],
  args: {"Type": "Sidebar", "State": "Default"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Sidebar"}}, "options": ["Sidebar", "Empty", "Multiple"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Selected"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "22907:283773", exportName: "LayoutThumbnail", docs: { description: { component: ".📦Layout thumbnail — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=22907-283773) · 6 вариантов." } } },
} satisfies Meta<typeof LayoutThumbnail>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="22907:283773" component={LayoutThumbnail} storyId="ds-22907-283773"/> };
/** Type: Sidebar · State: Default */
export const Variant001: Story = { name: "Type: Sidebar · State: Default", args: {"Type": "Sidebar", "State": "Default"}, tags: ["!autodocs"] };
/** Type: Multiple · State: Default */
export const Variant002: Story = { name: "Type: Multiple · State: Default", args: {"Type": "Multiple", "State": "Default"}, tags: ["!autodocs"] };
/** Type: Sidebar · State: Selected */
export const Variant003: Story = { name: "Type: Sidebar · State: Selected", args: {"Type": "Sidebar", "State": "Selected"}, tags: ["!autodocs"] };
/** Type: Multiple · State: Selected */
export const Variant004: Story = { name: "Type: Multiple · State: Selected", args: {"Type": "Multiple", "State": "Selected"}, tags: ["!autodocs"] };
/** Type: Empty · State: Default */
export const Variant005: Story = { name: "Type: Empty · State: Default", args: {"Type": "Empty", "State": "Default"}, tags: ["!autodocs"] };
/** Type: Empty · State: Selected */
export const Variant006: Story = { name: "Type: Empty · State: Selected", args: {"Type": "Empty", "State": "Selected"}, tags: ["!autodocs"] };
