// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AvatarGroupList } from './AvatarGroupList';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** AvatarGroupList: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-26769-282323", title: "Components/Elastic UI/💡 Avatar Group List [26769:282323]",
  component: AvatarGroupList, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "26769:282323", exportName: "AvatarGroupList", docs: { description: { component: "Uses &lt;EuiSelectable&gt;\n\nExample of using Selectable List to display a list Spaces. This list should max out and scroll before it gets too long.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=26769-282323) · 1 вариантов." } } },
} satisfies Meta<typeof AvatarGroupList>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="26769:282323" component={AvatarGroupList} storyId="ds-26769-282323"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
