// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Progress } from './Progress';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Progress: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13648-4438", title: "Components/Elastic UI/Progress [13648:4438]",
  component: Progress, tags: ['autodocs'],
  args: {"Size": "Medium* - 8px", "Color": "Success*", "Label": "False"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium* - 8px"}}, "options": ["X-Small - 2px", "Small - 4px", "Medium* - 8px", "Large - 16px"]}, "Color": {"control": "select", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Success*"}}, "options": ["Success*", "Primary", "Warning", "Danger", "Subdued", "Accent"]}, "Label": {"control": "inline-radio", "description": "Свойство Figma: Label", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13648:4438", exportName: "Progress", docs: { description: { component: "&lt;EuiProgress&gt;\n\nThe progress bar uses a text layer. Edit the invisible text to change the size of inner bar.\n\nYou can also swap any of the bar colors for a Viz or custom color. Just be sure to match that to the value text with the &quot;Text&quot; variant.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13648-4438) · 48 вариантов." } } },
} satisfies Meta<typeof Progress>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13648:4438" component={Progress} storyId="ds-13648-4438"/> };
/** Size: Large - 16px · Color: Accent · Label: False */
export const Variant001: Story = { name: "Size: Large - 16px · Color: Accent · Label: False", args: {"Size": "Large - 16px", "Color": "Accent", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Accent · Label: True */
export const Variant002: Story = { name: "Size: Large - 16px · Color: Accent · Label: True", args: {"Size": "Large - 16px", "Color": "Accent", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Subdued · Label: False */
export const Variant003: Story = { name: "Size: Large - 16px · Color: Subdued · Label: False", args: {"Size": "Large - 16px", "Color": "Subdued", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Subdued · Label: True */
export const Variant004: Story = { name: "Size: Large - 16px · Color: Subdued · Label: True", args: {"Size": "Large - 16px", "Color": "Subdued", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Danger · Label: False */
export const Variant005: Story = { name: "Size: Large - 16px · Color: Danger · Label: False", args: {"Size": "Large - 16px", "Color": "Danger", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Danger · Label: True */
export const Variant006: Story = { name: "Size: Large - 16px · Color: Danger · Label: True", args: {"Size": "Large - 16px", "Color": "Danger", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Warning · Label: False */
export const Variant007: Story = { name: "Size: Large - 16px · Color: Warning · Label: False", args: {"Size": "Large - 16px", "Color": "Warning", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Warning · Label: True */
export const Variant008: Story = { name: "Size: Large - 16px · Color: Warning · Label: True", args: {"Size": "Large - 16px", "Color": "Warning", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Primary · Label: False */
export const Variant009: Story = { name: "Size: Large - 16px · Color: Primary · Label: False", args: {"Size": "Large - 16px", "Color": "Primary", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Primary · Label: True */
export const Variant010: Story = { name: "Size: Large - 16px · Color: Primary · Label: True", args: {"Size": "Large - 16px", "Color": "Primary", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Success* · Label: False */
export const Variant011: Story = { name: "Size: Large - 16px · Color: Success* · Label: False", args: {"Size": "Large - 16px", "Color": "Success*", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Large - 16px · Color: Success* · Label: True */
export const Variant012: Story = { name: "Size: Large - 16px · Color: Success* · Label: True", args: {"Size": "Large - 16px", "Color": "Success*", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Accent · Label: False */
export const Variant013: Story = { name: "Size: Medium* - 8px · Color: Accent · Label: False", args: {"Size": "Medium* - 8px", "Color": "Accent", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Accent · Label: True */
export const Variant014: Story = { name: "Size: Medium* - 8px · Color: Accent · Label: True", args: {"Size": "Medium* - 8px", "Color": "Accent", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Success* · Label: False */
export const Variant015: Story = { name: "Size: Small - 4px · Color: Success* · Label: False", args: {"Size": "Small - 4px", "Color": "Success*", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Success* · Label: True */
export const Variant016: Story = { name: "Size: Small - 4px · Color: Success* · Label: True", args: {"Size": "Small - 4px", "Color": "Success*", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Subdued · Label: False */
export const Variant017: Story = { name: "Size: Medium* - 8px · Color: Subdued · Label: False", args: {"Size": "Medium* - 8px", "Color": "Subdued", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Subdued · Label: True */
export const Variant018: Story = { name: "Size: Medium* - 8px · Color: Subdued · Label: True", args: {"Size": "Medium* - 8px", "Color": "Subdued", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Danger · Label: False */
export const Variant019: Story = { name: "Size: Medium* - 8px · Color: Danger · Label: False", args: {"Size": "Medium* - 8px", "Color": "Danger", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Danger · Label: True */
export const Variant020: Story = { name: "Size: Medium* - 8px · Color: Danger · Label: True", args: {"Size": "Medium* - 8px", "Color": "Danger", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Warning · Label: False */
export const Variant021: Story = { name: "Size: Medium* - 8px · Color: Warning · Label: False", args: {"Size": "Medium* - 8px", "Color": "Warning", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Warning · Label: True */
export const Variant022: Story = { name: "Size: Medium* - 8px · Color: Warning · Label: True", args: {"Size": "Medium* - 8px", "Color": "Warning", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Primary · Label: False */
export const Variant023: Story = { name: "Size: Medium* - 8px · Color: Primary · Label: False", args: {"Size": "Medium* - 8px", "Color": "Primary", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Primary · Label: True */
export const Variant024: Story = { name: "Size: Medium* - 8px · Color: Primary · Label: True", args: {"Size": "Medium* - 8px", "Color": "Primary", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Success* · Label: False */
export const Variant025: Story = { name: "Size: X-Small - 2px · Color: Success* · Label: False", args: {"Size": "X-Small - 2px", "Color": "Success*", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Success* · Label: True */
export const Variant026: Story = { name: "Size: X-Small - 2px · Color: Success* · Label: True", args: {"Size": "X-Small - 2px", "Color": "Success*", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Accent · Label: False */
export const Variant027: Story = { name: "Size: Small - 4px · Color: Accent · Label: False", args: {"Size": "Small - 4px", "Color": "Accent", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Accent · Label: True */
export const Variant028: Story = { name: "Size: Small - 4px · Color: Accent · Label: True", args: {"Size": "Small - 4px", "Color": "Accent", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Subdued · Label: False */
export const Variant029: Story = { name: "Size: Small - 4px · Color: Subdued · Label: False", args: {"Size": "Small - 4px", "Color": "Subdued", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Subdued · Label: True */
export const Variant030: Story = { name: "Size: Small - 4px · Color: Subdued · Label: True", args: {"Size": "Small - 4px", "Color": "Subdued", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Danger · Label: False */
export const Variant031: Story = { name: "Size: Small - 4px · Color: Danger · Label: False", args: {"Size": "Small - 4px", "Color": "Danger", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Danger · Label: True */
export const Variant032: Story = { name: "Size: Small - 4px · Color: Danger · Label: True", args: {"Size": "Small - 4px", "Color": "Danger", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Warning · Label: False */
export const Variant033: Story = { name: "Size: Small - 4px · Color: Warning · Label: False", args: {"Size": "Small - 4px", "Color": "Warning", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Warning · Label: True */
export const Variant034: Story = { name: "Size: Small - 4px · Color: Warning · Label: True", args: {"Size": "Small - 4px", "Color": "Warning", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Primary · Label: False */
export const Variant035: Story = { name: "Size: Small - 4px · Color: Primary · Label: False", args: {"Size": "Small - 4px", "Color": "Primary", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Small - 4px · Color: Primary · Label: True */
export const Variant036: Story = { name: "Size: Small - 4px · Color: Primary · Label: True", args: {"Size": "Small - 4px", "Color": "Primary", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Accent · Label: False */
export const Variant037: Story = { name: "Size: X-Small - 2px · Color: Accent · Label: False", args: {"Size": "X-Small - 2px", "Color": "Accent", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Accent · Label: True */
export const Variant038: Story = { name: "Size: X-Small - 2px · Color: Accent · Label: True", args: {"Size": "X-Small - 2px", "Color": "Accent", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Subdued · Label: False */
export const Variant039: Story = { name: "Size: X-Small - 2px · Color: Subdued · Label: False", args: {"Size": "X-Small - 2px", "Color": "Subdued", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Subdued · Label: True */
export const Variant040: Story = { name: "Size: X-Small - 2px · Color: Subdued · Label: True", args: {"Size": "X-Small - 2px", "Color": "Subdued", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Danger · Label: False */
export const Variant041: Story = { name: "Size: X-Small - 2px · Color: Danger · Label: False", args: {"Size": "X-Small - 2px", "Color": "Danger", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Danger · Label: True */
export const Variant042: Story = { name: "Size: X-Small - 2px · Color: Danger · Label: True", args: {"Size": "X-Small - 2px", "Color": "Danger", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Warning · Label: False */
export const Variant043: Story = { name: "Size: X-Small - 2px · Color: Warning · Label: False", args: {"Size": "X-Small - 2px", "Color": "Warning", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Warning · Label: True */
export const Variant044: Story = { name: "Size: X-Small - 2px · Color: Warning · Label: True", args: {"Size": "X-Small - 2px", "Color": "Warning", "Label": "True"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Primary · Label: False */
export const Variant045: Story = { name: "Size: X-Small - 2px · Color: Primary · Label: False", args: {"Size": "X-Small - 2px", "Color": "Primary", "Label": "False"}, tags: ["!autodocs"] };
/** Size: X-Small - 2px · Color: Primary · Label: True */
export const Variant046: Story = { name: "Size: X-Small - 2px · Color: Primary · Label: True", args: {"Size": "X-Small - 2px", "Color": "Primary", "Label": "True"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Success* · Label: False */
export const Variant047: Story = { name: "Size: Medium* - 8px · Color: Success* · Label: False", args: {"Size": "Medium* - 8px", "Color": "Success*", "Label": "False"}, tags: ["!autodocs"] };
/** Size: Medium* - 8px · Color: Success* · Label: True */
export const Variant048: Story = { name: "Size: Medium* - 8px · Color: Success* · Label: True", args: {"Size": "Medium* - 8px", "Color": "Success*", "Label": "True"}, tags: ["!autodocs"] };
