// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Title } from './Title';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Title: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36238-395217", title: "Components/Elastic UI/Title [36238:395217]",
  component: Title, tags: ['autodocs'],
  args: {"Title size": "Small (default)"},
  argTypes: {"Title size": {"control": "inline-radio", "description": "Свойство Figma: Title size", "table": {"category": "Figma", "defaultValue": {"summary": "Small (default)"}}, "options": ["Small (default)", "XSmall"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36238:395217", exportName: "Title", docs: { description: { component: "Title — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36238-395217) · 2 вариантов." } } },
} satisfies Meta<typeof Title>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36238:395217" component={Title} storyId="ds-36238-395217"/> };
/** Title size: Small (default) */
export const Variant001: Story = { name: "Title size: Small (default)", args: {"Title size": "Small (default)"}, tags: ["!autodocs"] };
/** Title size: XSmall */
export const Variant002: Story = { name: "Title size: XSmall", args: {"Title size": "XSmall"}, tags: ["!autodocs"] };
