// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Breadcrumb } from './Breadcrumb';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Breadcrumb: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-42289-81", title: "Components/Elastic UI/.Breadcrumb [42289:81]",
  component: Breadcrumb, tags: ['autodocs'],
  args: {"Divider#42289:1": true, "Truncated": "False", "Interactive": "False", "Hover": "False"},
  argTypes: {"Divider#42289:1": {"control": "boolean", "description": "Свойство Figma: Divider", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Truncated": {"control": "inline-radio", "description": "Свойство Figma: Truncated", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "Interactive": {"control": "inline-radio", "description": "Свойство Figma: Interactive", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Hover": {"control": "inline-radio", "description": "Свойство Figma: Hover", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "42289:81", exportName: "Breadcrumb", docs: { description: { component: ".Breadcrumb — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=42289-81) · 5 вариантов." } } },
} satisfies Meta<typeof Breadcrumb>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="42289:81" component={Breadcrumb} storyId="ds-42289-81"/> };
/** Truncated: False · Interactive: True · Hover: False */
export const Variant001: Story = { name: "Truncated: False · Interactive: True · Hover: False", args: {"Truncated": "False", "Interactive": "True", "Hover": "False"}, tags: ["!autodocs"] };
/** Truncated: False · Interactive: True · Hover: True */
export const Variant002: Story = { name: "Truncated: False · Interactive: True · Hover: True", args: {"Truncated": "False", "Interactive": "True", "Hover": "True"}, tags: ["!autodocs"] };
/** Truncated: False · Interactive: False · Hover: False */
export const Variant003: Story = { name: "Truncated: False · Interactive: False · Hover: False", args: {"Truncated": "False", "Interactive": "False", "Hover": "False"}, tags: ["!autodocs"] };
/** Truncated: True · Interactive: True · Hover: False */
export const Variant004: Story = { name: "Truncated: True · Interactive: True · Hover: False", args: {"Truncated": "True", "Interactive": "True", "Hover": "False"}, tags: ["!autodocs"] };
/** Truncated: True · Interactive: True · Hover: True */
export const Variant005: Story = { name: "Truncated: True · Interactive: True · Hover: True", args: {"Truncated": "True", "Interactive": "True", "Hover": "True"}, tags: ["!autodocs"] };
