// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { PaginationRowsPerPage } from './PaginationRowsPerPage';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** PaginationRowsPerPage: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-22524-279617", title: "Components/Elastic UI/💡Pagination  ·  Rows per page [22524:279617]",
  component: PaginationRowsPerPage, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "22524:279617", exportName: "PaginationRowsPerPage", docs: { description: { component: "💡Pagination / Rows per page — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=22524-279617) · 1 вариантов." } } },
} satisfies Meta<typeof PaginationRowsPerPage>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="22524:279617" component={PaginationRowsPerPage} storyId="ds-22524-279617"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
