// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ListGroupItem } from './ListGroupItem';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ListGroupItem: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15132-116102", title: "Components/Elastic UI/List Group Item [15132:116102]",
  component: ListGroupItem, tags: ['autodocs'],
  args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Default"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "X-Small"]}, "Color": {"control": "inline-radio", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Primary", "Subdued"]}, "Icon": {"control": "inline-radio", "description": "Свойство Figma: Icon", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "Extra action": {"control": "inline-radio", "description": "Свойство Figma: Extra action", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Active", "Hover", "Disabled"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15132:116102", exportName: "ListGroupItem", docs: { description: { component: "&lt;EuiListGroupItem&gt;\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15132-116102) · 144 вариантов." } } },
} satisfies Meta<typeof ListGroupItem>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15132:116102" component={ListGroupItem} storyId="ds-15132-116102"/> };
/** Size: Medium · Color: Default · Icon: False · Extra action: False · State: Default */
export const Variant001: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Default */
export const Variant002: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Default */
export const Variant003: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: False · State: Active */
export const Variant004: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Active */
export const Variant005: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Active */
export const Variant006: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: False · State: Hover */
export const Variant007: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Hover */
export const Variant008: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Hover */
export const Variant009: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: False · State: Disabled */
export const Variant010: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Disabled */
export const Variant011: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Disabled */
export const Variant012: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: False · State: Default */
export const Variant013: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Default */
export const Variant014: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Default */
export const Variant015: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Default", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: False · State: Active */
export const Variant016: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Active */
export const Variant017: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Active */
export const Variant018: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Active", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: False · State: Hover */
export const Variant019: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Hover */
export const Variant020: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Hover */
export const Variant021: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Hover", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: False · State: Disabled */
export const Variant022: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Disabled */
export const Variant023: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Disabled */
export const Variant024: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: True · State: Default */
export const Variant025: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Default */
export const Variant026: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Default */
export const Variant027: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: True · State: Active */
export const Variant028: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Active */
export const Variant029: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Active */
export const Variant030: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: True · State: Hover */
export const Variant031: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Hover */
export const Variant032: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Hover */
export const Variant033: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: False · Extra action: True · State: Disabled */
export const Variant034: Story = { name: "Size: Medium · Color: Default · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Disabled */
export const Variant035: Story = { name: "Size: Medium · Color: Primary · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Disabled */
export const Variant036: Story = { name: "Size: Medium · Color: Subdued · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: True · State: Default */
export const Variant037: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Default */
export const Variant038: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Default */
export const Variant039: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Default", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: True · State: Active */
export const Variant040: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Active */
export const Variant041: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Active */
export const Variant042: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Active", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: True · State: Hover */
export const Variant043: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Hover */
export const Variant044: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Hover */
export const Variant045: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Hover", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Default · Icon: True · Extra action: True · State: Disabled */
export const Variant046: Story = { name: "Size: Medium · Color: Default · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Disabled */
export const Variant047: Story = { name: "Size: Medium · Color: Primary · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Disabled */
export const Variant048: Story = { name: "Size: Medium · Color: Subdued · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Medium", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: False · State: Default */
export const Variant049: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: False · State: Default */
export const Variant050: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Default */
export const Variant051: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: False · State: Active */
export const Variant052: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: False · State: Active */
export const Variant053: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Active */
export const Variant054: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: False · State: Hover */
export const Variant055: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: False · State: Hover */
export const Variant056: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Hover */
export const Variant057: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: False · State: Disabled */
export const Variant058: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: False · State: Disabled */
export const Variant059: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Disabled */
export const Variant060: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: False · State: Default */
export const Variant061: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: False · State: Default */
export const Variant062: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Default */
export const Variant063: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Default", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: False · State: Active */
export const Variant064: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: False · State: Active */
export const Variant065: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Active */
export const Variant066: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Active", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: False · State: Hover */
export const Variant067: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: False · State: Hover */
export const Variant068: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Hover */
export const Variant069: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Hover", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: False · State: Disabled */
export const Variant070: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: False · State: Disabled */
export const Variant071: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Disabled */
export const Variant072: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: False · State: Disabled", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: True · State: Default */
export const Variant073: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: True · State: Default */
export const Variant074: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Default */
export const Variant075: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: True · State: Active */
export const Variant076: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: True · State: Active */
export const Variant077: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Active */
export const Variant078: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: True · State: Hover */
export const Variant079: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: True · State: Hover */
export const Variant080: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Hover */
export const Variant081: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: False · Extra action: True · State: Disabled */
export const Variant082: Story = { name: "Size: Small · Color: Default · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: False · Extra action: True · State: Disabled */
export const Variant083: Story = { name: "Size: Small · Color: Primary · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Disabled */
export const Variant084: Story = { name: "Size: Small · Color: Subdued · Icon: False · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: True · State: Default */
export const Variant085: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: True · State: Default */
export const Variant086: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Default */
export const Variant087: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Default", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: True · State: Active */
export const Variant088: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: True · State: Active */
export const Variant089: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Active */
export const Variant090: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Active", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: True · State: Hover */
export const Variant091: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: True · State: Hover */
export const Variant092: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Hover */
export const Variant093: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Hover", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: Small · Color: Default · Icon: True · Extra action: True · State: Disabled */
export const Variant094: Story = { name: "Size: Small · Color: Default · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Primary · Icon: True · Extra action: True · State: Disabled */
export const Variant095: Story = { name: "Size: Small · Color: Primary · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Disabled */
export const Variant096: Story = { name: "Size: Small · Color: Subdued · Icon: True · Extra action: True · State: Disabled", args: {"Size": "Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Default */
export const Variant097: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Default */
export const Variant098: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Default */
export const Variant099: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Active */
export const Variant100: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Active */
export const Variant101: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Active */
export const Variant102: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Hover */
export const Variant103: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Hover */
export const Variant104: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Hover */
export const Variant105: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Disabled */
export const Variant106: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Disabled */
export const Variant107: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Disabled */
export const Variant108: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Default */
export const Variant109: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Default */
export const Variant110: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Default */
export const Variant111: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Default", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Active */
export const Variant112: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Active */
export const Variant113: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Active */
export const Variant114: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Active", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Hover */
export const Variant115: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Hover */
export const Variant116: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Hover */
export const Variant117: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Hover", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Disabled */
export const Variant118: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Disabled */
export const Variant119: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Disabled */
export const Variant120: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: False · State: Disabled", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "False", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Default */
export const Variant121: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Default */
export const Variant122: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Default */
export const Variant123: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Active */
export const Variant124: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Active */
export const Variant125: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Active */
export const Variant126: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Hover */
export const Variant127: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Hover */
export const Variant128: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Hover */
export const Variant129: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Disabled */
export const Variant130: Story = { name: "Size: X-Small · Color: Default · Icon: False · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Default", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Disabled */
export const Variant131: Story = { name: "Size: X-Small · Color: Primary · Icon: False · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Primary", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Disabled */
export const Variant132: Story = { name: "Size: X-Small · Color: Subdued · Icon: False · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "False", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Default */
export const Variant133: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Default */
export const Variant134: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Default */
export const Variant135: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Default", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Active */
export const Variant136: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Active */
export const Variant137: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Active */
export const Variant138: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Active", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Active"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Hover */
export const Variant139: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Hover */
export const Variant140: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Hover */
export const Variant141: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Hover", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Disabled */
export const Variant142: Story = { name: "Size: X-Small · Color: Default · Icon: True · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Default", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Disabled */
export const Variant143: Story = { name: "Size: X-Small · Color: Primary · Icon: True · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Primary", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
/** Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Disabled */
export const Variant144: Story = { name: "Size: X-Small · Color: Subdued · Icon: True · Extra action: True · State: Disabled", args: {"Size": "X-Small", "Color": "Subdued", "Icon": "True", "Extra action": "True", "State": "Disabled"}, tags: ["!autodocs"] };
