// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CollapsibleNavWithOverlay } from './CollapsibleNavWithOverlay';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** CollapsibleNavWithOverlay: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15213-169", title: "Components/Elastic UI/Collapsible Nav - With overlay [15213:169]",
  component: CollapsibleNavWithOverlay, tags: ['autodocs'],
  args: {},
  argTypes: {"children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15213:169", exportName: "CollapsibleNavWithOverlay", docs: { description: { component: "&lt;EuiCollapsibleNav&gt;\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15213-169) · 1 вариантов." } } },
} satisfies Meta<typeof CollapsibleNavWithOverlay>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15213:169" component={CollapsibleNavWithOverlay} storyId="ds-15213-169"/> };
/** Одиночный компонент */
export const Variant001: Story = { name: "Одиночный компонент", args: {}, tags: ["!autodocs"] };
