// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { StepIndicator } from './StepIndicator';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** StepIndicator: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14775-90261", title: "Components/Elastic UI/.📦 Step  ·  Indicator [14775:90261]",
  component: StepIndicator, tags: ['autodocs'],
  args: {"Status": "default", "Size": "Small/Medium"},
  argTypes: {"Status": {"control": "select", "description": "Свойство Figma: Status", "table": {"category": "Figma", "defaultValue": {"summary": "default"}}, "options": ["default", "complete", "incomplete", "disabled", "loading", "warning", "danger", "current"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Small/Medium"}}, "options": ["Small/Medium", "XSmall", "XXSmall"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14775:90261", exportName: "StepIndicator", docs: { description: { component: ".📦 Step / Indicator — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14775-90261) · 24 вариантов." } } },
} satisfies Meta<typeof StepIndicator>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14775:90261" component={StepIndicator} storyId="ds-14775-90261"/> };
/** Status: default · Size: Small/Medium */
export const Variant001: Story = { name: "Status: default · Size: Small/Medium", args: {"Status": "default", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: default · Size: XSmall */
export const Variant002: Story = { name: "Status: default · Size: XSmall", args: {"Status": "default", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: default · Size: XXSmall */
export const Variant003: Story = { name: "Status: default · Size: XXSmall", args: {"Status": "default", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: current · Size: Small/Medium */
export const Variant004: Story = { name: "Status: current · Size: Small/Medium", args: {"Status": "current", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: current · Size: XSmall */
export const Variant005: Story = { name: "Status: current · Size: XSmall", args: {"Status": "current", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: current · Size: XXSmall */
export const Variant006: Story = { name: "Status: current · Size: XXSmall", args: {"Status": "current", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: incomplete · Size: Small/Medium */
export const Variant007: Story = { name: "Status: incomplete · Size: Small/Medium", args: {"Status": "incomplete", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: incomplete · Size: XSmall */
export const Variant008: Story = { name: "Status: incomplete · Size: XSmall", args: {"Status": "incomplete", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: incomplete · Size: XXSmall */
export const Variant009: Story = { name: "Status: incomplete · Size: XXSmall", args: {"Status": "incomplete", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: loading · Size: Small/Medium */
export const Variant010: Story = { name: "Status: loading · Size: Small/Medium", args: {"Status": "loading", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: loading · Size: XSmall */
export const Variant011: Story = { name: "Status: loading · Size: XSmall", args: {"Status": "loading", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: loading · Size: XXSmall */
export const Variant012: Story = { name: "Status: loading · Size: XXSmall", args: {"Status": "loading", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: disabled · Size: Small/Medium */
export const Variant013: Story = { name: "Status: disabled · Size: Small/Medium", args: {"Status": "disabled", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: disabled · Size: XSmall */
export const Variant014: Story = { name: "Status: disabled · Size: XSmall", args: {"Status": "disabled", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: disabled · Size: XXSmall */
export const Variant015: Story = { name: "Status: disabled · Size: XXSmall", args: {"Status": "disabled", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: complete · Size: Small/Medium */
export const Variant016: Story = { name: "Status: complete · Size: Small/Medium", args: {"Status": "complete", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: complete · Size: XSmall */
export const Variant017: Story = { name: "Status: complete · Size: XSmall", args: {"Status": "complete", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: complete · Size: XXSmall */
export const Variant018: Story = { name: "Status: complete · Size: XXSmall", args: {"Status": "complete", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: warning · Size: Small/Medium */
export const Variant019: Story = { name: "Status: warning · Size: Small/Medium", args: {"Status": "warning", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: warning · Size: XSmall */
export const Variant020: Story = { name: "Status: warning · Size: XSmall", args: {"Status": "warning", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: warning · Size: XXSmall */
export const Variant021: Story = { name: "Status: warning · Size: XXSmall", args: {"Status": "warning", "Size": "XXSmall"}, tags: ["!autodocs"] };
/** Status: danger · Size: Small/Medium */
export const Variant022: Story = { name: "Status: danger · Size: Small/Medium", args: {"Status": "danger", "Size": "Small/Medium"}, tags: ["!autodocs"] };
/** Status: danger · Size: XSmall */
export const Variant023: Story = { name: "Status: danger · Size: XSmall", args: {"Status": "danger", "Size": "XSmall"}, tags: ["!autodocs"] };
/** Status: danger · Size: XXSmall */
export const Variant024: Story = { name: "Status: danger · Size: XXSmall", args: {"Status": "danger", "Size": "XXSmall"}, tags: ["!autodocs"] };
