// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Comment } from './Comment';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Comment: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-20788-280525", title: "Components/Elastic UI/Comment [20788:280525]",
  component: Comment, tags: ['autodocs'],
  args: {"Type": "Regular", "Color": "Plain"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Regular"}}, "options": ["Update", "Collapsed", "Regular"]}, "Color": {"control": "inline-radio", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Plain"}}, "options": ["Primary", "Plain"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "20788:280525", exportName: "Comment", docs: { description: { component: "You can change all the settings of the Timeline icon avatar to suit your needs.\n\n--\n\nThe Header portion of contents utilizes the Slots component to add additional content like tabs.\n\nYou may need to adjust the Auto layout settings to get your desired layout.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=20788-280525) · 4 вариантов." } } },
} satisfies Meta<typeof Comment>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="20788:280525" component={Comment} storyId="ds-20788-280525"/> };
/** Type: Regular · Color: Plain */
export const Variant001: Story = { name: "Type: Regular · Color: Plain", args: {"Type": "Regular", "Color": "Plain"}, tags: ["!autodocs"] };
/** Type: Regular · Color: Primary */
export const Variant002: Story = { name: "Type: Regular · Color: Primary", args: {"Type": "Regular", "Color": "Primary"}, tags: ["!autodocs"] };
/** Type: Update · Color: Plain */
export const Variant003: Story = { name: "Type: Update · Color: Plain", args: {"Type": "Update", "Color": "Plain"}, tags: ["!autodocs"] };
/** Type: Collapsed · Color: Plain */
export const Variant004: Story = { name: "Type: Collapsed · Color: Plain", args: {"Type": "Collapsed", "Color": "Plain"}, tags: ["!autodocs"] };
