// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { RadioButton } from './RadioButton';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** RadioButton: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-16033-196057", title: "Components/Elastic UI/.📦 Radio  ·  Button [16033:196057]",
  component: RadioButton, tags: ['autodocs'],
  args: {"Checked": "False", "Disabled": "False", "Focus": "False", "Size": "Medium"},
  argTypes: {"Checked": {"control": "inline-radio", "description": "Свойство Figma: Checked", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Focus": {"control": "inline-radio", "description": "Свойство Figma: Focus", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "16033:196057", exportName: "RadioButton", docs: { description: { component: ".📦 Radio / Button — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=16033-196057) · 10 вариантов." } } },
} satisfies Meta<typeof RadioButton>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="16033:196057" component={RadioButton} storyId="ds-16033-196057"/> };
/** Checked: False · Disabled: False · Focus: False · Size: Medium */
export const Variant001: Story = { name: "Checked: False · Disabled: False · Focus: False · Size: Medium", args: {"Checked": "False", "Disabled": "False", "Focus": "False", "Size": "Medium"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: False · Focus: False · Size: Small */
export const Variant002: Story = { name: "Checked: False · Disabled: False · Focus: False · Size: Small", args: {"Checked": "False", "Disabled": "False", "Focus": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Checked: True · Disabled: False · Focus: False · Size: Medium */
export const Variant003: Story = { name: "Checked: True · Disabled: False · Focus: False · Size: Medium", args: {"Checked": "True", "Disabled": "False", "Focus": "False", "Size": "Medium"}, tags: ["!autodocs"] };
/** Checked: True · Disabled: False · Focus: False · Size: Small */
export const Variant004: Story = { name: "Checked: True · Disabled: False · Focus: False · Size: Small", args: {"Checked": "True", "Disabled": "False", "Focus": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: False · Focus: True · Size: Medium */
export const Variant005: Story = { name: "Checked: False · Disabled: False · Focus: True · Size: Medium", args: {"Checked": "False", "Disabled": "False", "Focus": "True", "Size": "Medium"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: False · Focus: True · Size: Small */
export const Variant006: Story = { name: "Checked: False · Disabled: False · Focus: True · Size: Small", args: {"Checked": "False", "Disabled": "False", "Focus": "True", "Size": "Small"}, tags: ["!autodocs"] };
/** Checked: True · Disabled: True · Focus: False · Size: Medium */
export const Variant007: Story = { name: "Checked: True · Disabled: True · Focus: False · Size: Medium", args: {"Checked": "True", "Disabled": "True", "Focus": "False", "Size": "Medium"}, tags: ["!autodocs"] };
/** Checked: True · Disabled: True · Focus: False · Size: Small */
export const Variant008: Story = { name: "Checked: True · Disabled: True · Focus: False · Size: Small", args: {"Checked": "True", "Disabled": "True", "Focus": "False", "Size": "Small"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: True · Focus: False · Size: Medium */
export const Variant009: Story = { name: "Checked: False · Disabled: True · Focus: False · Size: Medium", args: {"Checked": "False", "Disabled": "True", "Focus": "False", "Size": "Medium"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: True · Focus: False · Size: Small */
export const Variant010: Story = { name: "Checked: False · Disabled: True · Focus: False · Size: Small", args: {"Checked": "False", "Disabled": "True", "Focus": "False", "Size": "Small"}, tags: ["!autodocs"] };
