// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { NavMenu } from './NavMenu';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** NavMenu: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-153-2777", title: "Components/UX-Lab/NavMenu [153:2777]",
  component: NavMenu, tags: ['autodocs'],
  args: {"FooterText#153:16": "Рабочее пространство команды", "ProjectLabel#153:27": "ПРОЕКТ: ИНТЕРНЕТ-МАГАЗИН", "StudyLabel#153:38": "ИССЛЕДОВАНИЕ: ПОКУПКА", "Active": "Projects"},
  argTypes: {"FooterText#153:16": {"control": "text", "description": "Свойство Figma: FooterText", "table": {"category": "Figma", "defaultValue": {"summary": "Рабочее пространство команды"}}}, "ProjectLabel#153:27": {"control": "text", "description": "Свойство Figma: ProjectLabel", "table": {"category": "Figma", "defaultValue": {"summary": "ПРОЕКТ: ИНТЕРНЕТ-МАГАЗИН"}}}, "StudyLabel#153:38": {"control": "text", "description": "Свойство Figma: StudyLabel", "table": {"category": "Figma", "defaultValue": {"summary": "ИССЛЕДОВАНИЕ: ПОКУПКА"}}}, "Active": {"control": "select", "description": "Свойство Figma: Active", "table": {"category": "Figma", "defaultValue": {"summary": "Projects"}}, "options": ["Projects", "Studies", "Setup", "Launch", "Overview", "Heatmap", "Funnel", "Participants", "Signals", "PDF"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "153:2777", exportName: "NavMenu", docs: { description: { component: "NavMenu — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=153-2777) · 10 вариантов." } } },
} satisfies Meta<typeof NavMenu>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="153:2777" component={NavMenu} storyId="ds-153-2777"/> };
/** Active: Projects */
export const Variant001: Story = { name: "Active: Projects", args: {"Active": "Projects"}, tags: ["!autodocs"] };
/** Active: Studies */
export const Variant002: Story = { name: "Active: Studies", args: {"Active": "Studies"}, tags: ["!autodocs"] };
/** Active: Setup */
export const Variant003: Story = { name: "Active: Setup", args: {"Active": "Setup"}, tags: ["!autodocs"] };
/** Active: Launch */
export const Variant004: Story = { name: "Active: Launch", args: {"Active": "Launch"}, tags: ["!autodocs"] };
/** Active: Overview */
export const Variant005: Story = { name: "Active: Overview", args: {"Active": "Overview"}, tags: ["!autodocs"] };
/** Active: Heatmap */
export const Variant006: Story = { name: "Active: Heatmap", args: {"Active": "Heatmap"}, tags: ["!autodocs"] };
/** Active: Funnel */
export const Variant007: Story = { name: "Active: Funnel", args: {"Active": "Funnel"}, tags: ["!autodocs"] };
/** Active: Participants */
export const Variant008: Story = { name: "Active: Participants", args: {"Active": "Participants"}, tags: ["!autodocs"] };
/** Active: Signals */
export const Variant009: Story = { name: "Active: Signals", args: {"Active": "Signals"}, tags: ["!autodocs"] };
/** Active: PDF */
export const Variant010: Story = { name: "Active: PDF", args: {"Active": "PDF"}, tags: ["!autodocs"] };
