// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { TextKeyboard } from './TextKeyboard';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** TextKeyboard: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-32286-391636", title: "Components/Elastic UI/☠️ Text - Keyboard [32286:391636]",
  component: TextKeyboard, tags: ['autodocs'],
  args: {"Content#32286:1": "Text", "Size": "Medium"},
  argTypes: {"Content#32286:1": {"control": "text", "description": "Свойство Figma: Content", "table": {"category": "Figma", "defaultValue": {"summary": "Text"}}}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "X-Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "32286:391636", exportName: "TextKeyboard", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=32286-391636) · 3 вариантов." } } },
} satisfies Meta<typeof TextKeyboard>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="32286:391636" component={TextKeyboard} storyId="ds-32286-391636"/> };
/** Size: Medium */
export const Variant001: Story = { name: "Size: Medium", args: {"Size": "Medium"}, tags: ["!autodocs"] };
/** Size: Small */
export const Variant002: Story = { name: "Size: Small", args: {"Size": "Small"}, tags: ["!autodocs"] };
/** Size: X-Small */
export const Variant003: Story = { name: "Size: X-Small", args: {"Size": "X-Small"}, tags: ["!autodocs"] };
