// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { StepVertical } from './StepVertical';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** StepVertical: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-44287-3458", title: "Components/Elastic UI/.Step - Vertical [44287:3458]",
  component: StepVertical, tags: ['autodocs'],
  args: {"Status": "False"},
  argTypes: {"Status": {"control": "inline-radio", "description": "Свойство Figma: Status", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "44287:3458", exportName: "StepVertical", docs: { description: { component: ".Step - Vertical — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=44287-3458) · 2 вариантов." } } },
} satisfies Meta<typeof StepVertical>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="44287:3458" component={StepVertical} storyId="ds-44287-3458"/> };
/** Status: True */
export const Variant001: Story = { name: "Status: True", args: {"Status": "True"}, tags: ["!autodocs"] };
/** Status: False */
export const Variant002: Story = { name: "Status: False", args: {"Status": "False"}, tags: ["!autodocs"] };
