// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SliderRange } from './SliderRange';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SliderRange: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14757-83541", title: "Components/Elastic UI/.📦 Slider  ·  Range [14757:83541]",
  component: SliderRange, tags: ['autodocs'],
  args: {"State": "Default", "Compressed": "False"},
  argTypes: {"State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Empty"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14757:83541", exportName: "SliderRange", docs: { description: { component: ".📦 Slider / Range — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14757-83541) · 4 вариантов." } } },
} satisfies Meta<typeof SliderRange>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14757:83541" component={SliderRange} storyId="ds-14757-83541"/> };
/** State: Default · Compressed: False */
export const Variant001: Story = { name: "State: Default · Compressed: False", args: {"State": "Default", "Compressed": "False"}, tags: ["!autodocs"] };
/** State: Default · Compressed: True */
export const Variant002: Story = { name: "State: Default · Compressed: True", args: {"State": "Default", "Compressed": "True"}, tags: ["!autodocs"] };
/** State: Empty · Compressed: False */
export const Variant003: Story = { name: "State: Empty · Compressed: False", args: {"State": "Empty", "Compressed": "False"}, tags: ["!autodocs"] };
/** State: Empty · Compressed: True */
export const Variant004: Story = { name: "State: Empty · Compressed: True", args: {"State": "Empty", "Compressed": "True"}, tags: ["!autodocs"] };
