// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { BodyHorizontal } from './BodyHorizontal';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** BodyHorizontal: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36686-394689", title: "Components/Elastic UI/.Body-Horizontal [36686:394689]",
  component: BodyHorizontal, tags: ['autodocs'],
  args: {"Padding size": "Large"},
  argTypes: {"Padding size": {"control": "inline-radio", "description": "Свойство Figma: Padding size", "table": {"category": "Figma", "defaultValue": {"summary": "Large"}}, "options": ["Large", "Medium", "Small", "None"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36686:394689", exportName: "BodyHorizontal", docs: { description: { component: ".Body-Horizontal — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36686-394689) · 4 вариантов." } } },
} satisfies Meta<typeof BodyHorizontal>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36686:394689" component={BodyHorizontal} storyId="ds-36686-394689"/> };
/** Padding size: Large */
export const Variant001: Story = { name: "Padding size: Large", args: {"Padding size": "Large"}, tags: ["!autodocs"] };
/** Padding size: Medium */
export const Variant002: Story = { name: "Padding size: Medium", args: {"Padding size": "Medium"}, tags: ["!autodocs"] };
/** Padding size: Small */
export const Variant003: Story = { name: "Padding size: Small", args: {"Padding size": "Small"}, tags: ["!autodocs"] };
/** Padding size: None */
export const Variant004: Story = { name: "Padding size: None", args: {"Padding size": "None"}, tags: ["!autodocs"] };
