// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { NoStatus } from './NoStatus';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** NoStatus: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-44287-2331", title: "Components/Elastic UI/.No status [44287:2331]",
  component: NoStatus, tags: ['autodocs'],
  args: {"Last step#44191:73": true, "titleSize": "Medium"},
  argTypes: {"Last step#44191:73": {"control": "boolean", "description": "Свойство Figma: Last step", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Children#44199:139": {"control": "text", "description": "Свойство Figma: Children · ID исходного компонента иконки; см. Foundation/Icons.", "table": {"category": "Figma", "defaultValue": {"summary": "32177:399616"}}}, "titleSize": {"control": "inline-radio", "description": "Свойство Figma: titleSize", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "XSmall", "XXSmall"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "44287:2331", exportName: "NoStatus", docs: { description: { component: ".No status — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=44287-2331) · 4 вариантов." } } },
} satisfies Meta<typeof NoStatus>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="44287:2331" component={NoStatus} storyId="ds-44287-2331"/> };
/** titleSize: Medium */
export const Variant001: Story = { name: "titleSize: Medium", args: {"titleSize": "Medium"}, tags: ["!autodocs"] };
/** titleSize: Small */
export const Variant002: Story = { name: "titleSize: Small", args: {"titleSize": "Small"}, tags: ["!autodocs"] };
/** titleSize: XSmall */
export const Variant003: Story = { name: "titleSize: XSmall", args: {"titleSize": "XSmall"}, tags: ["!autodocs"] };
/** titleSize: XXSmall */
export const Variant004: Story = { name: "titleSize: XXSmall", args: {"titleSize": "XXSmall"}, tags: ["!autodocs"] };
