// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { StepsHorizontal } from './StepsHorizontal';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** StepsHorizontal: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-44199-23052", title: "Components/Elastic UI/StepsHorizontal [44199:23052]",
  component: StepsHorizontal, tags: ['autodocs'],
  args: {"Size": "Medium"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "XSmall"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "44199:23052", exportName: "StepsHorizontal", docs: { description: { component: "StepsHorizontal — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=44199-23052) · 3 вариантов." } } },
} satisfies Meta<typeof StepsHorizontal>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="44199:23052" component={StepsHorizontal} storyId="ds-44199-23052"/> };
/** Size: Medium */
export const Variant001: Story = { name: "Size: Medium", args: {"Size": "Medium"}, tags: ["!autodocs"] };
/** Size: Small */
export const Variant002: Story = { name: "Size: Small", args: {"Size": "Small"}, tags: ["!autodocs"] };
/** Size: XSmall */
export const Variant003: Story = { name: "Size: XSmall", args: {"Size": "XSmall"}, tags: ["!autodocs"] };
