// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FirstClickTargets } from './FirstClickTargets';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FirstClickTargets: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-135-778", title: "Components/UX-Lab/FirstClickTargets [135:778]",
  component: FirstClickTargets, tags: ['autodocs'],
  args: {"State": "Ready"},
  argTypes: {"State": {"control": "select", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Ready"}}, "options": ["Ready", "Loading", "Empty", "FilteredEmpty", "Error"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "135:778", exportName: "FirstClickTargets", docs: { description: { component: "FirstClickTargets — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=135-778) · 5 вариантов." } } },
} satisfies Meta<typeof FirstClickTargets>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="135:778" component={FirstClickTargets} storyId="ds-135-778"/> };
/** State: Ready */
export const Variant001: Story = { name: "State: Ready", args: {"State": "Ready"}, tags: ["!autodocs"] };
/** State: Loading */
export const Variant002: Story = { name: "State: Loading", args: {"State": "Loading"}, tags: ["!autodocs"] };
/** State: Empty */
export const Variant003: Story = { name: "State: Empty", args: {"State": "Empty"}, tags: ["!autodocs"] };
/** State: FilteredEmpty */
export const Variant004: Story = { name: "State: FilteredEmpty", args: {"State": "FilteredEmpty"}, tags: ["!autodocs"] };
/** State: Error */
export const Variant005: Story = { name: "State: Error", args: {"State": "Error"}, tags: ["!autodocs"] };
