// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { NotificationBadge } from './NotificationBadge';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** NotificationBadge: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13546-25393", title: "Components/Elastic UI/☠️ Notification Badge [13546:25393]",
  component: NotificationBadge, tags: ['autodocs'],
  args: {"Count#31998:26": "1", "Color": "Accent", "Size": "Medium"},
  argTypes: {"Count#31998:26": {"control": "text", "description": "Свойство Figma: Count", "table": {"category": "Figma", "defaultValue": {"summary": "1"}}}, "Color": {"control": "inline-radio", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Accent"}}, "options": ["Subdued", "Accent", "Success"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13546:25393", exportName: "NotificationBadge", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13546-25393) · 6 вариантов." } } },
} satisfies Meta<typeof NotificationBadge>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13546:25393" component={NotificationBadge} storyId="ds-13546-25393"/> };
/** Color: Subdued · Size: Small */
export const Variant001: Story = { name: "Color: Subdued · Size: Small", args: {"Color": "Subdued", "Size": "Small"}, tags: ["!autodocs"] };
/** Color: Success · Size: Small */
export const Variant002: Story = { name: "Color: Success · Size: Small", args: {"Color": "Success", "Size": "Small"}, tags: ["!autodocs"] };
/** Color: Subdued · Size: Medium */
export const Variant003: Story = { name: "Color: Subdued · Size: Medium", args: {"Color": "Subdued", "Size": "Medium"}, tags: ["!autodocs"] };
/** Color: Success · Size: Medium */
export const Variant004: Story = { name: "Color: Success · Size: Medium", args: {"Color": "Success", "Size": "Medium"}, tags: ["!autodocs"] };
/** Color: Accent · Size: Small */
export const Variant005: Story = { name: "Color: Accent · Size: Small", args: {"Color": "Accent", "Size": "Small"}, tags: ["!autodocs"] };
/** Color: Accent · Size: Medium */
export const Variant006: Story = { name: "Color: Accent · Size: Medium", args: {"Color": "Accent", "Size": "Medium"}, tags: ["!autodocs"] };
