// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ProductTab } from './ProductTab';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ProductTab: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-128-1055", title: "Components/UX-Lab/ProductTab [128:1055]",
  component: ProductTab, tags: ['autodocs'],
  args: {"Selected": "False", "State": "Default", "Size": "Small", "children": "Сигналы"},
  argTypes: {"Selected": {"control": "inline-radio", "description": "Свойство Figma: Selected", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Pressed", "Focus"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Small"}}, "options": ["Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "128:1055", exportName: "ProductTab", docs: { description: { component: "ProductTab — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=128-1055) · 8 вариантов." } } },
} satisfies Meta<typeof ProductTab>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="128:1055" component={ProductTab} storyId="ds-128-1055"/> };
/** Selected: False · State: Default · Size: Small */
export const Variant001: Story = { name: "Selected: False · State: Default · Size: Small", args: {"Selected": "False", "State": "Default", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: True · State: Default · Size: Small */
export const Variant002: Story = { name: "Selected: True · State: Default · Size: Small", args: {"Selected": "True", "State": "Default", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: False · State: Hover · Size: Small */
export const Variant003: Story = { name: "Selected: False · State: Hover · Size: Small", args: {"Selected": "False", "State": "Hover", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: True · State: Hover · Size: Small */
export const Variant004: Story = { name: "Selected: True · State: Hover · Size: Small", args: {"Selected": "True", "State": "Hover", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: False · State: Pressed · Size: Small */
export const Variant005: Story = { name: "Selected: False · State: Pressed · Size: Small", args: {"Selected": "False", "State": "Pressed", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: True · State: Pressed · Size: Small */
export const Variant006: Story = { name: "Selected: True · State: Pressed · Size: Small", args: {"Selected": "True", "State": "Pressed", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: False · State: Focus · Size: Small */
export const Variant007: Story = { name: "Selected: False · State: Focus · Size: Small", args: {"Selected": "False", "State": "Focus", "Size": "Small"}, tags: ["!autodocs"] };
/** Selected: True · State: Focus · Size: Small */
export const Variant008: Story = { name: "Selected: True · State: Focus · Size: Small", args: {"Selected": "True", "State": "Focus", "Size": "Small"}, tags: ["!autodocs"] };
