// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CollapsibleNavGroup } from './CollapsibleNavGroup';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** CollapsibleNavGroup: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-20785-279182", title: "Components/Elastic UI/Collapsible Nav Group [20785:279182]",
  component: CollapsibleNavGroup, tags: ['autodocs'],
  args: {"Background": "None", "Collapsed": "Yes"},
  argTypes: {"Background": {"control": "inline-radio", "description": "Свойство Figma: Background", "table": {"category": "Figma", "defaultValue": {"summary": "None"}}, "options": ["None", "Light", "Dark"]}, "Collapsed": {"control": "inline-radio", "description": "Свойство Figma: Collapsed", "table": {"category": "Figma", "defaultValue": {"summary": "Yes"}}, "options": ["Yes", "No"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "20785:279182", exportName: "CollapsibleNavGroup", docs: { description: { component: "&lt;EuiCollapsibleNavGroup&gt;\n\nThe contents of a Collapsible Nav Group can be anything, but most commonly is a List Group.\n\nReplace the List Group layer with a different component to change content type.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=20785-279182) · 6 вариантов." } } },
} satisfies Meta<typeof CollapsibleNavGroup>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="20785:279182" component={CollapsibleNavGroup} storyId="ds-20785-279182"/> };
/** Background: None · Collapsed: Yes */
export const Variant001: Story = { name: "Background: None · Collapsed: Yes", args: {"Background": "None", "Collapsed": "Yes"}, tags: ["!autodocs"] };
/** Background: None · Collapsed: No */
export const Variant002: Story = { name: "Background: None · Collapsed: No", args: {"Background": "None", "Collapsed": "No"}, tags: ["!autodocs"] };
/** Background: Light · Collapsed: Yes */
export const Variant003: Story = { name: "Background: Light · Collapsed: Yes", args: {"Background": "Light", "Collapsed": "Yes"}, tags: ["!autodocs"] };
/** Background: Light · Collapsed: No */
export const Variant004: Story = { name: "Background: Light · Collapsed: No", args: {"Background": "Light", "Collapsed": "No"}, tags: ["!autodocs"] };
/** Background: Dark · Collapsed: Yes */
export const Variant005: Story = { name: "Background: Dark · Collapsed: Yes", args: {"Background": "Dark", "Collapsed": "Yes"}, tags: ["!autodocs"] };
/** Background: Dark · Collapsed: No */
export const Variant006: Story = { name: "Background: Dark · Collapsed: No", args: {"Background": "Dark", "Collapsed": "No"}, tags: ["!autodocs"] };
