// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Header } from './Header';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Header: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-26824-283060", title: "Components/Elastic UI/Header [26824:283060]",
  component: Header, tags: ['autodocs'],
  args: {"Mobile": "False"},
  argTypes: {"Mobile": {"control": "inline-radio", "description": "Свойство Figma: Mobile", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "26824:283060", exportName: "Header", docs: { description: { component: "Header — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=26824-283060) · 2 вариантов." } } },
} satisfies Meta<typeof Header>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="26824:283060" component={Header} storyId="ds-26824-283060"/> };
/** Mobile: False */
export const Variant001: Story = { name: "Mobile: False", args: {"Mobile": "False"}, tags: ["!autodocs"] };
/** Mobile: True */
export const Variant002: Story = { name: "Mobile: True", args: {"Mobile": "True"}, tags: ["!autodocs"] };
