// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ToastList } from './ToastList';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ToastList: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-39196-447", title: "Components/Elastic UI/💡 Toast - List [39196:447]",
  component: ToastList, tags: ['autodocs'],
  args: {"showClearAllButtonAt": "false"},
  argTypes: {"showClearAllButtonAt": {"control": "inline-radio", "description": "Свойство Figma: showClearAllButtonAt", "table": {"category": "Figma", "defaultValue": {"summary": "false"}}, "options": ["false", "true"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "39196:447", exportName: "ToastList", docs: { description: { component: "💡 Toast - List — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=39196-447) · 2 вариантов." } } },
} satisfies Meta<typeof ToastList>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="39196:447" component={ToastList} storyId="ds-39196-447"/> };
/** showClearAllButtonAt: false */
export const Variant001: Story = { name: "showClearAllButtonAt: false", args: {"showClearAllButtonAt": "false"}, tags: ["!autodocs"] };
/** showClearAllButtonAt: true */
export const Variant002: Story = { name: "showClearAllButtonAt: true", args: {"showClearAllButtonAt": "true"}, tags: ["!autodocs"] };
