// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ProductNavItem } from './ProductNavItem';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ProductNavItem: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-128-563", title: "Components/UX-Lab/ProductNavItem [128:563]",
  component: ProductNavItem, tags: ['autodocs'],
  args: {"Selected": "False", "State": "Default", "children": "Обзор результатов"},
  argTypes: {"Selected": {"control": "inline-radio", "description": "Свойство Figma: Selected", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Pressed", "Focus"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "icon": {"control": "text", "description": "Данные / обработчик компонента", "table": {"category": "React"}}},
  parameters: { layout: "padded", catalogId: "128:563", exportName: "ProductNavItem", docs: { description: { component: "ProductNavItem — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=128-563) · 8 вариантов." } } },
} satisfies Meta<typeof ProductNavItem>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="128:563" component={ProductNavItem} storyId="ds-128-563"/> };
/** Selected: False · State: Default */
export const Variant001: Story = { name: "Selected: False · State: Default", args: {"Selected": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Selected: True · State: Default */
export const Variant002: Story = { name: "Selected: True · State: Default", args: {"Selected": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Selected: False · State: Hover */
export const Variant003: Story = { name: "Selected: False · State: Hover", args: {"Selected": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Selected: True · State: Hover */
export const Variant004: Story = { name: "Selected: True · State: Hover", args: {"Selected": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Selected: False · State: Pressed */
export const Variant005: Story = { name: "Selected: False · State: Pressed", args: {"Selected": "False", "State": "Pressed"}, tags: ["!autodocs"] };
/** Selected: True · State: Pressed */
export const Variant006: Story = { name: "Selected: True · State: Pressed", args: {"Selected": "True", "State": "Pressed"}, tags: ["!autodocs"] };
/** Selected: False · State: Focus */
export const Variant007: Story = { name: "Selected: False · State: Focus", args: {"Selected": "False", "State": "Focus"}, tags: ["!autodocs"] };
/** Selected: True · State: Focus */
export const Variant008: Story = { name: "Selected: True · State: Focus", args: {"Selected": "True", "State": "Focus"}, tags: ["!autodocs"] };
