// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AutoRefreshButton } from './AutoRefreshButton';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** AutoRefreshButton: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-23938-282840", title: "Components/Elastic UI/Auto Refresh Button [23938:282840]",
  component: AutoRefreshButton, tags: ['autodocs'],
  args: {"Paused": "true", "Open": "false"},
  argTypes: {"Paused": {"control": "inline-radio", "description": "Свойство Figma: Paused", "table": {"category": "Figma", "defaultValue": {"summary": "true"}}, "options": ["true", "false"]}, "Open": {"control": "inline-radio", "description": "Свойство Figma: Open", "table": {"category": "Figma", "defaultValue": {"summary": "false"}}, "options": ["false", "true"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "23938:282840", exportName: "AutoRefreshButton", docs: { description: { component: "Auto Refresh Button — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=23938-282840) · 4 вариантов." } } },
} satisfies Meta<typeof AutoRefreshButton>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="23938:282840" component={AutoRefreshButton} storyId="ds-23938-282840"/> };
/** Paused: true · Open: false */
export const Variant001: Story = { name: "Paused: true · Open: false", args: {"Paused": "true", "Open": "false"}, tags: ["!autodocs"] };
/** Paused: false · Open: false */
export const Variant002: Story = { name: "Paused: false · Open: false", args: {"Paused": "false", "Open": "false"}, tags: ["!autodocs"] };
/** Paused: true · Open: true */
export const Variant003: Story = { name: "Paused: true · Open: true", args: {"Paused": "true", "Open": "true"}, tags: ["!autodocs"] };
/** Paused: false · Open: true */
export const Variant004: Story = { name: "Paused: false · Open: true", args: {"Paused": "false", "Open": "true"}, tags: ["!autodocs"] };
