// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Dot } from './Dot';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Dot: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36391-398502", title: "Components/Elastic UI/Dot [36391:398502]",
  component: Dot, tags: ['autodocs'],
  args: {"Filled": "true"},
  argTypes: {"Filled": {"control": "inline-radio", "description": "Свойство Figma: Filled", "table": {"category": "Figma", "defaultValue": {"summary": "true"}}, "options": ["true", "false"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36391:398502", exportName: "Dot", docs: { description: { component: "Dot — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36391-398502) · 2 вариантов." } } },
} satisfies Meta<typeof Dot>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36391:398502" component={Dot} storyId="ds-36391-398502"/> };
/** Filled: true */
export const Variant001: Story = { name: "Filled: true", args: {"Filled": "true"}, tags: ["!autodocs"] };
/** Filled: false */
export const Variant002: Story = { name: "Filled: false", args: {"Filled": "false"}, tags: ["!autodocs"] };
