// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Tour } from './Tour';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Tour: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36391-397462", title: "Components/Elastic UI/Tour [36391:397462]",
  component: Tour, tags: ['autodocs'],
  args: {"Title#36391:3": true, "Meta Title#36391:5": true, "Description#36391:16": true, "Next#36435:0": false, "Skip#36435:9": true, "Dots#36441:48": true, "Arrow": "↑ Top"},
  argTypes: {"Title#36391:3": {"control": "boolean", "description": "Свойство Figma: Title", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Meta Title#36391:5": {"control": "boolean", "description": "Свойство Figma: Meta Title", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Description#36391:16": {"control": "boolean", "description": "Свойство Figma: Description", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Next#36435:0": {"control": "boolean", "description": "Свойство Figma: Next", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Skip#36435:9": {"control": "boolean", "description": "Свойство Figma: Skip", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Dots#36441:48": {"control": "boolean", "description": "Свойство Figma: Dots", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Arrow": {"control": "inline-radio", "description": "Свойство Figma: Arrow", "table": {"category": "Figma", "defaultValue": {"summary": "↑ Top"}}, "options": ["↑ Top", "-> Right", "↓ Bottom", "← Left"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36391:397462", exportName: "Tour", docs: { description: { component: "Tour — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36391-397462) · 4 вариантов." } } },
} satisfies Meta<typeof Tour>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36391:397462" component={Tour} storyId="ds-36391-397462"/> };
/** Arrow: ↑ Top */
export const Variant001: Story = { name: "Arrow: ↑ Top", args: {"Arrow": "↑ Top"}, tags: ["!autodocs"] };
/** Arrow: -> Right */
export const Variant002: Story = { name: "Arrow: -> Right", args: {"Arrow": "-> Right"}, tags: ["!autodocs"] };
/** Arrow: ↓ Bottom */
export const Variant003: Story = { name: "Arrow: ↓ Bottom", args: {"Arrow": "↓ Bottom"}, tags: ["!autodocs"] };
/** Arrow: ← Left */
export const Variant004: Story = { name: "Arrow: ← Left", args: {"Arrow": "← Left"}, tags: ["!autodocs"] };
