// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ButtonGroup } from './ButtonGroup';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ButtonGroup: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-31735-392753", title: "Components/Elastic UI/☠️ Button Group [31735:392753]",
  component: ButtonGroup, tags: ['autodocs'],
  args: {"Size": "Small*", "Full width": "True", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Small*"}}, "options": ["Medium", "Small*", "Compressed"]}, "Full width": {"control": "inline-radio", "description": "Свойство Figma: Full width", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["False", "True"]}, "Color": {"control": "inline-radio", "description": "Свойство Figma: Color", "table": {"category": "Figma", "defaultValue": {"summary": "Neutral*"}}, "options": ["Primary", "Neutral*"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Icon only": {"control": "inline-radio", "description": "Свойство Figma: Icon only", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "31735:392753", exportName: "ButtonGroup", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=31735-392753) · 27 вариантов." } } },
} satisfies Meta<typeof ButtonGroup>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="31735:392753" component={ButtonGroup} storyId="ds-31735-392753"/> };
/** Size: Compressed · Full width: False · Color: Primary · Disabled: True · Icon only: True */
export const Variant001: Story = { name: "Size: Compressed · Full width: False · Color: Primary · Disabled: True · Icon only: True", args: {"Size": "Compressed", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Primary · Disabled: True · Icon only: True */
export const Variant002: Story = { name: "Size: Medium · Full width: False · Color: Primary · Disabled: True · Icon only: True", args: {"Size": "Medium", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Primary · Disabled: True · Icon only: True */
export const Variant003: Story = { name: "Size: Small* · Full width: False · Color: Primary · Disabled: True · Icon only: True", args: {"Size": "Small*", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: False · Color: Primary · Disabled: True · Icon only: False */
export const Variant004: Story = { name: "Size: Compressed · Full width: False · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Compressed", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Primary · Disabled: True · Icon only: False */
export const Variant005: Story = { name: "Size: Medium · Full width: False · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Medium", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Primary · Disabled: True · Icon only: False */
export const Variant006: Story = { name: "Size: Small* · Full width: False · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Small*", "Full width": "False", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: True · Color: Primary · Disabled: True · Icon only: False */
export const Variant007: Story = { name: "Size: Compressed · Full width: True · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Compressed", "Full width": "True", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: True · Color: Primary · Disabled: True · Icon only: False */
export const Variant008: Story = { name: "Size: Medium · Full width: True · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Medium", "Full width": "True", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: True · Color: Primary · Disabled: True · Icon only: False */
export const Variant009: Story = { name: "Size: Small* · Full width: True · Color: Primary · Disabled: True · Icon only: False", args: {"Size": "Small*", "Full width": "True", "Color": "Primary", "Disabled": "True", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: False · Color: Primary · Disabled: False · Icon only: True */
export const Variant010: Story = { name: "Size: Compressed · Full width: False · Color: Primary · Disabled: False · Icon only: True", args: {"Size": "Compressed", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Primary · Disabled: False · Icon only: True */
export const Variant011: Story = { name: "Size: Medium · Full width: False · Color: Primary · Disabled: False · Icon only: True", args: {"Size": "Medium", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Primary · Disabled: False · Icon only: True */
export const Variant012: Story = { name: "Size: Small* · Full width: False · Color: Primary · Disabled: False · Icon only: True", args: {"Size": "Small*", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: False · Color: Primary · Disabled: False · Icon only: False */
export const Variant013: Story = { name: "Size: Compressed · Full width: False · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Compressed", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Primary · Disabled: False · Icon only: False */
export const Variant014: Story = { name: "Size: Medium · Full width: False · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Medium", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Primary · Disabled: False · Icon only: False */
export const Variant015: Story = { name: "Size: Small* · Full width: False · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Small*", "Full width": "False", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: True · Color: Primary · Disabled: False · Icon only: False */
export const Variant016: Story = { name: "Size: Compressed · Full width: True · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Compressed", "Full width": "True", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: True · Color: Primary · Disabled: False · Icon only: False */
export const Variant017: Story = { name: "Size: Medium · Full width: True · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Medium", "Full width": "True", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: True · Color: Primary · Disabled: False · Icon only: False */
export const Variant018: Story = { name: "Size: Small* · Full width: True · Color: Primary · Disabled: False · Icon only: False", args: {"Size": "Small*", "Full width": "True", "Color": "Primary", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: False · Color: Neutral* · Disabled: False · Icon only: True */
export const Variant019: Story = { name: "Size: Compressed · Full width: False · Color: Neutral* · Disabled: False · Icon only: True", args: {"Size": "Compressed", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Neutral* · Disabled: False · Icon only: True */
export const Variant020: Story = { name: "Size: Medium · Full width: False · Color: Neutral* · Disabled: False · Icon only: True", args: {"Size": "Medium", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Neutral* · Disabled: False · Icon only: True */
export const Variant021: Story = { name: "Size: Small* · Full width: False · Color: Neutral* · Disabled: False · Icon only: True", args: {"Size": "Small*", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "True"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: False · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant022: Story = { name: "Size: Compressed · Full width: False · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Compressed", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: False · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant023: Story = { name: "Size: Medium · Full width: False · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Medium", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: False · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant024: Story = { name: "Size: Small* · Full width: False · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Small*", "Full width": "False", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Compressed · Full width: True · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant025: Story = { name: "Size: Compressed · Full width: True · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Compressed", "Full width": "True", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Medium · Full width: True · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant026: Story = { name: "Size: Medium · Full width: True · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Medium", "Full width": "True", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
/** Size: Small* · Full width: True · Color: Neutral* · Disabled: False · Icon only: False */
export const Variant027: Story = { name: "Size: Small* · Full width: True · Color: Neutral* · Disabled: False · Icon only: False", args: {"Size": "Small*", "Full width": "True", "Color": "Neutral*", "Disabled": "False", "Icon only": "False"}, tags: ["!autodocs"] };
