// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { MarkdownEditorFooterLeftSide } from './MarkdownEditorFooterLeftSide';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** MarkdownEditorFooterLeftSide: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-16512-210927", title: "Components/Elastic UI/.📦Markdown Editor  ·  Footer  ·  Left side [16512:210927]",
  component: MarkdownEditorFooterLeftSide, tags: ['autodocs'],
  args: {"Type": "Errors"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Errors"}}, "options": ["Attachment error", "Errors", "Attachment"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "16512:210927", exportName: "MarkdownEditorFooterLeftSide", docs: { description: { component: ".📦Markdown Editor / Footer / Left side — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=16512-210927) · 3 вариантов." } } },
} satisfies Meta<typeof MarkdownEditorFooterLeftSide>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="16512:210927" component={MarkdownEditorFooterLeftSide} storyId="ds-16512-210927"/> };
/** Type: Errors */
export const Variant001: Story = { name: "Type: Errors", args: {"Type": "Errors"}, tags: ["!autodocs"] };
/** Type: Attachment error */
export const Variant002: Story = { name: "Type: Attachment error", args: {"Type": "Attachment error"}, tags: ["!autodocs"] };
/** Type: Attachment */
export const Variant003: Story = { name: "Type: Attachment", args: {"Type": "Attachment"}, tags: ["!autodocs"] };
