// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Logos } from './Logos';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Logos: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13648-4314", title: "Components/Elastic UI/☠️ Logos [13648:4314]",
  component: Logos, tags: ['autodocs'],
  args: {"Size": "Medium (default)"},
  argTypes: {"Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium (default)"}}, "options": ["Medium (default)", "Large", "X Large"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13648:4314", exportName: "Logos", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13648-4314) · 3 вариантов." } } },
} satisfies Meta<typeof Logos>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13648:4314" component={Logos} storyId="ds-13648-4314"/> };
/** Size: Medium (default) */
export const Variant001: Story = { name: "Size: Medium (default)", args: {"Size": "Medium (default)"}, tags: ["!autodocs"] };
/** Size: Large */
export const Variant002: Story = { name: "Size: Large", args: {"Size": "Large"}, tags: ["!autodocs"] };
/** Size: X Large */
export const Variant003: Story = { name: "Size: X Large", args: {"Size": "X Large"}, tags: ["!autodocs"] };
