// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FormRowHelpText } from './FormRowHelpText';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FormRowHelpText: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15883-126375", title: "Components/Elastic UI/☠️📦 Form Row  ·  Help text [15883:126375]",
  component: FormRowHelpText, tags: ['autodocs'],
  args: {"State": "Default"},
  argTypes: {"State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Invalid"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15883:126375", exportName: "FormRowHelpText", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15883-126375) · 2 вариантов." } } },
} satisfies Meta<typeof FormRowHelpText>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15883:126375" component={FormRowHelpText} storyId="ds-15883-126375"/> };
/** State: Default */
export const Variant001: Story = { name: "State: Default", args: {"State": "Default"}, tags: ["!autodocs"] };
/** State: Invalid */
export const Variant002: Story = { name: "State: Invalid", args: {"State": "Invalid"}, tags: ["!autodocs"] };
