// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { HeaderDark } from './HeaderDark';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** HeaderDark: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-26824-282882", title: "Components/Elastic UI/Header - Dark [26824:282882]",
  component: HeaderDark, tags: ['autodocs'],
  args: {"Show setup guides#47104:0": false, "Show feedback#47104:3": false, "Show AI Assistant#47104:6": true, "Mobile": "False"},
  argTypes: {"Show setup guides#47104:0": {"control": "boolean", "description": "Свойство Figma: Show setup guides", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Show feedback#47104:3": {"control": "boolean", "description": "Свойство Figma: Show feedback", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Show AI Assistant#47104:6": {"control": "boolean", "description": "Свойство Figma: Show AI Assistant", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "Mobile": {"control": "inline-radio", "description": "Свойство Figma: Mobile", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "26824:282882", exportName: "HeaderDark", docs: { description: { component: "Header - Dark — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=26824-282882) · 2 вариантов." } } },
} satisfies Meta<typeof HeaderDark>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="26824:282882" component={HeaderDark} storyId="ds-26824-282882"/> };
/** Mobile: False */
export const Variant001: Story = { name: "Mobile: False", args: {"Mobile": "False"}, tags: ["!autodocs"] };
/** Mobile: True */
export const Variant002: Story = { name: "Mobile: True", args: {"Mobile": "True"}, tags: ["!autodocs"] };
