// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { TextBlockquote } from './TextBlockquote';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** TextBlockquote: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-32296-392036", title: "Components/Elastic UI/☠️ Text - Blockquote [32296:392036]",
  component: TextBlockquote, tags: ['autodocs'],
  args: {"Text#32296:54": "Blockquote", "Size": "Medium"},
  argTypes: {"Text#32296:54": {"control": "text", "description": "Свойство Figma: Text", "table": {"category": "Figma", "defaultValue": {"summary": "Blockquote"}}}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Medium"}}, "options": ["Medium", "Small", "X-Small"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "32296:392036", exportName: "TextBlockquote", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=32296-392036) · 3 вариантов." } } },
} satisfies Meta<typeof TextBlockquote>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="32296:392036" component={TextBlockquote} storyId="ds-32296-392036"/> };
/** Size: Medium */
export const Variant001: Story = { name: "Size: Medium", args: {"Size": "Medium"}, tags: ["!autodocs"] };
/** Size: Small */
export const Variant002: Story = { name: "Size: Small", args: {"Size": "Small"}, tags: ["!autodocs"] };
/** Size: X-Small */
export const Variant003: Story = { name: "Size: X-Small", args: {"Size": "X-Small"}, tags: ["!autodocs"] };
