// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FirstClickTargetRow } from './FirstClickTargetRow';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FirstClickTargetRow: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-132-634", title: "Components/UX-Lab/FirstClickTargetRow [132:634]",
  component: FirstClickTargetRow, tags: ['autodocs'],
  args: {"Title#132:43": "Добавить в корзину", "Description#132:50": "Основное действие страницы", "Count#132:57": "6", "Share#132:64": "33%", "Selected": "False", "State": "Default"},
  argTypes: {"TargetIcon#132:36": {"control": "text", "description": "Свойство Figma: TargetIcon · ID исходного компонента иконки; см. Foundation/Icons.", "table": {"category": "Figma", "defaultValue": {"summary": "132:579"}}}, "Title#132:43": {"control": "text", "description": "Свойство Figma: Title", "table": {"category": "Figma", "defaultValue": {"summary": "Добавить в корзину"}}}, "Description#132:50": {"control": "text", "description": "Свойство Figma: Description", "table": {"category": "Figma", "defaultValue": {"summary": "Основное действие страницы"}}}, "Count#132:57": {"control": "text", "description": "Свойство Figma: Count", "table": {"category": "Figma", "defaultValue": {"summary": "6"}}}, "Share#132:64": {"control": "text", "description": "Свойство Figma: Share", "table": {"category": "Figma", "defaultValue": {"summary": "33%"}}}, "Selected": {"control": "inline-radio", "description": "Свойство Figma: Selected", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Focus"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "132:634", exportName: "FirstClickTargetRow", docs: { description: { component: "FirstClickTargetRow — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=132-634) · 6 вариантов." } } },
} satisfies Meta<typeof FirstClickTargetRow>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="132:634" component={FirstClickTargetRow} storyId="ds-132-634"/> };
/** Selected: False · State: Default */
export const Variant001: Story = { name: "Selected: False · State: Default", args: {"Selected": "False", "State": "Default"}, tags: ["!autodocs"] };
/** Selected: False · State: Hover */
export const Variant002: Story = { name: "Selected: False · State: Hover", args: {"Selected": "False", "State": "Hover"}, tags: ["!autodocs"] };
/** Selected: False · State: Focus */
export const Variant003: Story = { name: "Selected: False · State: Focus", args: {"Selected": "False", "State": "Focus"}, tags: ["!autodocs"] };
/** Selected: True · State: Default */
export const Variant004: Story = { name: "Selected: True · State: Default", args: {"Selected": "True", "State": "Default"}, tags: ["!autodocs"] };
/** Selected: True · State: Hover */
export const Variant005: Story = { name: "Selected: True · State: Hover", args: {"Selected": "True", "State": "Hover"}, tags: ["!autodocs"] };
/** Selected: True · State: Focus */
export const Variant006: Story = { name: "Selected: True · State: Focus", args: {"Selected": "True", "State": "Focus"}, tags: ["!autodocs"] };
