// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { TreeViewItem } from './TreeViewItem';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** TreeViewItem: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14652-151", title: "Components/Elastic UI/Tree view item [14652:151]",
  component: TreeViewItem, tags: ['autodocs'],
  args: {"Open?": "False", "Icon?": "True", "Arrow?": "True", "State": "Default", "Compressed?": "False"},
  argTypes: {"Open?": {"control": "inline-radio", "description": "Свойство Figma: Open?", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Icon?": {"control": "inline-radio", "description": "Свойство Figma: Icon?", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Arrow?": {"control": "inline-radio", "description": "Свойство Figma: Arrow?", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Focus"]}, "Compressed?": {"control": "inline-radio", "description": "Свойство Figma: Compressed?", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14652:151", exportName: "TreeViewItem", docs: { description: { component: "To adjust for nesting, use the auto-layout left padding.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14652-151) · 32 вариантов." } } },
} satisfies Meta<typeof TreeViewItem>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14652:151" component={TreeViewItem} storyId="ds-14652-151"/> };
/** Open?: False · Icon?: True · Arrow?: True · State: Default · Compressed?: False */
export const Variant001: Story = { name: "Open?: False · Icon?: True · Arrow?: True · State: Default · Compressed?: False", args: {"Open?": "False", "Icon?": "True", "Arrow?": "True", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: True · State: Default · Compressed?: True */
export const Variant002: Story = { name: "Open?: False · Icon?: True · Arrow?: True · State: Default · Compressed?: True", args: {"Open?": "False", "Icon?": "True", "Arrow?": "True", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: True · State: Focus · Compressed?: True */
export const Variant003: Story = { name: "Open?: False · Icon?: True · Arrow?: True · State: Focus · Compressed?: True", args: {"Open?": "False", "Icon?": "True", "Arrow?": "True", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: True · State: Focus · Compressed?: False */
export const Variant004: Story = { name: "Open?: False · Icon?: True · Arrow?: True · State: Focus · Compressed?: False", args: {"Open?": "False", "Icon?": "True", "Arrow?": "True", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: False · State: Default · Compressed?: False */
export const Variant005: Story = { name: "Open?: False · Icon?: True · Arrow?: False · State: Default · Compressed?: False", args: {"Open?": "False", "Icon?": "True", "Arrow?": "False", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: False · State: Default · Compressed?: True */
export const Variant006: Story = { name: "Open?: False · Icon?: True · Arrow?: False · State: Default · Compressed?: True", args: {"Open?": "False", "Icon?": "True", "Arrow?": "False", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: False · State: Focus · Compressed?: True */
export const Variant007: Story = { name: "Open?: False · Icon?: True · Arrow?: False · State: Focus · Compressed?: True", args: {"Open?": "False", "Icon?": "True", "Arrow?": "False", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: True · Arrow?: False · State: Focus · Compressed?: False */
export const Variant008: Story = { name: "Open?: False · Icon?: True · Arrow?: False · State: Focus · Compressed?: False", args: {"Open?": "False", "Icon?": "True", "Arrow?": "False", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: False · State: Default · Compressed?: False */
export const Variant009: Story = { name: "Open?: False · Icon?: False · Arrow?: False · State: Default · Compressed?: False", args: {"Open?": "False", "Icon?": "False", "Arrow?": "False", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: False · State: Default · Compressed?: True */
export const Variant010: Story = { name: "Open?: False · Icon?: False · Arrow?: False · State: Default · Compressed?: True", args: {"Open?": "False", "Icon?": "False", "Arrow?": "False", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: False · State: Focus · Compressed?: True */
export const Variant011: Story = { name: "Open?: False · Icon?: False · Arrow?: False · State: Focus · Compressed?: True", args: {"Open?": "False", "Icon?": "False", "Arrow?": "False", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: False · State: Focus · Compressed?: False */
export const Variant012: Story = { name: "Open?: False · Icon?: False · Arrow?: False · State: Focus · Compressed?: False", args: {"Open?": "False", "Icon?": "False", "Arrow?": "False", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: True · State: Default · Compressed?: False */
export const Variant013: Story = { name: "Open?: False · Icon?: False · Arrow?: True · State: Default · Compressed?: False", args: {"Open?": "False", "Icon?": "False", "Arrow?": "True", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: True · State: Default · Compressed?: True */
export const Variant014: Story = { name: "Open?: False · Icon?: False · Arrow?: True · State: Default · Compressed?: True", args: {"Open?": "False", "Icon?": "False", "Arrow?": "True", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: True · State: Focus · Compressed?: True */
export const Variant015: Story = { name: "Open?: False · Icon?: False · Arrow?: True · State: Focus · Compressed?: True", args: {"Open?": "False", "Icon?": "False", "Arrow?": "True", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: False · Icon?: False · Arrow?: True · State: Focus · Compressed?: False */
export const Variant016: Story = { name: "Open?: False · Icon?: False · Arrow?: True · State: Focus · Compressed?: False", args: {"Open?": "False", "Icon?": "False", "Arrow?": "True", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: True · State: Default · Compressed?: False */
export const Variant017: Story = { name: "Open?: True · Icon?: True · Arrow?: True · State: Default · Compressed?: False", args: {"Open?": "True", "Icon?": "True", "Arrow?": "True", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: True · State: Default · Compressed?: True */
export const Variant018: Story = { name: "Open?: True · Icon?: True · Arrow?: True · State: Default · Compressed?: True", args: {"Open?": "True", "Icon?": "True", "Arrow?": "True", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: True · State: Focus · Compressed?: True */
export const Variant019: Story = { name: "Open?: True · Icon?: True · Arrow?: True · State: Focus · Compressed?: True", args: {"Open?": "True", "Icon?": "True", "Arrow?": "True", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: True · State: Focus · Compressed?: False */
export const Variant020: Story = { name: "Open?: True · Icon?: True · Arrow?: True · State: Focus · Compressed?: False", args: {"Open?": "True", "Icon?": "True", "Arrow?": "True", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: False · State: Default · Compressed?: False */
export const Variant021: Story = { name: "Open?: True · Icon?: True · Arrow?: False · State: Default · Compressed?: False", args: {"Open?": "True", "Icon?": "True", "Arrow?": "False", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: False · State: Default · Compressed?: True */
export const Variant022: Story = { name: "Open?: True · Icon?: True · Arrow?: False · State: Default · Compressed?: True", args: {"Open?": "True", "Icon?": "True", "Arrow?": "False", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: False · State: Focus · Compressed?: True */
export const Variant023: Story = { name: "Open?: True · Icon?: True · Arrow?: False · State: Focus · Compressed?: True", args: {"Open?": "True", "Icon?": "True", "Arrow?": "False", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: True · Arrow?: False · State: Focus · Compressed?: False */
export const Variant024: Story = { name: "Open?: True · Icon?: True · Arrow?: False · State: Focus · Compressed?: False", args: {"Open?": "True", "Icon?": "True", "Arrow?": "False", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: False · State: Default · Compressed?: False */
export const Variant025: Story = { name: "Open?: True · Icon?: False · Arrow?: False · State: Default · Compressed?: False", args: {"Open?": "True", "Icon?": "False", "Arrow?": "False", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: False · State: Default · Compressed?: True */
export const Variant026: Story = { name: "Open?: True · Icon?: False · Arrow?: False · State: Default · Compressed?: True", args: {"Open?": "True", "Icon?": "False", "Arrow?": "False", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: False · State: Focus · Compressed?: True */
export const Variant027: Story = { name: "Open?: True · Icon?: False · Arrow?: False · State: Focus · Compressed?: True", args: {"Open?": "True", "Icon?": "False", "Arrow?": "False", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: False · State: Focus · Compressed?: False */
export const Variant028: Story = { name: "Open?: True · Icon?: False · Arrow?: False · State: Focus · Compressed?: False", args: {"Open?": "True", "Icon?": "False", "Arrow?": "False", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: True · State: Default · Compressed?: False */
export const Variant029: Story = { name: "Open?: True · Icon?: False · Arrow?: True · State: Default · Compressed?: False", args: {"Open?": "True", "Icon?": "False", "Arrow?": "True", "State": "Default", "Compressed?": "False"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: True · State: Default · Compressed?: True */
export const Variant030: Story = { name: "Open?: True · Icon?: False · Arrow?: True · State: Default · Compressed?: True", args: {"Open?": "True", "Icon?": "False", "Arrow?": "True", "State": "Default", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: True · State: Focus · Compressed?: True */
export const Variant031: Story = { name: "Open?: True · Icon?: False · Arrow?: True · State: Focus · Compressed?: True", args: {"Open?": "True", "Icon?": "False", "Arrow?": "True", "State": "Focus", "Compressed?": "True"}, tags: ["!autodocs"] };
/** Open?: True · Icon?: False · Arrow?: True · State: Focus · Compressed?: False */
export const Variant032: Story = { name: "Open?: True · Icon?: False · Arrow?: True · State: Focus · Compressed?: False", args: {"Open?": "True", "Icon?": "False", "Arrow?": "True", "State": "Focus", "Compressed?": "False"}, tags: ["!autodocs"] };
