// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DataGridHeaderRow } from './DataGridHeaderRow';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DataGridHeaderRow: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-46305-10129", title: "Components/Elastic UI/.🧱 Data Grid - Header Row [46305:10129]",
  component: DataGridHeaderRow, tags: ['autodocs'],
  args: {"Border": "None", "Style": "Shade"},
  argTypes: {"Border": {"control": "inline-radio", "description": "Свойство Figma: Border", "table": {"category": "Figma", "defaultValue": {"summary": "None"}}, "options": ["None", "Horizontal", "All"]}, "Style": {"control": "inline-radio", "description": "Свойство Figma: Style", "table": {"category": "Figma", "defaultValue": {"summary": "Shade"}}, "options": ["Shade", "Underline"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "46305:10129", exportName: "DataGridHeaderRow", docs: { description: { component: ".🧱 Data Grid - Header Row — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=46305-10129) · 6 вариантов." } } },
} satisfies Meta<typeof DataGridHeaderRow>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="46305:10129" component={DataGridHeaderRow} storyId="ds-46305-10129"/> };
/** Border: None · Style: Shade */
export const Variant001: Story = { name: "Border: None · Style: Shade", args: {"Border": "None", "Style": "Shade"}, tags: ["!autodocs"] };
/** Border: None · Style: Underline */
export const Variant002: Story = { name: "Border: None · Style: Underline", args: {"Border": "None", "Style": "Underline"}, tags: ["!autodocs"] };
/** Border: Horizontal · Style: Underline */
export const Variant003: Story = { name: "Border: Horizontal · Style: Underline", args: {"Border": "Horizontal", "Style": "Underline"}, tags: ["!autodocs"] };
/** Border: Horizontal · Style: Shade */
export const Variant004: Story = { name: "Border: Horizontal · Style: Shade", args: {"Border": "Horizontal", "Style": "Shade"}, tags: ["!autodocs"] };
/** Border: All · Style: Shade */
export const Variant005: Story = { name: "Border: All · Style: Shade", args: {"Border": "All", "Style": "Shade"}, tags: ["!autodocs"] };
/** Border: All · Style: Underline */
export const Variant006: Story = { name: "Border: All · Style: Underline", args: {"Border": "All", "Style": "Underline"}, tags: ["!autodocs"] };
