// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { FormControlBackground } from './FormControlBackground';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** FormControlBackground: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-13581-24745", title: "Components/Elastic UI/.📦 Form Control  ·  Background [13581:24745]",
  component: FormControlBackground, tags: ['autodocs'],
  args: {"Resizable#44601:0": false, "State": "Normal"},
  argTypes: {"Resizable#44601:0": {"control": "boolean", "description": "Свойство Figma: Resizable", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "State": {"control": "select", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Normal"}}, "options": ["Disabled", "Focus", "Invalid", "Normal", "Read-Only"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "13581:24745", exportName: "FormControlBackground", docs: { description: { component: ".📦 Form Control / Background — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=13581-24745) · 5 вариантов." } } },
} satisfies Meta<typeof FormControlBackground>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="13581:24745" component={FormControlBackground} storyId="ds-13581-24745"/> };
/** State: Disabled */
export const Variant001: Story = { name: "State: Disabled", args: {"State": "Disabled"}, tags: ["!autodocs"] };
/** State: Read-Only */
export const Variant002: Story = { name: "State: Read-Only", args: {"State": "Read-Only"}, tags: ["!autodocs"] };
/** State: Normal */
export const Variant003: Story = { name: "State: Normal", args: {"State": "Normal"}, tags: ["!autodocs"] };
/** State: Focus */
export const Variant004: Story = { name: "State: Focus", args: {"State": "Focus"}, tags: ["!autodocs"] };
/** State: Invalid */
export const Variant005: Story = { name: "State: Invalid", args: {"State": "Invalid"}, tags: ["!autodocs"] };
