// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Avatar } from './Avatar';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Avatar: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14755-585", title: "Components/Elastic UI/☠️ Avatar [14755:585]",
  component: Avatar, tags: ['autodocs'],
  args: {"Type": "User", "Content": "Initials", "Size": "Small - 24px"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "User"}}, "options": ["User", "Spaces"]}, "Content": {"control": "inline-radio", "description": "Свойство Figma: Content", "table": {"category": "Figma", "defaultValue": {"summary": "Initials"}}, "options": ["Initials", "Image", "Icon"]}, "Size": {"control": "inline-radio", "description": "Свойство Figma: Size", "table": {"category": "Figma", "defaultValue": {"summary": "Small - 24px"}}, "options": ["Small - 24px", "Medium - 32px (default)", "Large - 40px", "X-Large - 64px"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14755:585", exportName: "Avatar", docs: { description: { component: "☠️ Deprecated - Please use the new Elastic UI [Borealis] Library\n\nУстаревший компонент исходной Elastic UI. Сохранён для совместимости; не подменён новой версией.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14755-585) · 24 вариантов." } } },
} satisfies Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14755:585" component={Avatar} storyId="ds-14755-585"/> };
/** Type: User · Content: Image · Size: X-Large - 64px */
export const Variant001: Story = { name: "Type: User · Content: Image · Size: X-Large - 64px", args: {"Type": "User", "Content": "Image", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: User · Content: Image · Size: Large - 40px */
export const Variant002: Story = { name: "Type: User · Content: Image · Size: Large - 40px", args: {"Type": "User", "Content": "Image", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: User · Content: Image · Size: Medium - 32px (default) */
export const Variant003: Story = { name: "Type: User · Content: Image · Size: Medium - 32px (default)", args: {"Type": "User", "Content": "Image", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: User · Content: Image · Size: Small - 24px */
export const Variant004: Story = { name: "Type: User · Content: Image · Size: Small - 24px", args: {"Type": "User", "Content": "Image", "Size": "Small - 24px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Image · Size: X-Large - 64px */
export const Variant005: Story = { name: "Type: Spaces · Content: Image · Size: X-Large - 64px", args: {"Type": "Spaces", "Content": "Image", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Image · Size: Large - 40px */
export const Variant006: Story = { name: "Type: Spaces · Content: Image · Size: Large - 40px", args: {"Type": "Spaces", "Content": "Image", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Image · Size: Medium - 32px (default) */
export const Variant007: Story = { name: "Type: Spaces · Content: Image · Size: Medium - 32px (default)", args: {"Type": "Spaces", "Content": "Image", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Image · Size: Small - 24px */
export const Variant008: Story = { name: "Type: Spaces · Content: Image · Size: Small - 24px", args: {"Type": "Spaces", "Content": "Image", "Size": "Small - 24px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Initials · Size: X-Large - 64px */
export const Variant009: Story = { name: "Type: Spaces · Content: Initials · Size: X-Large - 64px", args: {"Type": "Spaces", "Content": "Initials", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Initials · Size: Large - 40px */
export const Variant010: Story = { name: "Type: Spaces · Content: Initials · Size: Large - 40px", args: {"Type": "Spaces", "Content": "Initials", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Initials · Size: Medium - 32px (default) */
export const Variant011: Story = { name: "Type: Spaces · Content: Initials · Size: Medium - 32px (default)", args: {"Type": "Spaces", "Content": "Initials", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Initials · Size: Small - 24px */
export const Variant012: Story = { name: "Type: Spaces · Content: Initials · Size: Small - 24px", args: {"Type": "Spaces", "Content": "Initials", "Size": "Small - 24px"}, tags: ["!autodocs"] };
/** Type: User · Content: Initials · Size: X-Large - 64px */
export const Variant013: Story = { name: "Type: User · Content: Initials · Size: X-Large - 64px", args: {"Type": "User", "Content": "Initials", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: User · Content: Icon · Size: X-Large - 64px */
export const Variant014: Story = { name: "Type: User · Content: Icon · Size: X-Large - 64px", args: {"Type": "User", "Content": "Icon", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Icon · Size: X-Large - 64px */
export const Variant015: Story = { name: "Type: Spaces · Content: Icon · Size: X-Large - 64px", args: {"Type": "Spaces", "Content": "Icon", "Size": "X-Large - 64px"}, tags: ["!autodocs"] };
/** Type: User · Content: Initials · Size: Large - 40px */
export const Variant016: Story = { name: "Type: User · Content: Initials · Size: Large - 40px", args: {"Type": "User", "Content": "Initials", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: User · Content: Icon · Size: Large - 40px */
export const Variant017: Story = { name: "Type: User · Content: Icon · Size: Large - 40px", args: {"Type": "User", "Content": "Icon", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Icon · Size: Large - 40px */
export const Variant018: Story = { name: "Type: Spaces · Content: Icon · Size: Large - 40px", args: {"Type": "Spaces", "Content": "Icon", "Size": "Large - 40px"}, tags: ["!autodocs"] };
/** Type: User · Content: Initials · Size: Medium - 32px (default) */
export const Variant019: Story = { name: "Type: User · Content: Initials · Size: Medium - 32px (default)", args: {"Type": "User", "Content": "Initials", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: User · Content: Icon · Size: Medium - 32px (default) */
export const Variant020: Story = { name: "Type: User · Content: Icon · Size: Medium - 32px (default)", args: {"Type": "User", "Content": "Icon", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Icon · Size: Medium - 32px (default) */
export const Variant021: Story = { name: "Type: Spaces · Content: Icon · Size: Medium - 32px (default)", args: {"Type": "Spaces", "Content": "Icon", "Size": "Medium - 32px (default)"}, tags: ["!autodocs"] };
/** Type: User · Content: Initials · Size: Small - 24px */
export const Variant022: Story = { name: "Type: User · Content: Initials · Size: Small - 24px", args: {"Type": "User", "Content": "Initials", "Size": "Small - 24px"}, tags: ["!autodocs"] };
/** Type: User · Content: Icon · Size: Small - 24px */
export const Variant023: Story = { name: "Type: User · Content: Icon · Size: Small - 24px", args: {"Type": "User", "Content": "Icon", "Size": "Small - 24px"}, tags: ["!autodocs"] };
/** Type: Spaces · Content: Icon · Size: Small - 24px */
export const Variant024: Story = { name: "Type: Spaces · Content: Icon · Size: Small - 24px", args: {"Type": "Spaces", "Content": "Icon", "Size": "Small - 24px"}, tags: ["!autodocs"] };
