// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { TableCellFooter } from './TableCellFooter';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** TableCellFooter: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-15129-1692", title: "Components/Elastic UI/📦 Table Cell -> Footer [15129:1692]",
  component: TableCellFooter, tags: ['autodocs'],
  args: {"Compressed": "False"},
  argTypes: {"Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "15129:1692", exportName: "TableCellFooter", docs: { description: { component: "📦 Table Cell -> Footer — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=15129-1692) · 2 вариантов." } } },
} satisfies Meta<typeof TableCellFooter>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="15129:1692" component={TableCellFooter} storyId="ds-15129-1692"/> };
/** Compressed: False */
export const Variant001: Story = { name: "Compressed: False", args: {"Compressed": "False"}, tags: ["!autodocs"] };
/** Compressed: True */
export const Variant002: Story = { name: "Compressed: True", args: {"Compressed": "True"}, tags: ["!autodocs"] };
