// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CodeBlock } from './CodeBlock';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** CodeBlock: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-41035-20638", title: "Components/Elastic UI/Code Block [41035:20638]",
  component: CodeBlock, tags: ['autodocs'],
  args: {"↳ overflowHeight#41035:6": true, "↳ isCopiable#41035:7": true, "lineNumbers#41035:8": true, "transparentBackground#41581:0": true, "scrollbar#41581:3": false, "Controls": "False"},
  argTypes: {"↳ overflowHeight#41035:6": {"control": "boolean", "description": "Свойство Figma: ↳ overflowHeight", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "↳ isCopiable#41035:7": {"control": "boolean", "description": "Свойство Figma: ↳ isCopiable", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "lineNumbers#41035:8": {"control": "boolean", "description": "Свойство Figma: lineNumbers", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "transparentBackground#41581:0": {"control": "boolean", "description": "Свойство Figma: transparentBackground", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}}, "scrollbar#41581:3": {"control": "boolean", "description": "Свойство Figma: scrollbar", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}}, "Controls": {"control": "inline-radio", "description": "Свойство Figma: Controls", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["True", "False"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "41035:20638", exportName: "CodeBlock", docs: { description: { component: "Code Block — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=41035-20638) · 2 вариантов." } } },
} satisfies Meta<typeof CodeBlock>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="41035:20638" component={CodeBlock} storyId="ds-41035-20638"/> };
/** Controls: False */
export const Variant001: Story = { name: "Controls: False", args: {"Controls": "False"}, tags: ["!autodocs"] };
/** Controls: True */
export const Variant002: Story = { name: "Controls: True", args: {"Controls": "True"}, tags: ["!autodocs"] };
