// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DescriptionListItem } from './DescriptionListItem';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DescriptionListItem: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14711-170", title: "Components/Elastic UI/Description List Item [14711:170]",
  component: DescriptionListItem, tags: ['autodocs'],
  args: {"Type": "Stacked", "Reverse": "No", "Compressed": "No", "Align": "Left"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Stacked"}}, "options": ["Stacked", "Column", "Inline"]}, "Reverse": {"control": "inline-radio", "description": "Свойство Figma: Reverse", "table": {"category": "Figma", "defaultValue": {"summary": "No"}}, "options": ["No", "Yes"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "No"}}, "options": ["No", "Yes"]}, "Align": {"control": "inline-radio", "description": "Свойство Figma: Align", "table": {"category": "Figma", "defaultValue": {"summary": "Left"}}, "options": ["Left", "Center"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14711:170", exportName: "DescriptionListItem", docs: { description: { component: "&lt;EuiDescriptionList&gt;\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14711-170) · 18 вариантов." } } },
} satisfies Meta<typeof DescriptionListItem>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14711:170" component={DescriptionListItem} storyId="ds-14711-170"/> };
/** Type: Stacked · Reverse: No · Compressed: No · Align: Left */
export const Variant001: Story = { name: "Type: Stacked · Reverse: No · Compressed: No · Align: Left", args: {"Type": "Stacked", "Reverse": "No", "Compressed": "No", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: No · Compressed: No · Align: Center */
export const Variant002: Story = { name: "Type: Stacked · Reverse: No · Compressed: No · Align: Center", args: {"Type": "Stacked", "Reverse": "No", "Compressed": "No", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: No · Compressed: Yes · Align: Left */
export const Variant003: Story = { name: "Type: Stacked · Reverse: No · Compressed: Yes · Align: Left", args: {"Type": "Stacked", "Reverse": "No", "Compressed": "Yes", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: No · Compressed: Yes · Align: Center */
export const Variant004: Story = { name: "Type: Stacked · Reverse: No · Compressed: Yes · Align: Center", args: {"Type": "Stacked", "Reverse": "No", "Compressed": "Yes", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: No · Compressed: No · Align: Left */
export const Variant005: Story = { name: "Type: Column · Reverse: No · Compressed: No · Align: Left", args: {"Type": "Column", "Reverse": "No", "Compressed": "No", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: No · Compressed: No · Align: Center */
export const Variant006: Story = { name: "Type: Column · Reverse: No · Compressed: No · Align: Center", args: {"Type": "Column", "Reverse": "No", "Compressed": "No", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: No · Compressed: Yes · Align: Left */
export const Variant007: Story = { name: "Type: Column · Reverse: No · Compressed: Yes · Align: Left", args: {"Type": "Column", "Reverse": "No", "Compressed": "Yes", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: No · Compressed: Yes · Align: Center */
export const Variant008: Story = { name: "Type: Column · Reverse: No · Compressed: Yes · Align: Center", args: {"Type": "Column", "Reverse": "No", "Compressed": "Yes", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: Yes · Compressed: No · Align: Left */
export const Variant009: Story = { name: "Type: Stacked · Reverse: Yes · Compressed: No · Align: Left", args: {"Type": "Stacked", "Reverse": "Yes", "Compressed": "No", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: Yes · Compressed: No · Align: Center */
export const Variant010: Story = { name: "Type: Stacked · Reverse: Yes · Compressed: No · Align: Center", args: {"Type": "Stacked", "Reverse": "Yes", "Compressed": "No", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: Yes · Compressed: Yes · Align: Left */
export const Variant011: Story = { name: "Type: Stacked · Reverse: Yes · Compressed: Yes · Align: Left", args: {"Type": "Stacked", "Reverse": "Yes", "Compressed": "Yes", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Stacked · Reverse: Yes · Compressed: Yes · Align: Center */
export const Variant012: Story = { name: "Type: Stacked · Reverse: Yes · Compressed: Yes · Align: Center", args: {"Type": "Stacked", "Reverse": "Yes", "Compressed": "Yes", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: Yes · Compressed: Yes · Align: Left */
export const Variant013: Story = { name: "Type: Column · Reverse: Yes · Compressed: Yes · Align: Left", args: {"Type": "Column", "Reverse": "Yes", "Compressed": "Yes", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: Yes · Compressed: Yes · Align: Center */
export const Variant014: Story = { name: "Type: Column · Reverse: Yes · Compressed: Yes · Align: Center", args: {"Type": "Column", "Reverse": "Yes", "Compressed": "Yes", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: Yes · Compressed: No · Align: Left */
export const Variant015: Story = { name: "Type: Column · Reverse: Yes · Compressed: No · Align: Left", args: {"Type": "Column", "Reverse": "Yes", "Compressed": "No", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Column · Reverse: Yes · Compressed: No · Align: Center */
export const Variant016: Story = { name: "Type: Column · Reverse: Yes · Compressed: No · Align: Center", args: {"Type": "Column", "Reverse": "Yes", "Compressed": "No", "Align": "Center"}, tags: ["!autodocs"] };
/** Type: Inline · Reverse: No · Compressed: No · Align: Left */
export const Variant017: Story = { name: "Type: Inline · Reverse: No · Compressed: No · Align: Left", args: {"Type": "Inline", "Reverse": "No", "Compressed": "No", "Align": "Left"}, tags: ["!autodocs"] };
/** Type: Inline · Reverse: No · Compressed: Yes · Align: Left */
export const Variant018: Story = { name: "Type: Inline · Reverse: No · Compressed: Yes · Align: Left", args: {"Type": "Inline", "Reverse": "No", "Compressed": "Yes", "Align": "Left"}, tags: ["!autodocs"] };
