// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { SliderThumb } from './SliderThumb';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** SliderThumb: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14757-83542", title: "Components/Elastic UI/.📦 Slider  ·  Thumb [14757:83542]",
  component: SliderThumb, tags: ['autodocs'],
  args: {"Tooltip": "None"},
  argTypes: {"Tooltip": {"control": "inline-radio", "description": "Свойство Figma: Tooltip", "table": {"category": "Figma", "defaultValue": {"summary": "None"}}, "options": ["None", "Left", "Right"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14757:83542", exportName: "SliderThumb", docs: { description: { component: "The tooltip should show the current value of the thumb position.\n\nUse only on single value sliders and shift position if it runs outside the bounds of the slider.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14757-83542) · 3 вариантов." } } },
} satisfies Meta<typeof SliderThumb>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14757:83542" component={SliderThumb} storyId="ds-14757-83542"/> };
/** Tooltip: None */
export const Variant001: Story = { name: "Tooltip: None", args: {"Tooltip": "None"}, tags: ["!autodocs"] };
/** Tooltip: Left */
export const Variant002: Story = { name: "Tooltip: Left", args: {"Tooltip": "Left"}, tags: ["!autodocs"] };
/** Tooltip: Right */
export const Variant003: Story = { name: "Tooltip: Right", args: {"Tooltip": "Right"}, tags: ["!autodocs"] };
