// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Default as SourceDefault } from './Default';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Default: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-37824-395926", title: "Components/Elastic UI/.Default [37824:395926]",
  component: SourceDefault, tags: ['autodocs'],
  args: {"Checked": "True", "Disabled": "False"},
  argTypes: {"Checked": {"control": "inline-radio", "description": "Свойство Figma: Checked", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "37824:395926", exportName: "Default", docs: { description: { component: ".Default — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=37824-395926) · 4 вариантов." } } },
} satisfies Meta<typeof SourceDefault>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="37824:395926" component={SourceDefault} storyId="ds-37824-395926"/> };
/** Checked: True · Disabled: False */
export const Variant001: Story = { name: "Checked: True · Disabled: False", args: {"Checked": "True", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: False */
export const Variant002: Story = { name: "Checked: False · Disabled: False", args: {"Checked": "False", "Disabled": "False"}, tags: ["!autodocs"] };
/** Checked: True · Disabled: True */
export const Variant003: Story = { name: "Checked: True · Disabled: True", args: {"Checked": "True", "Disabled": "True"}, tags: ["!autodocs"] };
/** Checked: False · Disabled: True */
export const Variant004: Story = { name: "Checked: False · Disabled: True", args: {"Checked": "False", "Disabled": "True"}, tags: ["!autodocs"] };
