// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DatePickerCalendar } from './DatePickerCalendar';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** DatePickerCalendar: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14787-3001", title: "Components/Elastic UI/📦 Date Picker - Calendar [14787:3001]",
  component: DatePickerCalendar, tags: ['autodocs'],
  args: {"Time": "Off"},
  argTypes: {"Time": {"control": "inline-radio", "description": "Свойство Figma: Time", "table": {"category": "Figma", "defaultValue": {"summary": "Off"}}, "options": ["Off", "On", "Only"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14787:3001", exportName: "DatePickerCalendar", docs: { description: { component: "Contains re-design concepts.\n\nQuick calendar component of the Date Picker.\n\nCan be put inside of a Popover or used inline.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14787-3001) · 3 вариантов." } } },
} satisfies Meta<typeof DatePickerCalendar>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14787:3001" component={DatePickerCalendar} storyId="ds-14787-3001"/> };
/** Time: On */
export const Variant001: Story = { name: "Time: On", args: {"Time": "On"}, tags: ["!autodocs"] };
/** Time: Only */
export const Variant002: Story = { name: "Time: Only", args: {"Time": "Only"}, tags: ["!autodocs"] };
/** Time: Off */
export const Variant003: Story = { name: "Time: Off", args: {"Time": "Off"}, tags: ["!autodocs"] };
