import { createElement, useId, useState, type ComponentType, type ReactNode } from 'react';
import * as E from '@elastic/eui';
import moment from 'moment';
import { ElasticAvatarCollection, ElasticSourceCard, ElasticRefresh, ElasticThumbnail, ElasticNestedNav, ElasticFileField } from './ElasticVariantParts';
import { DesignIcon, type VariantValues } from './CatalogComponent';
import { isOn } from './variantValues';
import styles from './ElasticComponent.module.css';
import tokenManifest from '../../tokens/manifest.json';
import productTheme from '../../tokens/product-theme.json';
import { useVariantState } from './useVariantState';
import { ElasticDataGrid } from './ElasticDataGrid';
import { ElasticTablePart } from './ElasticTableParts';
import { ElasticFilters } from './ElasticFilters';
import { ElasticNotifications } from './ElasticNotifications';
import { ElasticPagePart } from './ElasticPageParts';
import { ElasticSelectable } from './ElasticSelectable';
import { ElasticFormPart, ElasticMarkdownPart, ElasticRangePart, ElasticDatePart, ElasticPopoverPart, ElasticTourPart } from './ElasticParts';

// The one dynamic boundary: exact Figma property names are normalized here,
// while each public facade exposes its own literal-union property contract.
function ui(name: keyof typeof E, props: Record<string, unknown> = {}, ...children: ReactNode[]) {
  const component = E[name] as unknown as ComponentType<Record<string, unknown>>;
  if (!component) throw new Error(`EUI adapter unavailable: ${name}`);
  return createElement(component, props, ...children);
}
const sizes: Record<string, string> = { none:'none', xs:'xs',s:'s',m:'m',l:'l',xl:'xl',xxl:'xxl','x small':'xs','xxx-small':'xxxs', 'x-small':'xs', xsmall:'xs', xxsmall:'xxs', 'small/medium':'s', 'extra small':'xs', 'xx-small':'xxs', small:'s', medium:'m', large:'l', 'x large':'xl', 'xx large':'xxl', 'x-large':'xl', 'xx-large':'xxl', compressed:'compressed' };
function size(value: unknown, fallback='m') { return sizes[String(value||'').toLowerCase().replace(/\*.*/, '').trim().split(/ - | \(/)[0]] || fallback; }
function color(value: unknown) { const key=String(value||'primary').toLowerCase().replace(/\*.*/, '').trim(); return ({neutral:'text',default:'default',failure:'danger',healthy:'success',unknown:'subdued',active:'primary','text (defualt)':'text','secondary':'success'} as Record<string,string>)[key] || key; }
const palette=tokenManifest.tokens.filter(t=>t.type==='COLOR'&&t.name.includes('Color Blind')).slice(0,6).map(t=>Object.values(t.values)[0]);

export function ElasticComponent({ index: i, values: p }: { index: number; values: VariantValues }) {
  const id=useId();
  const [text,setText]=useVariantState(String(p.State==='Placeholder'?'':p.value??'Пример значения'));
  const [checked,setChecked]=useVariantState(isOn(p.Checked)||isOn(p.Selected)||isOn(p['Checked?'])||isOn(p.Active)||isOn(p['Active?']));
  const [open,setOpen]=useVariantState(isOn(p.Expand)||isOn(p.Open));
  const [selected,setSelected]=useState('one');
  const [page,setPage]=useVariantState(p.Type==='Many is last'?9:p.Type==='Many in between'?4:0);
  const [number,setNumber]=useState(40);
  const [date,setDate]=useState(moment('2026-09-23'));
  const [endDate,setEndDate]=useState(moment('2026-09-30'));
  const [groupSelection,setGroupSelection]=useState<Record<string,boolean>>({});
  const disabled=isOn(p.Disabled)||isOn(p['Disabled?'])||p.State==='Disabled';
  const invalid=p.State==='Invalid'||isOn(p.Invalid);
  const compressed=isOn(p.Compressed)||isOn(p['Compressed?'])||i===88;
  const label=String(p.label??Object.entries(p).find(([k,v])=>/^(Text|Label)#/.test(k)&&typeof v==='string')?.[1]??'Пример');
  const property=(key:string)=>p[key]??Object.entries(p).find(([name])=>name.startsWith(key+'#'))?.[1];
  const flag=(key:string)=>isOn(property(key));
  const children=p.children as ReactNode;
  const click=()=>{setChecked(!checked); if(typeof p.onClick==='function')p.onClick();};
  const changed=(value:unknown)=>{if(typeof p.onChange==='function')p.onChange(value);};
  const fieldProps={id,'aria-label':label,disabled,isInvalid:invalid,compressed,fullWidth:true,readOnly:/read.only/i.test(String(p.State)),placeholder:'Введите значение',value:text,onChange:(event:React.ChangeEvent<HTMLInputElement>)=>{setText(event.target.value);changed(event.target.value);}};
  const button=(empty=false)=>ui(empty?'EuiButtonEmpty':'EuiButton',{size:size(p.Size)==='xs'?'s':size(p.Size)==='s'?'s':'m',color:color(p.Color),isDisabled:disabled,isLoading:isOn(p.Loading),...(empty?{}:{fill:p.Style==='Filled',minWidth:isOn(p['Icon only'])?false:undefined}),className:isOn(p['Icon only'])?styles.iconButton:undefined,'aria-label':isOn(p['Icon only'])?label:undefined,onClick:click},isOn(p['Icon only'])?<DesignIcon/>:<span className={styles.buttonContent}>{flag('Icon left')?<DesignIcon/>:null}{isOn(p.Loading)?String(property('Loading text')||label):label}{flag('Icon right')?<DesignIcon/>:null}</span>);
  const form=(kind:string)=>{
    let control:ReactNode;
    const clearable=isOn(p['Clearable?'])||isOn(p.Clearble);
    const readonly=/read.only/i.test(String(p.State));
    const clear=clearable&&text&&!disabled&&!readonly?ui('EuiButtonIcon',{'aria-label':'Очистить значение',iconType:'cross',onClick:()=>{setText('');changed('');}}):undefined;
    const extras={prepend:/Prepend|Both/.test(String(p['Prepend / Append']))?'https://':undefined,append:[...(p.Icon==='Both'?[<DesignIcon key="right"/>]:[]),...(clear?[clear]:[]),...(/Append|Both/.test(String(p['Prepend / Append']))?['.test']:[])]};
    const layout={...extras,append:extras.append.length?extras.append:undefined,isLoading:isOn(p.Loading)||isOn(p['Loading?']),icon:p.Icon&&p.Icon!=='None'?{type:DesignIcon,side:p.Icon==='Right'?'right':'left'}:undefined};
    if(/combobox/i.test(kind))control=ui('EuiComboBox',{'aria-label':label,isDisabled:disabled,isInvalid:invalid,compressed,options:[{label:'Первый'},{label:'Второй'}],selectedOptions:text?[{label:text}]:[],onChange:(options:{label:string}[])=>setText(options.map(o=>o.label).join(', ')),onCreateOption:(value:string)=>setText(value)});
    else if(/color palette/i.test(kind))control=ui('EuiColorPalettePicker',{palettes:[{value:'one',title:'Палитра',palette,type:'fixed'},{value:'two',title:'Палитра 2',palette:[...palette].reverse(),type:'fixed'}],value:selected,onChange:setSelected,disabled,compressed});
    else if(/select/i.test(kind))control=ui('EuiSelect',{...fieldProps,...layout,value:selected,options:[{value:'one',text:'Первый вариант'},{value:'two',text:'Второй вариант'}],onChange:(ev:React.ChangeEvent<HTMLSelectElement>)=>{setSelected(ev.target.value);changed(ev.target.value);}});
    else if(/number/i.test(kind))control=ui('EuiFieldNumber',{...fieldProps,...layout,value:number,onChange:(ev:React.ChangeEvent<HTMLInputElement>)=>{setNumber(Number(ev.target.value));changed(Number(ev.target.value));}});
    else if(/textarea/i.test(kind))control=ui('EuiTextArea',{...fieldProps,rows:3});
    else control=ui(/password/i.test(kind)?'EuiFieldPassword':/search/i.test(kind)?'EuiFieldSearch':'EuiFieldText',{...fieldProps,...layout});
    return ui('EuiFormRow',{label:isOn(p.Label)?'Название поля':undefined,helpText:isOn(p['Help text'])?'Пояснение к полю':undefined,isInvalid:invalid,error:invalid?['Проверьте значение']:undefined,fullWidth:true,display:isOn(p['Column display'])?'columnCompressed':compressed?'rowCompressed':'row'},control);
  };
  const breadcrumbs=()=>ui('EuiBreadcrumbs',{breadcrumbs:[{text:'UX-Lab',onClick:click},{text:'Проект',onClick:click},{text:'Исследование'}],truncate:isOn(p.Truncated)});
  const panel=(body:ReactNode=children||'Содержимое панели')=>ui('EuiPanel',{paddingSize:size(p['Padding size']||p['Padding Size']),hasShadow:isOn(p.Shadow),hasBorder:isOn(p.Border),color:['plain','subdued','transparent','primary','success','warning','danger','accent'].includes(color(p.Color||p.Display))?color(p.Color||p.Display):'plain',borderRadius:p['Border radius']==='False'?'none':'m'},body);
  const list=()=>ui('EuiListGroup',{flush:true,listItems:[{label:'Первый элемент',onClick:click,isActive:checked,isDisabled:disabled},{label:'Второй элемент',onClick:()=>setChecked(false)}]});
  const tabs=()=>ui('EuiTabs',{size:['s','m','l','xl'].includes(size(p.Size))?size(p.Size):'m',expand:isOn(p.Expand)},...['one','two'].map((value,j)=>ui('EuiTab',{key:value,isSelected:selected===value,disabled:disabled&&j===1,onClick:()=>setSelected(value)},j?'Вкладка 2':'Вкладка 1')));
  const checkbox=(radio=false)=>ui(radio?'EuiRadio':'EuiCheckbox',{id,label:p.Label==='False'||i===152||i===153?undefined:label,checked,disabled,className:p.Size==='Small'?styles.smallChoice:undefined,...(radio?{}:{indeterminate:isOn(p.Indeterminate)}),onChange:()=>{setChecked(!checked);changed(!checked);}});
  const empty=()=>ui('EuiEmptyPrompt',{title:<h3>Нет данных</h3>,body:<p>Здесь появятся результаты.</p>,layout:p.Layout==='Horizontal'||i===58?'horizontal':'vertical',paddingSize:size(p['Padding size']||p['Padding Size']),color:String(p.Color||'Transparent').toLowerCase().split(' + ')[0],hasBorder:p.Color==='Plain + Border',hasShadow:p.Color==='Plain + Shadow',actions:button(true)});
  const datePicker=(inline=false,timeOnly=false)=>ui('EuiDatePicker',{'aria-label':'Дата',selected:date,onChange:setDate,disabled,isInvalid:invalid,compressed,inline,showTimeSelect:timeOnly||p.Time==='On',showTimeSelectOnly:timeOnly,showIcon:false});
  const formRow=(control:ReactNode)=>ui('EuiFormRow',{label:isOn(p.Label)?'Название поля':undefined,isInvalid:invalid,error:invalid?['Проверьте значение']:undefined,helpText:isOn(p['Help text'])?'Пояснение к полю':undefined,display:isOn(p['Column display'])?'columnCompressed':compressed?'rowCompressed':'row'},control);

  const description=()=>ui('EuiDescriptionList',{type:p.Type==='Column'?'column':p.Type==='Inline'?'inline':'row',compressed,textStyle:isOn(p.Reverse)?'reverse':'normal',align:p.Align==='Center'?'center':'left',listItems:[{title:'Параметр',description:'Значение'}]});

  if(i===0)return ui('EuiAccordion',{id,buttonContent:label,forceState:open?'open':'closed',onToggle:setOpen,extraAction:flag('Extra action')?ui('EuiButtonIcon',{'aria-label':'Дополнительное действие',iconType:DesignIcon,onClick:click}):undefined,isLoading:isOn(p.Loading),isDisabled:disabled,arrowDisplay:String(p['Arrow display']||'Left').toLowerCase(),paddingSize:'m'},children||'Содержимое раскрытого блока');
  if(i>=1&&i<=3)return <ElasticRefresh index={i} values={p}/>;
  if(i===4)return ui('EuiAvatar',{name:'Анна Иванова',size:size(p.Size),type:p.Type==='Spaces'?'space':'user',initials:p.Content==='Initials'?'АИ':undefined,iconType:p.Content==='Icon'?DesignIcon:undefined});
  if(i===5||i===6)return <ElasticAvatarCollection index={i} values={p}/>;
  if(i===7)return ui('EuiNotificationBadge',{color:color(p.Color),size:size(p.Size)},String(property('Count')||'1'));
  if(i===8||i===9)return ui(i===9?'EuiBetaBadge':'EuiBadge',{color:color(p.Color),label:i===9?label:undefined,iconType:isOn(p['Icon only'])?DesignIcon:undefined,...(i===8?{isDisabled:disabled}:{})},i===8?label:undefined);
  if(i===10)return <div className={styles.bottomBar}>{children||'Нижняя панель'}{button()}</div>;
  if(i===11||i===95)return ui('EuiBreadcrumbs',{breadcrumbs:[{text:isOn(p.Collapsed)?'…':label,onClick:isOn(p.Interactive)||isOn(p.Linked)?click:undefined}],truncate:isOn(p.Truncated)});
  if(i===12||i===94)return breadcrumbs();
  if(i===13||i===14)return ui('EuiButtonGroup',{legend:'Выбор режима',options:i===14?[{id:id+'a',label}]:[{id:id+'a',label:'Первый'},{id:id+'b',label:'Второй'}],idSelected:checked?id+'a':i===14?'':id+'b',onChange:click,isDisabled:disabled,buttonSize:compressed?'compressed':size(p.Size)==='s'?'s':'m',color:color(p.Color),isFullWidth:isOn(p['Full width'])});
  if(i===15)return button(p.Style==='Empty');
  if(i===17)return ui('EuiText',{size:'s'},children||<p>Дополнительная информация.</p>);
  if(i===16)return ui('EuiCallOut',{title:'Сообщение',color:color(p.Color),size:size(p.Size)==='s'?'s':'m'},children||<p>Дополнительная информация.</p>);
  if(i===18||i===194)return ui('EuiTitle',{size:size(p.Size||p['Title size'],'s')},<h3>{label}</h3>);
  if(i===19||i===20)return <div className={styles.panelBackground} data-disabled={disabled} data-checked={i===20&&checked}>{panel()}</div>;
  if(i===124)return panel();
  if(i===21)return <div className={styles.row} style={{justifyContent:p.Align==='Right'?'flex-end':p.Align==='Center'?'center':undefined}}>{button(true)}{button()}</div>;
  if(i===55)return <footer className={styles.exampleFooter}><DesignIcon/></footer>;
  if(i===56)return <footer className={styles.exampleFooter} data-color={String(p.Color)}>{ui('EuiText',{size:'s'},<p>Хотите узнать больше? {ui('EuiLink',{onClick:click},'Подробнее')}</p>)}</footer>;
  if(i===23)return ui('EuiText',{size:'s'},<p>Пример содержимого карточки.</p>,p.Content==='1'?<ul><li>Первый пункт</li><li>Второй пункт</li><li>Третий пункт</li></ul>:p.Content==='2'?<p>Дополнительная информация.</p>:<>{button(true)}</>);
  if(i===22)return <ElasticSourceCard values={p}/>;
  if(i===24)return ui('EuiCode',{fontSize:size(p.Size)},'const value = 42;');
  if(i===25)return ui('EuiText',{size:size(p.Size)},<p>Пример с {ui('EuiCode',{},'const value = 42;')} в строке.</p>);
  if(i===26)return <span className={styles.codeAnnotation}>?</span>;
  if(i===27)return <span className={styles.codeLine}><span>1</span><span className={styles.codeAnnotation}>?</span></span>;
  if(i===28)return ui('EuiCodeBlock',{language:'js',fontSize:size(p.Size)==='xs'?'s':size(p.Size),paddingSize:'m',isCopyable:p.Controls!=='False',lineNumbers:isOn(p['lineNumbers#41035:8'])},'const value = 42;\nconsole.log(value);');
  if(i===29)return formRow(ui('EuiColorPicker',{color:text.startsWith('#')?text:productTheme['accent/strong'],onChange:setText,disabled,isInvalid:invalid,compressed}));
  if(i===30)return form('color palette');
  if(i===31)return ui('EuiColorPaletteDisplay',{palette:p.Palette==='Color blind (natural)'?[...palette].reverse():palette,type:'fixed'});
  if(i===36)return <div className={styles.row}><DesignIcon/>{ui('EuiTitle',{size:'xxs'},<h3>Навигация</h3>)}</div>;
  if(i===33||i===34)return <div className={i===34?styles.navOverlay:undefined}><nav className={styles.collapsibleNav} aria-label="Навигация"><E.EuiCollapsibleNavGroup title="Главная"/><E.EuiCollapsibleNavGroup title="Раздел" isCollapsible initialIsOpen>{list()}</E.EuiCollapsibleNavGroup>{['Первый раздел','Второй раздел','Третий раздел','Четвёртый раздел','Настройки'].map(title=><E.EuiCollapsibleNavGroup key={title} title={title} isCollapsible initialIsOpen={false}>{list()}</E.EuiCollapsibleNavGroup>)}</nav></div>;
  if(i===32||i===35)return ui('EuiCollapsibleNavGroup',{title:'Навигация',isCollapsible:true,initialIsOpen:p.Collapsed!=='Yes',background:String(p.Background||'None').toLowerCase()},list());
  if(i===37)return form('combobox');
  if(i===39)return <div className={styles.timelineIcon} data-position={String(p.Position)}>{p.Type==='Avatar'?ui('EuiAvatar',{name:'Анна',size:size(p.Size)}):<DesignIcon/>}</div>;
  if(i===38||i===40||i===41)return ui('EuiCommentList',{comments:Array.from({length:i===41?3:1},(_,index)=>({username:index?'Борис':'Анна',event:p.Type==='Update'?'обновила данные':p.Type==='Collapsed'?'предыдущие комментарии':'добавила комментарий',eventColor:p.Color==='Primary'?'primary':'plain',timestamp:'сегодня',children:p.Type==='Update'||p.Type==='Collapsed'?undefined:<p>Текст комментария</p>,timelineAvatar:<DesignIcon/>}))});
  if(i>=42&&i<=44||i===46)return <ElasticDataGrid key={JSON.stringify([p.Border,p.Borders,p.Padding,p.Style,p['Structured By']])} values={p} index={i}/>;
  if(i===45)return <div className={styles.stack}>{ui('EuiTitle',{size:'xs'},<h3>{String(p.Content)}</h3>)}{p.Content==='Columns'?ui('EuiCheckboxGroup',{options:[{id:id+'name',label:'Название'},{id:id+'count',label:'Значение'}],idToSelectedMap:groupSelection,onChange:(key:string,value:boolean)=>setGroupSelection(previous=>({...previous,[key]:value}))}):p.Content==='Sorting'?ui('EuiSelect',{'aria-label':'Сортировать',value:selected,options:[{value:'one',text:'По возрастанию'},{value:'two',text:'По убыванию'}],onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>setSelected(event.target.value)}):p.Content==='Keyboard shortcuts'?ui('EuiDescriptionList',{listItems:[{title:'Стрелки',description:'Перемещение по ячейкам'},{title:'Enter',description:'Открыть ячейку'}]}):<>{ui('EuiRange',{'aria-label':'Размер текста',min:1,max:3,value:number>3?2:number,onChange:(event:React.ChangeEvent<HTMLInputElement>)=>setNumber(Number(event.target.value))})}{ui('EuiSwitch',{label:'Чередовать строки',checked,onChange:click})}</>}</div>;
  if(i===47)return formRow(ui('EuiDatePickerRange',{isInvalid:invalid,disabled,compressed,startDateControl:datePicker(),endDateControl:ui('EuiDatePicker',{'aria-label':'Дата окончания',selected:endDate,onChange:setEndDate,disabled,isInvalid:invalid,compressed,showIcon:false})}));
  if(i===48||i===49)return formRow(datePicker(false,i===49));
  if(i===50)return datePicker(true,p.Time==='Only');
  if(i===51)return description();
  if(i===52)return ui('EuiBadge',{},'1');
  if(i===53||i===54)return <ElasticThumbnail index={i} values={p}/>;
  if(i>=57&&i<=59)return empty();
  if(i===60||i===61)return ui('EuiExpression',{description:'Параметр',value:'Значение',display:i===61?'columns':'inline',color:color(p.Color),isActive:isOn(p.Active),isInvalid:invalid,onClick:p.Clickable==='False'?undefined:click});
  if(i>=62&&i<=68)return <ElasticFilters index={i} values={p}/>;
  if(i>=69&&i<=73||i>=75&&i<=78)return <ElasticFormPart index={i} values={p}/>;
  if(i>=74&&i<=84)return form(i===80?'number':i===81?'search':i===82||i===75?'select':i===83?'password':i===84?'textarea':i===78?'combobox':String(p.Type||'text'));
  if(i===85||i===86)return <ElasticFileField index={i} values={p}/>;
  if(i===87||i===88)return ui('EuiForm',{isInvalid:invalid},form('text'),form('select'),button());
  if(i===89)return <div className={styles.row}>{ui('EuiFormLabel',{isInvalid:invalid},'Название поля')}{p.Append==='Text'?ui('EuiText',{size:'xs'},'Необязательно'):p.Append==='Icon'?<DesignIcon/>:null}</div>;
  if(i===90)return ui(invalid?'EuiFormErrorText':'EuiFormHelpText',{},invalid?'Проверьте значение':'Пояснение к полю');
  if(i===91)return ui('EuiFormRow',{label:'Название поля',display:isOn(p.Column)?'columnCompressed':'row'},ui('EuiFieldText',fieldProps));
  if(i===92)return ui('EuiDescribedFormGroup',{title:<h3>Настройки</h3>,description:<p>Параметры формы</p>,ratio:String(p.Ratio||'Half').replace('*','').toLowerCase()},form('text'));
  if(i===93||i===113)return <>{ui('EuiButton',{onClick:()=>setOpen(true)},i===93?'Открыть панель':'Открыть окно')}{open?(i===93?ui('EuiFlyout',{onClose:()=>setOpen(false),'aria-labelledby':id,size:'s',type:p.Type==='Push'?'push':'overlay'},ui('EuiFlyoutHeader',{},<h2 id={id}>Боковая панель</h2>),ui('EuiFlyoutBody',{},isOn(p.Tabs)?tabs():null,form('text'))):ui('EuiModal',{onClose:()=>setOpen(false),'aria-labelledby':id},ui('EuiModalHeader',{},ui('EuiModalHeaderTitle',{id},String(p.title||'Диалог'))),ui('EuiModalBody',{},children||form('text')),ui('EuiModalFooter',{},p.footer as ReactNode||ui('EuiButton',{onClick:()=>setOpen(false)},'Закрыть')))):null}</>;
  if(i===96||i===97)return ui('EuiHeader',{theme:i===96?'dark':'default',sections:[{items:isOn(p.Mobile)?[ui('EuiButtonIcon',{'aria-label':'Открыть меню',iconType:'menu',onClick:click}),<span key="brand">UX-Lab</span>]:[<span key="brand">UX-Lab</span>,breadcrumbs()]}]});
  if(i===98)return ui('EuiHealth',{color:color(p.Color),textSize:size(p.Size)},'Состояние');
  if(i===99)return ui('EuiHorizontalRule',{margin:size(p.Margin),size:p.Size==='Half'?'half':p.Size==='Quarter'?'quarter':'full'});
  if(i===100)return <div className={styles.imagePlaceholder} data-image-size={String(p.Size)} data-shadow={isOn(p.hasShadow)} role="img" aria-label="Место изображения"/>;
  if(i===101)return ui('EuiKeyPadMenuItem',{label,isDisabled:disabled,isSelected:checked,...(p.Checkable!=='None'?{checkable:String(p.Checkable).toLowerCase(),name:id,onChange:click}:{onClick:click,betaBadgeLabel:p['Beta badge']==='None'?undefined:'Beta',betaBadgeIconType:p['Beta badge']==='Icon'?DesignIcon:undefined})},<DesignIcon/>);
  if(i===102)return list();
  if(i===103||i===104)return ui('EuiListGroupItem',{label,size:size(p.Size),color:p.Color==='Default'?'text':color(p.Color),iconType:isOn(p.Icon)?DesignIcon:undefined,isActive:p.State==='Active'||checked,isDisabled:disabled,onClick:click,extraAction:isOn(p['Extra action'])?{iconType:DesignIcon,'aria-label':'Дополнительное действие',onClick:click}:undefined});
  if(i===105||i===106)return ui('EuiLoadingSpinner',{size:size(p.Size),className:i===106?styles.staticSpinner:undefined});
  if(i===107)return ui('EuiLoadingElastic',{size:size(p.Size)});
  if(i===108)return ui('EuiLoadingLogo',{size:size(p.Size),logo:DesignIcon});
  if(i===109)return ui('EuiLoadingChart',{size:size(p.Size),className:p.Color==='False'?styles.monochrome:undefined});
  if(i===111||i===112)return <ElasticMarkdownPart index={i} values={p}/>;
  if(i===110)return ui('EuiMarkdownEditor',{'aria-label':'Редактор Markdown',value:text,onChange:setText,autoFocus:p.Type==='Focus',errors:p.Type==='Errors'?['Проверьте Markdown']:p.Type==='Attachment Error'?['Файл не поддерживается. Выберите другой файл.']:undefined});
  if(i>=114&&i<=120)return <ElasticPagePart index={i} values={p}/>;
  if(i===121)return ui('EuiPagination',{pageCount:p.Type==='Few'?3:10,activePage:page,onPageClick:(next:number)=>{setPage(next);changed(next);},compressed:p.Type==='Compressed'||p.Type==='Mobile / Indeterminate'});
  if(i===122)return p.State==='Ellipsis'?<span>…</span>:ui('EuiPaginationButton',{pageIndex:0,isActive:p.State==='Active',isDisabled:disabled,onClick:click},'1');
  if(i===123)return ui('EuiSelect',{'aria-label':'Строк на странице',options:[{text:'10 строк'},{text:'25 строк'},{text:'50 строк'}]});
  if(i===125)return <E.EuiSplitPanel.Outer direction={p.Direction==='Horizontal'?'row':'column'} hasBorder={isOn(p.Border)} hasShadow={isOn(p.Shadow)} borderRadius={p['Border radius']==='False'?'none':'m'}><E.EuiSplitPanel.Inner>Первая область</E.EuiSplitPanel.Inner><E.EuiSplitPanel.Inner color="subdued">Вторая область</E.EuiSplitPanel.Inner></E.EuiSplitPanel.Outer>;
  if(i>=126&&i<=129)return <ElasticPopoverPart index={i} values={p}/>;
  if(i===130||i===131){const progress=ui('EuiProgress',{value:number,max:100,size:['xs','s','m','l'].includes(size(p.Size))?size(p.Size):'m',color:color(p.Color),label:isOn(p.Label)?'Загрузка':undefined,valueText:isOn(p.Label),position:i===131?'absolute':'static'});return i===131?<div className={styles.progressPanel}>{progress}</div>:progress;}
  if(i>=132&&i<=138)return <ElasticRangePart index={i} values={p}/>;
  if(i===139)return ui('EuiSearchBar',{query:text,onChange:({queryText}:{queryText:string})=>setText(queryText),box:{placeholder:'Поиск'}});
  if(i>=140&&i<=147)return <ElasticSelectable values={p} index={i}/>;
  if(i===148)return formRow(ui('EuiCheckboxGroup',{options:[{id:id+'one',label:'Первый вариант'},{id:id+'two',label:'Второй вариант'}],idToSelectedMap:groupSelection,onChange:(key:string,value:boolean)=>{setGroupSelection(previous=>({...previous,[key]:value}));changed({[key]:value});},compressed,disabled}));
  if(i===150)return formRow(ui('EuiRadioGroup',{name:id,options:[{id:id+'one',label:'Первый вариант'},{id:id+'two',label:'Второй вариант'}],idSelected:id+selected,onChange:(next:string)=>{setSelected(next.slice(id.length));changed(next);},compressed,disabled}));
  if(i===149||i===152)return checkbox();
  if(i===151||i===153)return checkbox(true);
  if(i>=154&&i<=156)return ui('EuiSwitch',{label,checked,disabled,compressed:compressed||i===155,onChange:click});
  if(i===158)return isOn(p.Show)?<span className={styles.nestedIndicator} data-last={isOn(p['Is last?'])} data-child={isOn(p['Is child?'])}/>:null;
  if(i===157)return <ElasticNestedNav values={p}/>;
  if(i===159)return p.Direction==='Horizontal'?<span className={styles.horizontalSpacer} style={{inlineSize:`var(--size-${({xs:'x-small',s:'small',m:'base',l:'large',xl:'x-large',xxl:'xx-large'} as Record<string,string>)[size(p.Size)]||'base'})`}}/>:ui('EuiSpacer',{size:size(p.Size)});
  if(i===160)return ui('EuiSteps',{titleSize:size(p.titleSize,'s'),steps:[{title:'Первый шаг',status:isOn(p.Status)?'complete':undefined,children:<p>Описание шага</p>},{title:'Второй шаг',status:isOn(p.Status)?'current':undefined,children:<p>Описание шага</p>}]});
  if(i===161)return ui('EuiStepsHorizontal',{size:size(p.Size),steps:[{title:'Первый шаг',status:'complete',onClick:click},{title:'Второй шаг',status:'current',onClick:click}]});
  if(i===162)return ui('EuiStepNumber',{number:1,status:p.Status==='default'?undefined:p.Status,titleSize:p.Size==='XXSmall'?'none':size(p.Size,'s')});
  if(i===163)return <div data-position={String(p.Position)} className={styles.horizontalStep}>{ui('EuiStepHorizontal',{step:1,title:'Шаг',size:size(p.Size),status:p.Status==='default'?undefined:p.Status,onClick:click})}</div>;
  if(i>=164&&i<=166)return ui('EuiStep',{step:1,title:'Шаг',titleSize:size(p.titleSize,'s'),status:i===164?p.status:i===166&&isOn(p.Status)?'current':undefined},children||<p>Описание шага</p>);
  if(i===167)return ui('EuiStat',{title:'24',description:'Показатель',titleSize:size(p.Size),titleColor:color(p.Color),textAlign:String(p.Align||'Left').toLowerCase(),reverse:isOn(p.Reverse),isLoading:isOn(p.Loading)});
  if(i>=168&&i<=173)return <ElasticDatePart index={i} values={p}/>;
  if(i>=174&&i<=178)return <ElasticTablePart index={i} values={p}/>;
  if(i===179)return ui('EuiTabs',{size:size(p.Size)},ui('EuiTab',{isSelected:checked,disabled,onClick:click},label));
  if(i===180)return tabs();
  if(i===188)return ui('EuiText',{},<p>Пример {p.Example==='Keyboard'?<kbd>Enter</kbd>:ui('EuiLink',{onClick:click},'ссылки')} в тексте.</p>);
  if(i===189)return ui('EuiText',{size:size(p.Size)},<h3>Заголовок</h3>,<p>Текст параграфа.</p>);
  if(i>=181&&i<=187){const tag=i===181?'h'+String(p.Level||'Heading 3').slice(-1):i===183?'small':i===185?'blockquote':i===186?'pre':i===187?'kbd':'p';return ui('EuiText',{size:size(p.Size)},i===184?ui('EuiLink',{onClick:click},label):createElement(tag,{},children||label));}
  if(i===190)return <div className={styles.timelineIcon} data-position={String(p.Position)}>{p.Type==='Avatar'?ui('EuiAvatar',{name:'Анна',size:size(p.Size)}):<DesignIcon/>}</div>;
  if(i>=191&&i<=193)return <E.EuiTimeline><E.EuiTimelineItem verticalAlign={i===192||p.verticalAlign==='Center'?'center':'top'} icon={<DesignIcon/>}>{p.Children==='Markdown Editor'?ui('EuiMarkdownEditor',{'aria-label':'Комментарий',value:text,onChange:setText}):p.Children==='Split Panel'?<E.EuiSplitPanel.Outer><E.EuiSplitPanel.Inner>Заголовок события</E.EuiSplitPanel.Inner><E.EuiSplitPanel.Inner color="subdued">Подробности</E.EuiSplitPanel.Inner></E.EuiSplitPanel.Outer>:<E.EuiPanel color={p.Children==='Panel with color'?'primary':'transparent'} hasShadow={false}>Содержимое события</E.EuiPanel>}</E.EuiTimelineItem></E.EuiTimeline>;
  if(i>=195&&i<=197)return <ElasticNotifications key={i} index={i} values={p}/>;
  if(i>=198&&i<=202)return <ElasticTourPart index={i} values={p}/>;
  if(i===203)return ui('EuiTreeView',{'aria-label':'Дерево',display:compressed?'compressed':'default',showExpansionArrows:isOn(p['Arrow?']),items:[{id:'root',label:'Раздел',isExpanded:isOn(p['Open?']),icon:isOn(p['Icon?'])?<DesignIcon/>:undefined,children:[{id:'child',label:'Элемент'}]}]});
  throw new Error(`Unmapped Elastic entry ${i}`);
}
