// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ParticipantRow } from './ParticipantRow';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** ParticipantRow: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-153-692", title: "Components/UX-Lab/ParticipantRow [153:692]",
  component: ParticipantRow, tags: ['autodocs'],
  args: {"ParticipantId#153:0": "014", "Attempt#153:4": "1", "Duration#153:8": "04:32", "SignalCount#153:12": "4", "State": "Default"},
  argTypes: {"ParticipantId#153:0": {"control": "text", "description": "Свойство Figma: ParticipantId", "table": {"category": "Figma", "defaultValue": {"summary": "014"}}}, "Attempt#153:4": {"control": "text", "description": "Свойство Figma: Attempt", "table": {"category": "Figma", "defaultValue": {"summary": "1"}}}, "Duration#153:8": {"control": "text", "description": "Свойство Figma: Duration", "table": {"category": "Figma", "defaultValue": {"summary": "04:32"}}}, "SignalCount#153:12": {"control": "text", "description": "Свойство Figma: SignalCount", "table": {"category": "Figma", "defaultValue": {"summary": "4"}}}, "State": {"control": "inline-radio", "description": "Свойство Figma: State", "table": {"category": "Figma", "defaultValue": {"summary": "Default"}}, "options": ["Default", "Hover", "Focus"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "153:692", exportName: "ParticipantRow", docs: { description: { component: "ParticipantRow — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/1LeVoicxDT7Sl8TpMPs4hr/?node-id=153-692) · 3 вариантов." } } },
} satisfies Meta<typeof ParticipantRow>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="153:692" component={ParticipantRow} storyId="ds-153-692"/> };
/** State: Default */
export const Variant001: Story = { name: "State: Default", args: {"State": "Default"}, tags: ["!autodocs"] };
/** State: Hover */
export const Variant002: Story = { name: "State: Hover", args: {"State": "Hover"}, tags: ["!autodocs"] };
/** State: Focus */
export const Variant003: Story = { name: "State: Focus", args: {"State": "Focus"}, tags: ["!autodocs"] };
