// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Slider } from './Slider';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Slider: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-14757-86523", title: "Components/Elastic UI/.📦 Slider [14757:86523]",
  component: Slider, tags: ['autodocs'],
  args: {"Type": "Single", "Show range": "True", "Compressed": "False", "Ticks": "False", "Levels": "False"},
  argTypes: {"Type": {"control": "inline-radio", "description": "Свойство Figma: Type", "table": {"category": "Figma", "defaultValue": {"summary": "Single"}}, "options": ["Single", "Dual"]}, "Show range": {"control": "inline-radio", "description": "Свойство Figma: Show range", "table": {"category": "Figma", "defaultValue": {"summary": "True"}}, "options": ["True", "False"]}, "Compressed": {"control": "inline-radio", "description": "Свойство Figma: Compressed", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Ticks": {"control": "inline-radio", "description": "Свойство Figma: Ticks", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "Levels": {"control": "inline-radio", "description": "Свойство Figma: Levels", "table": {"category": "Figma", "defaultValue": {"summary": "False"}}, "options": ["False", "True"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "14757:86523", exportName: "Slider", docs: { description: { component: "Edit the text of the Range components to adjust the thumb positions.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=14757-86523) · 32 вариантов." } } },
} satisfies Meta<typeof Slider>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="14757:86523" component={Slider} storyId="ds-14757-86523"/> };
/** Type: Dual · Show range: True · Compressed: False · Ticks: False · Levels: False */
export const Variant001: Story = { name: "Type: Dual · Show range: True · Compressed: False · Ticks: False · Levels: False", args: {"Type": "Dual", "Show range": "True", "Compressed": "False", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: False · Ticks: True · Levels: False */
export const Variant002: Story = { name: "Type: Dual · Show range: True · Compressed: False · Ticks: True · Levels: False", args: {"Type": "Dual", "Show range": "True", "Compressed": "False", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: False · Ticks: True · Levels: True */
export const Variant003: Story = { name: "Type: Dual · Show range: True · Compressed: False · Ticks: True · Levels: True", args: {"Type": "Dual", "Show range": "True", "Compressed": "False", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: False · Ticks: False · Levels: True */
export const Variant004: Story = { name: "Type: Dual · Show range: True · Compressed: False · Ticks: False · Levels: True", args: {"Type": "Dual", "Show range": "True", "Compressed": "False", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: True · Ticks: False · Levels: False */
export const Variant005: Story = { name: "Type: Dual · Show range: True · Compressed: True · Ticks: False · Levels: False", args: {"Type": "Dual", "Show range": "True", "Compressed": "True", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: True · Ticks: True · Levels: False */
export const Variant006: Story = { name: "Type: Dual · Show range: True · Compressed: True · Ticks: True · Levels: False", args: {"Type": "Dual", "Show range": "True", "Compressed": "True", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: True · Ticks: True · Levels: True */
export const Variant007: Story = { name: "Type: Dual · Show range: True · Compressed: True · Ticks: True · Levels: True", args: {"Type": "Dual", "Show range": "True", "Compressed": "True", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: True · Compressed: True · Ticks: False · Levels: True */
export const Variant008: Story = { name: "Type: Dual · Show range: True · Compressed: True · Ticks: False · Levels: True", args: {"Type": "Dual", "Show range": "True", "Compressed": "True", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: False · Ticks: False · Levels: False */
export const Variant009: Story = { name: "Type: Dual · Show range: False · Compressed: False · Ticks: False · Levels: False", args: {"Type": "Dual", "Show range": "False", "Compressed": "False", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: False · Ticks: True · Levels: False */
export const Variant010: Story = { name: "Type: Dual · Show range: False · Compressed: False · Ticks: True · Levels: False", args: {"Type": "Dual", "Show range": "False", "Compressed": "False", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: False · Ticks: True · Levels: True */
export const Variant011: Story = { name: "Type: Dual · Show range: False · Compressed: False · Ticks: True · Levels: True", args: {"Type": "Dual", "Show range": "False", "Compressed": "False", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: False · Ticks: False · Levels: True */
export const Variant012: Story = { name: "Type: Dual · Show range: False · Compressed: False · Ticks: False · Levels: True", args: {"Type": "Dual", "Show range": "False", "Compressed": "False", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: True · Ticks: False · Levels: False */
export const Variant013: Story = { name: "Type: Dual · Show range: False · Compressed: True · Ticks: False · Levels: False", args: {"Type": "Dual", "Show range": "False", "Compressed": "True", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: True · Ticks: True · Levels: False */
export const Variant014: Story = { name: "Type: Dual · Show range: False · Compressed: True · Ticks: True · Levels: False", args: {"Type": "Dual", "Show range": "False", "Compressed": "True", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: True · Ticks: True · Levels: True */
export const Variant015: Story = { name: "Type: Dual · Show range: False · Compressed: True · Ticks: True · Levels: True", args: {"Type": "Dual", "Show range": "False", "Compressed": "True", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Dual · Show range: False · Compressed: True · Ticks: False · Levels: True */
export const Variant016: Story = { name: "Type: Dual · Show range: False · Compressed: True · Ticks: False · Levels: True", args: {"Type": "Dual", "Show range": "False", "Compressed": "True", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: False · Ticks: False · Levels: False */
export const Variant017: Story = { name: "Type: Single · Show range: True · Compressed: False · Ticks: False · Levels: False", args: {"Type": "Single", "Show range": "True", "Compressed": "False", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: False · Ticks: True · Levels: False */
export const Variant018: Story = { name: "Type: Single · Show range: True · Compressed: False · Ticks: True · Levels: False", args: {"Type": "Single", "Show range": "True", "Compressed": "False", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: False · Ticks: True · Levels: True */
export const Variant019: Story = { name: "Type: Single · Show range: True · Compressed: False · Ticks: True · Levels: True", args: {"Type": "Single", "Show range": "True", "Compressed": "False", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: False · Ticks: False · Levels: True */
export const Variant020: Story = { name: "Type: Single · Show range: True · Compressed: False · Ticks: False · Levels: True", args: {"Type": "Single", "Show range": "True", "Compressed": "False", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: True · Ticks: False · Levels: False */
export const Variant021: Story = { name: "Type: Single · Show range: True · Compressed: True · Ticks: False · Levels: False", args: {"Type": "Single", "Show range": "True", "Compressed": "True", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: True · Ticks: True · Levels: False */
export const Variant022: Story = { name: "Type: Single · Show range: True · Compressed: True · Ticks: True · Levels: False", args: {"Type": "Single", "Show range": "True", "Compressed": "True", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: True · Ticks: True · Levels: False */
export const Variant023: Story = { name: "Type: Single · Show range: False · Compressed: True · Ticks: True · Levels: False", args: {"Type": "Single", "Show range": "False", "Compressed": "True", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: True · Ticks: True · Levels: True */
export const Variant024: Story = { name: "Type: Single · Show range: True · Compressed: True · Ticks: True · Levels: True", args: {"Type": "Single", "Show range": "True", "Compressed": "True", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: True · Compressed: True · Ticks: False · Levels: True */
export const Variant025: Story = { name: "Type: Single · Show range: True · Compressed: True · Ticks: False · Levels: True", args: {"Type": "Single", "Show range": "True", "Compressed": "True", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: False · Ticks: False · Levels: False */
export const Variant026: Story = { name: "Type: Single · Show range: False · Compressed: False · Ticks: False · Levels: False", args: {"Type": "Single", "Show range": "False", "Compressed": "False", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: False · Ticks: True · Levels: False */
export const Variant027: Story = { name: "Type: Single · Show range: False · Compressed: False · Ticks: True · Levels: False", args: {"Type": "Single", "Show range": "False", "Compressed": "False", "Ticks": "True", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: False · Ticks: True · Levels: True */
export const Variant028: Story = { name: "Type: Single · Show range: False · Compressed: False · Ticks: True · Levels: True", args: {"Type": "Single", "Show range": "False", "Compressed": "False", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: False · Ticks: False · Levels: True */
export const Variant029: Story = { name: "Type: Single · Show range: False · Compressed: False · Ticks: False · Levels: True", args: {"Type": "Single", "Show range": "False", "Compressed": "False", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: True · Ticks: False · Levels: False */
export const Variant030: Story = { name: "Type: Single · Show range: False · Compressed: True · Ticks: False · Levels: False", args: {"Type": "Single", "Show range": "False", "Compressed": "True", "Ticks": "False", "Levels": "False"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: True · Ticks: True · Levels: True */
export const Variant031: Story = { name: "Type: Single · Show range: False · Compressed: True · Ticks: True · Levels: True", args: {"Type": "Single", "Show range": "False", "Compressed": "True", "Ticks": "True", "Levels": "True"}, tags: ["!autodocs"] };
/** Type: Single · Show range: False · Compressed: True · Ticks: False · Levels: True */
export const Variant032: Story = { name: "Type: Single · Show range: False · Compressed: True · Ticks: False · Levels: True", args: {"Type": "Single", "Show range": "False", "Compressed": "True", "Ticks": "False", "Levels": "True"}, tags: ["!autodocs"] };
