// Generated by execution/generate_storybook_catalog.py; source: catalog.json.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Background } from './Background';
import { VariantMatrix } from '../../storybook/VariantMatrix';
/** Background: варианты, контролы и готовый код использования. */
const meta = {
  id: "ds-36238-395223", title: "Components/Elastic UI/Background [36238:395223]",
  component: Background, tags: ['autodocs'],
  args: {"Display": "Plain", "Shadow": "false", "Border": "false", "Disabled": "false"},
  argTypes: {"Display": {"control": "select", "description": "Свойство Figma: Display", "table": {"category": "Figma", "defaultValue": {"summary": "Plain"}}, "options": ["Plain", "Subdued", "Primary", "Success", "Warning", "Danger", "Accent", "Transparent"]}, "Shadow": {"control": "inline-radio", "description": "Свойство Figma: Shadow", "table": {"category": "Figma", "defaultValue": {"summary": "false"}}, "options": ["false", "true"]}, "Border": {"control": "inline-radio", "description": "Свойство Figma: Border", "table": {"category": "Figma", "defaultValue": {"summary": "false"}}, "options": ["false", "true"]}, "Disabled": {"control": "inline-radio", "description": "Свойство Figma: Disabled", "table": {"category": "Figma", "defaultValue": {"summary": "false"}}, "options": ["false", "true"]}, "children": {"control": "text", "table": {"category": "React"}, "description": "Содержимое компонента"}, "label": {"control": "text", "table": {"category": "React"}, "description": "Доступная подпись"}, "className": {"control": "text", "table": {"category": "React"}, "description": "Дополнительный CSS-класс"}, "onClick": {"control": false, "action": "onClick", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}, "onChange": {"control": false, "action": "onChange", "table": {"category": "Events"}, "description": "Обработчик взаимодействия"}},
  parameters: { layout: "padded", catalogId: "36238:395223", exportName: "Background", docs: { description: { component: "Background — компонент существующей базы UX-Lab.\n\n[Исходный компонент Figma](https://www.figma.com/design/SNBSKtwsO81j3BdjRGFpAw/?node-id=36238-395223) · 11 вариантов." } } },
} satisfies Meta<typeof Background>;
export default meta;
type Story = StoryObj<typeof meta>;
/** Живой пример; свойства меняются в Controls. */
export const Default: Story = {};
/** Полная исходная матрица, без искусственного декартова произведения. */
export const AllVariants: Story = { tags: ["!autodocs"], render: () => <VariantMatrix catalogId="36238:395223" component={Background} storyId="ds-36238-395223"/> };
/** Display: Plain · Shadow: false · Border: false · Disabled: false */
export const Variant001: Story = { name: "Display: Plain · Shadow: false · Border: false · Disabled: false", args: {"Display": "Plain", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Subdued · Shadow: false · Border: false · Disabled: false */
export const Variant002: Story = { name: "Display: Subdued · Shadow: false · Border: false · Disabled: false", args: {"Display": "Subdued", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Primary · Shadow: false · Border: false · Disabled: false */
export const Variant003: Story = { name: "Display: Primary · Shadow: false · Border: false · Disabled: false", args: {"Display": "Primary", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Success · Shadow: false · Border: false · Disabled: false */
export const Variant004: Story = { name: "Display: Success · Shadow: false · Border: false · Disabled: false", args: {"Display": "Success", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Warning · Shadow: false · Border: false · Disabled: false */
export const Variant005: Story = { name: "Display: Warning · Shadow: false · Border: false · Disabled: false", args: {"Display": "Warning", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Danger · Shadow: false · Border: false · Disabled: false */
export const Variant006: Story = { name: "Display: Danger · Shadow: false · Border: false · Disabled: false", args: {"Display": "Danger", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Accent · Shadow: false · Border: false · Disabled: false */
export const Variant007: Story = { name: "Display: Accent · Shadow: false · Border: false · Disabled: false", args: {"Display": "Accent", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Transparent · Shadow: false · Border: false · Disabled: false */
export const Variant008: Story = { name: "Display: Transparent · Shadow: false · Border: false · Disabled: false", args: {"Display": "Transparent", "Shadow": "false", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Plain · Shadow: true · Border: false · Disabled: false */
export const Variant009: Story = { name: "Display: Plain · Shadow: true · Border: false · Disabled: false", args: {"Display": "Plain", "Shadow": "true", "Border": "false", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Plain · Shadow: false · Border: true · Disabled: false */
export const Variant010: Story = { name: "Display: Plain · Shadow: false · Border: true · Disabled: false", args: {"Display": "Plain", "Shadow": "false", "Border": "true", "Disabled": "false"}, tags: ["!autodocs"] };
/** Display: Plain · Shadow: false · Border: false · Disabled: true */
export const Variant011: Story = { name: "Display: Plain · Shadow: false · Border: false · Disabled: true", args: {"Display": "Plain", "Shadow": "false", "Border": "false", "Disabled": "true"}, tags: ["!autodocs"] };
